/**
 * Battens and eaves.
 *
 * Generated from the estimator workbook (Tāme rows 70-88) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Latojums, m2 ----
  line({
    id: "latojums.starplatojums",
    row: 70,
    block: "latojums",
    name: "Starplatojums",
    unit: "m3",
    laborUnit: "m",
    qty: (c) => c.inp.batten_area_m2,
    reserve: 1.2,
    qtyRes: (c) => c.this.qty/c.inp.rafter_spacing_m*c.this.reserve*c.inp.counter_batten_thickness_m*c.inp.counter_batten_width_m,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('latojums.starplatojums_zagesana_pienaglosana'),
    blockMaterials: (c) => total(c.span('latojums.starplatojums', 'latojums.regulejamas_skruves_6x80_2gb_m2', 'materials')),
    blockLabor: (c) => total(c.span('latojums.starplatojums', 'latojums.regulejamas_skruves_6x80_2gb_m2', 'labor')),
    blockHours: (c) => total(c.span('latojums.starplatojums', 'latojums.regulejamas_skruves_6x80_2gb_m2', 'hours')),
    blockTotal: (c) => total(c.span('latojums.starplatojums', 'latojums.starplatojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis"],
  }),
  line({
    id: "latojums.naglu_lenta",
    row: 71,
    block: "latojums",
    name: "Naglu lenta",
    unit: "m",
    laborUnit: "m",
    note: "m",
    qty: (c) => c.line('latojums.starplatojums').qty/c.inp.rafter_spacing_m,
    reserve: 1.1,
    unitPrice: (c) => c.price('basic_naglu_lenta'),
    hoursPerUnit: (c) => c.norm('latojums.naglu_lenta_m'),
    blockTotal: (c) => total(c.span('latojums.naglu_lenta', 'latojums.naglu_lenta', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "basic_naglu_lenta"},
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3",
    row: 72,
    block: "latojums",
    name: "Naglas pneimatiskai pistolei Ø3.1xL90mm 34°, gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('latojums.starplatojums').qty/c.inp.rafter_spacing_m*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('naglas_pneimatiskai_pistolei_3_1xl90mm_34'),
    blockTotal: (c) => total(c.span('latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3', 'latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "naglas_pneimatiskai_pistolei_3_1xl90mm_34"},
    blank: ["hours"],
    tools: ["Naglu pistole", "Striķis un krīts"],
  }),
  line({
    id: "latojums.skerslatojums",
    row: 73,
    block: "latojums",
    name: "Šķērslatojums",
    unit: "m3",
    laborUnit: "m2",
    note: "25x100, solis 200mm (starpa 100mm)",
    qty: (c) => c.inp.batten_area_m2*c.inp.cross_batten_coverage_ratio/c.inp.cross_batten_width_m,
    reserve: 1.2,
    qtyRes: (c) => c.this.qty*c.inp.cross_batten_thickness_m*c.inp.cross_batten_width_m*c.this.reserve,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('latojums.skerslatojums_sprauga_100mm_zagesana_pie'),
    hours: (c) => c.this.hoursPerUnit*c.inp.batten_area_m2,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.batten_area_m2,
    blockTotal: (c) => total(c.span('latojums.skerslatojums', 'latojums.skerslatojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Striķis un krīts"],
  }),
  line({
    id: "latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3_2",
    row: 74,
    block: "latojums",
    name: "Naglas pneimatiskai pistolei Ø3.1xL90mm 34°, gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('latojums.skerslatojums').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('naglas_pneimatiskai_pistolei_3_1xl90mm_34'),
    blockTotal: (c) => total(c.span('latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3_2', 'latojums.naglas_pneimatiskai_pistolei_3_1xl90mm_3_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "naglas_pneimatiskai_pistolei_3_1xl90mm_34"},
    blank: ["hours"],
    tools: ["Naglu pistole"],
  }),
  line({
    id: "latojums.limenosana_starplatas",
    row: 75,
    block: "latojums",
    name: "Līmeņošana starplatas ",
    unit: "m3",
    laborUnit: "m2",
    note: "25x50",
    qty: (c) => c.inp.leveling_area_m2/c.inp.rafter_spacing_m,
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*0.025*0.05*c.this.reserve,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('latojums.limenosana_starplatas_ar_distanceriem_ev'),
    hours: (c) => c.this.hoursPerUnit*c.inp.leveling_area_m2,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.leveling_area_m2,
    blockTotal: (c) => total(c.span('latojums.limenosana_starplatas', 'latojums.limenosana_starplatas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Ēvele", "Cirkulārais zāģis", "Striķis un krīts"],
  }),
  line({
    id: "latojums.distanceri_gb_m",
    row: 76,
    block: "latojums",
    name: "Distanceri gb/m",
    unit: "gb",
    param: 2,
    qty: (c) => c.line('latojums.limenosana_starplatas').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('distanceris_kilis'),
    blockTotal: (c) => total(c.span('latojums.distanceri_gb_m', 'latojums.distanceri_gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "distanceris_kilis"},
    blank: ["hours"],
  }),
  line({
    id: "latojums.skruves_5x70_gb_m",
    row: 77,
    block: "latojums",
    name: "Skrūves 5x70 gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('latojums.limenosana_starplatas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('kokskruve_t_5x70'),
    blockTotal: (c) => total(c.span('latojums.skruves_5x70_gb_m', 'latojums.skruves_5x70_gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x70"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "latojums.regulejamas_skruves_6x80_2gb_m2",
    row: 78,
    block: "latojums",
    name: "Regulējamās skrūves 6x80, 2gb/m2",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*c.inp.leveling_area_m2,
    reserve: 1.1,
    unitPrice: (c) => c.price('regulejosa_skruve_6x80'),
    blockTotal: (c) => total(c.span('latojums.regulejamas_skruves_6x80_2gb_m2', 'latojums.regulejamas_skruves_6x80_2gb_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "regulejosa_skruve_6x80"},
    blank: ["hours"],
  }),

  // ---- Ventilējama Dzega, m ----
  line({
    id: "ventilejama_dzega.apakslasne_5_15_2_2_24cm",
    row: 79,
    block: "ventilejama_dzega",
    name: "Apakšlāsne (5+15+2+2=24cm)",
    unit: "m",
    laborUnit: "m",
    note: "Pa perimetru",
    qty: (c) => c.inp.eaves_ventilated_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('apakslasne_5_15_2_2_24cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('dzega.apakslasne_5_15_2_2_24cm_griesana_skruve'),
    blockMaterials: (c) => total(c.span('ventilejama_dzega.apakslasne_5_15_2_2_24cm', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3', 'materials')),
    blockLabor: (c) => total(c.span('ventilejama_dzega.apakslasne_5_15_2_2_24cm', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3', 'labor')),
    blockHours: (c) => total(c.span('ventilejama_dzega.apakslasne_5_15_2_2_24cm', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3', 'hours')),
    blockTotal: (c) => total(c.span('ventilejama_dzega.apakslasne_5_15_2_2_24cm', 'ventilejama_dzega.apakslasne_5_15_2_2_24cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "apakslasne_5_15_2_2_24cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m",
    row: 80,
    block: "ventilejama_dzega",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_dzega.apakslasne_5_15_2_2_24cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_dzega.kaiteku_siets_perferets_5_8_13cm",
    row: 81,
    block: "ventilejama_dzega",
    name: "Kaitēku siets Perferēts (5+8=13cm)",
    unit: "m",
    laborUnit: "m",
    note: "Pa perimetru",
    qty: (c) => c.inp.eaves_ventilated_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('kaiteku_siets_perferets_5_8_13cm', 'perforated_07'),
    hoursPerUnit: (c) => c.norm('dzega.kaiteku_siets_perferets_5_8_13cm_griesan'),
    blockTotal: (c) => total(c.span('ventilejama_dzega.kaiteku_siets_perferets_5_8_13cm', 'ventilejama_dzega.kaiteku_siets_perferets_5_8_13cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "kaiteku_siets_perferets_5_8_13cm", "variant": "perforated_07"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_2",
    row: 82,
    block: "ventilejama_dzega",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_dzega.kaiteku_siets_perferets_5_8_13cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_2', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_dzega.lasene_13_3_15_2_2_35cm",
    row: 83,
    block: "ventilejama_dzega",
    name: "Lāsene (13+3+15+2+2=35cm",
    unit: "m",
    laborUnit: "m",
    note: "Pa perimetru",
    qty: (c) => c.inp.eaves_ventilated_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('lasene_13_3_15_2_2_35cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('dzega.lasene_13_3_15_2_2_35cm_griesana_skruves'),
    blockTotal: (c) => total(c.span('ventilejama_dzega.lasene_13_3_15_2_2_35cm', 'ventilejama_dzega.lasene_13_3_15_2_2_35cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "lasene_13_3_15_2_2_35cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3",
    row: 84,
    block: "ventilejama_dzega",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_dzega.lasene_13_3_15_2_2_35cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3', 'ventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m_3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),

  // ---- Neventilējama dzega, m ----
  line({
    id: "neventilejama_dzega.apakslasne_5_15_2_2_24cm",
    row: 85,
    block: "neventilejama_dzega",
    name: "Apakšlāsne (5+15+2+2=24cm)",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.eaves_unventilated_m,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('apakslasne_5_15_2_2_24cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('dzega.apakslasne_5_15_2_2_24cm_griesana_skruve'),
    blockMaterials: (c) => total(c.span('neventilejama_dzega.apakslasne_5_15_2_2_24cm', 'neventilejama_dzega.kokskruves_5x70_4gb_m', 'materials')),
    blockLabor: (c) => total(c.span('neventilejama_dzega.apakslasne_5_15_2_2_24cm', 'neventilejama_dzega.kokskruves_5x70_4gb_m', 'labor')),
    blockHours: (c) => total(c.span('neventilejama_dzega.apakslasne_5_15_2_2_24cm', 'neventilejama_dzega.kokskruves_5x70_4gb_m', 'hours')),
    blockTotal: (c) => total(c.span('neventilejama_dzega.apakslasne_5_15_2_2_24cm', 'neventilejama_dzega.apakslasne_5_15_2_2_24cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "apakslasne_5_15_2_2_24cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "neventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m",
    row: 86,
    block: "neventilejama_dzega",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('neventilejama_dzega.apakslasne_5_15_2_2_24cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('neventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m', 'neventilejama_dzega.skruves_klemmeru_4_5x2_5_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "neventilejama_dzega.pieres_delis_2gb_100x25",
    row: 87,
    block: "neventilejama_dzega",
    name: "Pieres dēlis 2gb 100x25",
    unit: "m3",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.eaves_unventilated_m*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0)*0.025*0.1,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('bezasbesta_siferis.pieres_dela_montaza_montaza'),
    blockTotal: (c) => total(c.span('neventilejama_dzega.pieres_delis_2gb_100x25', 'neventilejama_dzega.pieres_delis_2gb_100x25', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Skrūvmašīna un uzgaļi", "Striķis un krīts"],
  }),
  line({
    id: "neventilejama_dzega.kokskruves_5x70_4gb_m",
    row: 88,
    block: "neventilejama_dzega",
    name: "Kokskrūves 5x70, 4gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('neventilejama_dzega.pieres_delis_2gb_100x25').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x70'),
    blockTotal: (c) => total(c.span('neventilejama_dzega.kokskruves_5x70_4gb_m', 'neventilejama_dzega.kokskruves_5x70_4gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x70"},
  }),
];
