/**
 * Chimney masonry and plaster.
 *
 * Generated from the estimator workbook (Tāme rows 281-308) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Skursteņu mūra atjaunošana, m2 ----
  line({
    id: "skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2",
    row: 281,
    block: "skurstenu_mura_atjaunosana",
    name: "Lodes ķieģeļi 250x120x65mm=0.03m2",
    unit: "gb",
    laborUnit: "gb",
    param: 0.03,
    qty: (c) => ceilUp(total([c.inp.chimney_rebuild_1_area_m2, c.inp.chimney_rebuild_2_area_m2, c.inp.chimney_rebuild_3_area_m2, c.inp.chimney_rebuild_4_area_m2, c.inp.chimney_rebuild_5_area_m2, c.inp.chimney_rebuild_6_area_m2])/c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('lodes_kiegeli_250x120x65mm'),
    hoursPerUnit: (c) => c.norm('skurstenu_mura_atj.lodes_kiegeli_250x120x65mm_0_03m2'),
    blockMaterials: (c) => total(c.span('skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2', 'skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'materials')),
    blockLabor: (c) => total(c.span('skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2', 'skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'labor')),
    blockHours: (c) => total(c.span('skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2', 'skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'hours')),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2', 'skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "lodes_kiegeli_250x120x65mm"},
    tools: ["Spainis", "Ķelle", "Javas maisītājs"],
  }),
  line({
    id: "skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie",
    row: 282,
    block: "skurstenu_mura_atjaunosana",
    name: "Mūrēšanas java Sakret ZM 25kg, 1gb/ 20 ķieģeļi",
    unit: "gb",
    laborUnit: "gb",
    param: 20,
    qty: (c) => ceilUp(c.line('skurstenu_mura_atjaunosana.lodes_kiegeli_250x120x65mm_0_03m2').qty/c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('muresanas_java_sakret_zm_25kg'),
    hoursPerUnit: (c) => c.norm('skurstenu_mura_atj.maisu_uzcelsana_un_javas_maisisana_maisu'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie', 'skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "muresanas_java_sakret_zm_25kg"},
  }),
  line({
    id: "skurstenu_mura_atjaunosana.udens_5l_1_maiss",
    row: 283,
    block: "skurstenu_mura_atjaunosana",
    name: "ūdens 5l/ 1 maiss",
    unit: "l",
    param: 5,
    qty: (c) => c.line('skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie').qty*c.this.param,
    reserve: 1.1,
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.udens_5l_1_maiss', 'skurstenu_mura_atjaunosana.udens_5l_1_maiss', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_mura_atjaunosana.spainis_16l_1gb_5_maisi",
    row: 284,
    block: "skurstenu_mura_atjaunosana",
    name: "Spainis 16L 1gb/5 maisi",
    unit: "gb",
    param: 5,
    qty: (c) => ceilUp(c.line('skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spainis_16l'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.spainis_16l_1gb_5_maisi', 'skurstenu_mura_atjaunosana.spainis_16l_1gb_5_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spainis_16l"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_mura_atjaunosana.javas_maisitajs_1gb_30_maisi",
    row: 285,
    block: "skurstenu_mura_atjaunosana",
    name: "Javas maisītājs, 1gb 30 maisi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('javas_maisitajs_1gb_30_maisi'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.javas_maisitajs_1gb_30_maisi', 'skurstenu_mura_atjaunosana.javas_maisitajs_1gb_30_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "javas_maisitajs_1gb_30_maisi"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstenu_mura_atjaunosana.kelle_1gb_10_maisi",
    row: 286,
    block: "skurstenu_mura_atjaunosana",
    name: "Ķelle, 1gb/10 maisi",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('skurstenu_mura_atjaunosana.muresanas_java_sakret_zm_25kg_1gb_20_kie').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('kelle_1gb_10_maisi'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.kelle_1gb_10_maisi', 'skurstenu_mura_atjaunosana.kelle_1gb_10_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kelle_1gb_10_maisi"},
    blank: ["hours"],
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "skurstenu_mura_atjaunosana.nosegsanas_materiali_1m2_1m2",
    row: 287,
    block: "skurstenu_mura_atjaunosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    laborUnit: "m2",
    param: 1,
    qty: (c) => c.this.param*total([c.inp.chimney_rebuild_1_area_m2, c.inp.chimney_rebuild_2_area_m2, c.inp.chimney_rebuild_3_area_m2, c.inp.chimney_rebuild_4_area_m2, c.inp.chimney_rebuild_5_area_m2, c.inp.chimney_rebuild_6_area_m2]),
    reserve: 1,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    hoursPerUnit: (c) => c.norm('skurstenu_mura_atj.nosegsanas_materiali_1m2_1m2_nosegsana'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.nosegsanas_materiali_1m2_1m2', 'skurstenu_mura_atjaunosana.nosegsanas_materiali_1m2_1m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
  }),
  line({
    id: "skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2",
    row: 288,
    block: "skurstenu_mura_atjaunosana",
    name: "PVC līmlenta nosegšanai, 1gb/10m2",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(total([c.inp.chimney_rebuild_1_area_m2, c.inp.chimney_rebuild_2_area_m2, c.inp.chimney_rebuild_3_area_m2, c.inp.chimney_rebuild_4_area_m2, c.inp.chimney_rebuild_5_area_m2, c.inp.chimney_rebuild_6_area_m2])/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('pvc_limlenta_nosegsanai'),
    blockTotal: (c) => total(c.span('skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'skurstenu_mura_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_limlenta_nosegsanai"},
    blank: ["hours"],
  }),

  // ---- Skursteņu apmetuma atjaunošana, m2 ----
  line({
    id: "skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo",
    row: 289,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Stiklšķiedras siets CT Gewebe 650 Caparol, m2",
    unit: "m2",
    laborUnit: "m2",
    note: "stiklšķiedras m2- skursteņa m2",
    qty: (c) => total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2]),
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('stiklskiedras_siets_ct_gewebe_650_caparol_m2'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.apmesanas_siets_stiklskiedras_sieta_lime'),
    blockMaterials: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo', 'skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2', 'materials')),
    blockLabor: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo', 'skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2', 'labor')),
    blockHours: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo', 'skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2', 'hours')),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo', 'skurstenu_apmetuma_atjaunosana.stiklskiedras_siets_ct_gewebe_650_caparo', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "stiklskiedras_siets_ct_gewebe_650_caparol_m2"},
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.siets_sturisi_m",
    row: 290,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Siets stūrīši, m",
    unit: "m",
    qty: (c) => total([c.inp.chimney_plaster_1_height_m, c.inp.chimney_plaster_2_height_m, c.inp.chimney_plaster_3_height_m, c.inp.chimney_plaster_4_height_m, c.inp.chimney_plaster_5_height_m])*4,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('siets_sturisi_m'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.siets_sturisi_m', 'skurstenu_apmetuma_atjaunosana.siets_sturisi_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "siets_sturisi_m"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb",
    row: 291,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Līmjava BAK 25kg 3m2/ gb",
    unit: "gb",
    laborUnit: "gb",
    param: 3,
    qty: (c) => ceilUp(total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])/3, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('limjava_bak_25kg_3m2_gb'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.maisu_uzcelsana_un_javas_maisisana_maisu'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb', 'skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "limjava_bak_25kg_3m2_gb"},
    tools: ["Spainis 16L", "Ķelle", "Javas maisītājs", "Spakteļlāpstiņas"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.dzilumgrunts_1l_2m2",
    row: 292,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Dziļumgrunts 1l/2m2",
    unit: "l",
    param: 2,
    qty: (c) => total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('dzilumgrunts_cena_l'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.dzilumgrunts_1l_2m2', 'skurstenu_apmetuma_atjaunosana.dzilumgrunts_1l_2m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dzilumgrunts_cena_l"},
    blank: ["hours", "labor", "total"],
    tools: ["Ota Lielā"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.udens_5l_maiss",
    row: 293,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "ūdens 5l/maiss",
    unit: "l",
    param: 5,
    qty: (c) => c.this.param*c.line('skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb').qty,
    reserve: 1.1,
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.udens_5l_maiss', 'skurstenu_apmetuma_atjaunosana.udens_5l_maiss', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.spainis_16l_1gb_5_maisi",
    row: 294,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Spainis 16L 1gb/5 maisi",
    unit: "gb",
    param: 5,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spainis_16l'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.spainis_16l_1gb_5_maisi', 'skurstenu_apmetuma_atjaunosana.spainis_16l_1gb_5_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spainis_16l"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi",
    row: 295,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Javas maisītājs, 1gb 30 maisi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('javas_maisitajs_1gb_30_maisi'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi', 'skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "javas_maisitajs_1gb_30_maisi"},
    blank: ["hours"],
    tools: ["Urbjmašīna", "Būvgružu maisi"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_3_maisi",
    row: 296,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Špakteles lāpsitiņa, 1gb/3 maisi",
    unit: "gb",
    param: 3,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.limjava_bak_25kg_3m2_gb').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spakteles_lapsitina'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_3_maisi', 'skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_3_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spakteles_lapsitina"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2",
    row: 297,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    laborUnit: "m2",
    param: 1,
    qty: (c) => total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])*c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.nosegsanas_materiali_1m2_1m2_nosegsana'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2', 'skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2",
    row: 298,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "PVC līmlenta nosegšanai, 1gb/10m2",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('pvc_limlenta_nosegsanai'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_limlenta_nosegsanai"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2",
    row: 299,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Apmetums Sakret CLP+25kg,  1 maiss 2m2",
    unit: "gb",
    laborUnit: "m2",
    param: 2,
    qty: (c) => ceilUp(total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])/c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('apmetums_sakret_clp_25kg_1_maiss_2m2'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.apmetums_sakret_clp_25kg_1_maiss_2m2_apm'),
    hours: (c) => c.this.hoursPerUnit*total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2]),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2', 'skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "apmetums_sakret_clp_25kg_1_maiss_2m2"},
    tools: ["Spainis 16L", "Ķelle", "Javas maisītājs", "Spakteļlāpstiņas"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.maisisana_darbs",
    row: 300,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Maisīšana, darbs",
    unit: "gb",
    laborUnit: "gb",
    note: "maisīšana, darbība",
    qty: (c) => c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.maisu_uzcelsana_un_javas_maisisana_maisu_2'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.maisisana_darbs', 'skurstenu_apmetuma_atjaunosana.maisisana_darbs', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.udens_5l_1_maiss",
    row: 301,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "ūdens 5l/ 1 maiss",
    unit: "l",
    param: 5,
    qty: (c) => c.this.param*c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty,
    reserve: 1.1,
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.udens_5l_1_maiss', 'skurstenu_apmetuma_atjaunosana.udens_5l_1_maiss', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.spainis_1gb_5_maisi",
    row: 302,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Spainis 1gb/5 maisi",
    unit: "gb",
    param: 5,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spainis_16l'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.spainis_1gb_5_maisi', 'skurstenu_apmetuma_atjaunosana.spainis_1gb_5_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spainis_16l"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi_2",
    row: 303,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Javas maisītājs, 1gb 30 maisi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('javas_maisitajs_1gb_30_maisi'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi_2', 'skurstenu_apmetuma_atjaunosana.javas_maisitajs_1gb_30_maisi_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "javas_maisitajs_1gb_30_maisi"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_10_maisi",
    row: 304,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Špakteles lāpsitiņa, 1gb/10 maisi",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spakteles_lapsitina'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_10_maisi', 'skurstenu_apmetuma_atjaunosana.spakteles_lapsitina_1gb_10_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spakteles_lapsitina"},
    blank: ["hours"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.sturu_kelle_1gb_10_maisi",
    row: 305,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Stūru ķelle, 1gb/10 maisi",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('sturu_kelle_1gb_10_maisi'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.sturu_kelle_1gb_10_maisi', 'skurstenu_apmetuma_atjaunosana.sturu_kelle_1gb_10_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sturu_kelle_1gb_10_maisi"},
    blank: ["hours"],
    tools: ["Stūru ķelle", "Putoplasta rīve"],
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.rive_1gb_10_maisi",
    row: 306,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Rīve 1gb/10 maisi",
    unit: "gb",
    laborUnit: "m2",
    param: 10,
    qty: (c) => ceilUp(c.line('skurstenu_apmetuma_atjaunosana.apmetums_sakret_clp_25kg_1_maiss_2m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('rive_1gb_10_maisi'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.apstrade_rivesana_sturu_izveide_lizinasa'),
    hours: (c) => c.this.hoursPerUnit*total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2]),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.rive_1gb_10_maisi', 'skurstenu_apmetuma_atjaunosana.rive_1gb_10_maisi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "rive_1gb_10_maisi"},
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2_2",
    row: 307,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    laborUnit: "m2",
    param: 1,
    qty: (c) => total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])*c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    hoursPerUnit: (c) => c.norm('skurstenu_apmetuma.nosegsanas_materiali_1m2_1m2_nosegsana_2'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2_2', 'skurstenu_apmetuma_atjaunosana.nosegsanas_materiali_1m2_1m2_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
  }),
  line({
    id: "skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2",
    row: 308,
    block: "skurstenu_apmetuma_atjaunosana",
    name: "PVC līmlenta nosegšanai, 1gb/10m2",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(total([c.inp.chimney_plaster_1_area_m2, c.inp.chimney_plaster_2_area_m2, c.inp.chimney_plaster_3_area_m2, c.inp.chimney_plaster_4_area_m2, c.inp.chimney_plaster_5_area_m2])/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('pvc_limlenta_nosegsanai'),
    blockTotal: (c) => total(c.span('skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2', 'skurstenu_apmetuma_atjaunosana.pvc_limlenta_nosegsanai_1gb_10m2_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_limlenta_nosegsanai"},
    blank: ["hours"],
    tools: ["Nazis un asmeņi", "Slota un šaufele", "Būvgružu maisi"],
  }),
];
