/**
 * Chimney cladding and caps.
 *
 * Generated from the estimator workbook (Tāme rows 194-213) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Skursteņa apdare, valcētas loksnes, m2 ----
  line({
    id: "skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne",
    row: 194,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Cementa šķiedras plāksne",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => total([c.inp.chimney_cladding_1_area_m2, c.inp.chimney_cladding_2_area_m2, c.inp.chimney_cladding_3_area_m2, c.inp.chimney_cladding_4_area_m2, c.inp.chimney_cladding_5_area_m2, c.inp.chimney_cladding_6_area_m2, c.inp.chimney_cladding_7_area_m2]),
    reserve: 1.5,
    unitPrice: (c) => c.price('cementa_skiedras_plaksne_m2'),
    hoursPerUnit: (c) => c.norm('skurstena_apdare_v.cementa_skiedras_plaksne_griesana_dibelo'),
    blockMaterials: (c) => total(c.span('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne', 'skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m', 'materials')),
    blockLabor: (c) => total(c.span('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne', 'skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m', 'labor')),
    blockHours: (c) => total(c.span('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne', 'skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m', 'hours')),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne', 'skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "cementa_skiedras_plaksne_m2"},
    tools: ["Fleksis", "Dimanta ripa"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.distanceri_10gb_m2",
    row: 195,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Distanceri, 10gb/m2",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('distanceris_kilis'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.distanceri_10gb_m2', 'skurstena_apdare_valcetas_loksne.distanceri_10gb_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "distanceris_kilis"},
    blank: ["hours"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.dibelnaglas_6x50_10gb_m2",
    row: 196,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Dībeļnaglas 6x50, 10gb/m2",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('dibelnaglas_ar_gremdgalvu_6x50mm'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.dibelnaglas_6x50_10gb_m2', 'skurstena_apdare_valcetas_loksne.dibelnaglas_6x50_10gb_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dibelnaglas_ar_gremdgalvu_6x50mm"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli",
    row: 197,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Urbis ķieģeļiem 7mm, 1gb/30 dībeļi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('skurstena_apdare_valcetas_loksne.dibelnaglas_6x50_10gb_m2').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('urbis_betonam_7mm'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli', 'skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_7mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.starplatojums_25x50_vertikali_ik_pa_40cm",
    row: 198,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Starplatojums 25x50, Vertikāli Ik pa 40cm",
    unit: "m3",
    laborUnit: "m2",
    param: (c) => total([c.inp.chimney_cladding_1_perimeter_m, c.inp.chimney_cladding_2_perimeter_m, c.inp.chimney_cladding_3_perimeter_m, c.inp.chimney_cladding_4_perimeter_m, c.inp.chimney_cladding_5_perimeter_m, c.inp.chimney_cladding_6_perimeter_m, c.inp.chimney_cladding_7_perimeter_m])/0.4*2,
    qty: (c) => c.this.param*total([c.inp.chimney_cladding_1_height_m, c.inp.chimney_cladding_2_height_m, c.inp.chimney_cladding_3_height_m, c.inp.chimney_cladding_4_height_m, c.inp.chimney_cladding_5_height_m, c.inp.chimney_cladding_6_height_m, c.inp.chimney_cladding_7_height_m]),
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.025*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('skurstena_apdare_v.starplatojums_25x50_vertikali_ik_pa_40cm'),
    hours: (c) => c.this.hoursPerUnit*total([c.inp.chimney_cladding_1_area_m2, c.inp.chimney_cladding_2_area_m2, c.inp.chimney_cladding_3_area_m2, c.inp.chimney_cladding_4_area_m2, c.inp.chimney_cladding_5_area_m2, c.inp.chimney_cladding_6_area_m2, c.inp.chimney_cladding_7_area_m2]),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.line('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne').qty*c.this.rate,
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.starplatojums_25x50_vertikali_ik_pa_40cm', 'skurstena_apdare_valcetas_loksne.starplatojums_25x50_vertikali_ik_pa_40cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Zobenzāģis", "līmeņrādis"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.dibelnaglas_6x70_2gb_m",
    row: 199,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Dībeļnaglas 6x70, 2gb/m",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*c.line('skurstena_apdare_valcetas_loksne.starplatojums_25x50_vertikali_ik_pa_40cm').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('dibelnaglas_ar_gremdgalvu_6x50mm'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.dibelnaglas_6x70_2gb_m', 'skurstena_apdare_valcetas_loksne.dibelnaglas_6x70_2gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dibelnaglas_ar_gremdgalvu_6x50mm"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi", "āmurs", "stangas"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli_2",
    row: 200,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Urbis ķieģeļiem 7mm, 1gb/30 dībeļi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('skurstena_apdare_valcetas_loksne.dibelnaglas_6x70_2gb_m').qtyRes/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('urbis_betonam_7mm'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli_2', 'skurstena_apdare_valcetas_loksne.urbis_kiegeliem_7mm_1gb_30_dibeli_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_7mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.skerslatojums_25x100_sprauga_20cm",
    row: 201,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Šķērslatojums 25x100, sprauga 20cm)",
    unit: "m3",
    laborUnit: "m2",
    param: (c) => total([c.inp.chimney_cladding_1_area_m2, c.inp.chimney_cladding_2_area_m2, c.inp.chimney_cladding_3_area_m2, c.inp.chimney_cladding_4_area_m2, c.inp.chimney_cladding_5_area_m2, c.inp.chimney_cladding_6_area_m2, c.inp.chimney_cladding_7_area_m2])/2.5/0.1,
    qty: (c) => c.this.param,
    reserve: 1.2,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.025*0.1,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('skurstena_apdare_v.skerslatojums_25x100_sprauga_20cm_zagesa'),
    hours: (c) => c.this.hoursPerUnit*total([c.inp.chimney_cladding_1_area_m2, c.inp.chimney_cladding_2_area_m2, c.inp.chimney_cladding_3_area_m2, c.inp.chimney_cladding_4_area_m2, c.inp.chimney_cladding_5_area_m2, c.inp.chimney_cladding_6_area_m2, c.inp.chimney_cladding_7_area_m2]),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.line('skurstena_apdare_valcetas_loksne.cementa_skiedras_plaksne').qty,
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.skerslatojums_25x100_sprauga_20cm', 'skurstena_apdare_valcetas_loksne.skerslatojums_25x100_sprauga_20cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Zobenzāģis"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.kokskruves_4_5x45_4gb_m",
    row: 202,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Kokskrūves 4.5x45, 4gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('skurstena_apdare_valcetas_loksne.skerslatojums_25x100_sprauga_20cm').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('kokskruve_t_4_5x45'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.kokskruves_4_5x45_4gb_m', 'skurstena_apdare_valcetas_loksne.kokskruves_4_5x45_4gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4_5x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.valcprofila_loksnes",
    row: 203,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Valcprofila loksnes",
    unit: "m2",
    laborUnit: "m2",
    note: "m2",
    qty: (c) => total([c.inp.chimney_cladding_1_area_m2, c.inp.chimney_cladding_2_area_m2, c.inp.chimney_cladding_3_area_m2, c.inp.chimney_cladding_4_area_m2, c.inp.chimney_cladding_5_area_m2, c.inp.chimney_cladding_6_area_m2, c.inp.chimney_cladding_7_area_m2]),
    reserve: 1.5,
    unitPrice: (c) => c.price('valcprofils_rukki'),
    hoursPerUnit: (c) => c.norm('skurstena_apdare_v.valcprofila_loksnes_klemmeri_aizvalcesan'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.valcprofila_loksnes', 'skurstena_apdare_valcetas_loksne.valcprofila_loksnes', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcprofils_rukki"},
    tools: ["Skārdnieka instrumenti, aizvalcētājs", "Striķis un krīts"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.klemmeri_7gb_m2",
    row: 204,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Klemmeri 7gb/m2",
    unit: "gb",
    param: 7,
    qty: (c) => c.this.param*c.line('skurstena_apdare_valcetas_loksne.valcprofila_loksnes').qty,
    reserve: 1.2,
    unitPrice: (c) => c.price('klemmeri'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.klemmeri_7gb_m2', 'skurstena_apdare_valcetas_loksne.klemmeri_7gb_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri"},
    blank: ["hours"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_3gb_x_klemmeru_s",
    row: 205,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Klemmeru skrūves 4.5x25, 3gb x klemmeru skaits",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('skurstena_apdare_valcetas_loksne.klemmeri_7gb_m2').qty*c.this.param,
    reserve: 1.2,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_3gb_x_klemmeru_s', 'skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_3gb_x_klemmeru_s', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.loksnu_materials_125cm",
    row: 206,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Lokšņu materiāls 125cm",
    note: "m2",
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.loksnu_materials_125cm', 'skurstena_apdare_valcetas_loksne.loksnu_materials_125cm', 'blockMaterials', 'blockLabor')),
    blank: ["qtyRes", "hours"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.sturu_listes_ar_mazajam_valcem_3_5_10_10",
    row: 207,
    block: "skurstena_apdare_valcetas_loksne",
    name: "stūru līstes ar mazajām valcēm (3.5+10+10+3.5= 27cm), 4gb x skursteņa augstums",
    unit: "m",
    laborUnit: "m",
    param: 4,
    qty: (c) => total([c.inp.chimney_cladding_1_height_m, c.inp.chimney_cladding_2_height_m, c.inp.chimney_cladding_3_height_m, c.inp.chimney_cladding_4_height_m, c.inp.chimney_cladding_5_height_m, c.inp.chimney_cladding_6_height_m, c.inp.chimney_cladding_7_height_m])*c.this.param,
    reserve: 1.3,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.profile('sturu_listes_ar_mazajam_valcem_3_5_1', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('skurstena_apdare_v.sturu_listes_ar_mazajam_valcem_3_5_10_10'),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.this.qtyRes,
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.sturu_listes_ar_mazajam_valcem_3_5_10_10', 'skurstena_apdare_valcetas_loksne.sturu_listes_ar_mazajam_valcem_3_5_10_10', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "sturu_listes_ar_mazajam_valcem_3_5_1", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.skurstena_zem_jumtina_nosegelemnts_17_3",
    row: 208,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Skursteņa zem jumtiņa nosegelemnts (17+3=20cm)",
    unit: "m",
    qty: (c) => total([c.inp.chimney_cladding_1_perimeter_m, c.inp.chimney_cladding_2_perimeter_m, c.inp.chimney_cladding_3_perimeter_m, c.inp.chimney_cladding_4_perimeter_m, c.inp.chimney_cladding_5_perimeter_m, c.inp.chimney_cladding_6_perimeter_m, c.inp.chimney_cladding_7_perimeter_m]),
    reserve: 1.2,
    unitPrice: (c) => c.profile('nosegelemnts_zem_skurstena_jumtina_1', 'rukki_05'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.skurstena_zem_jumtina_nosegelemnts_17_3', 'skurstena_apdare_valcetas_loksne.skurstena_zem_jumtina_nosegelemnts_17_3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "nosegelemnts_zem_skurstena_jumtina_1", "variant": "rukki_05"},
    blank: ["hours"],
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m",
    row: 209,
    block: "skurstena_apdare_valcetas_loksne",
    name: "Klemmeru skrūves 4.5x25, 5gb/m",
    unit: "gb",
    param: 5,
    qty: (c) => c.line('skurstena_apdare_valcetas_loksne.sturu_listes_ar_mazajam_valcem_3_5_10_10').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m', 'skurstena_apdare_valcetas_loksne.klemmeru_skruves_4_5x25_5gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),

  // ---- Skursteņa jumtiņs, gb ----
  line({
    id: "skurstena_jumtins.skurstena_jumtins_bez_ekrana",
    row: 210,
    block: "skurstena_jumtins",
    name: "Skursteņa jumtiņš bez ekrāna",
    unit: "m2",
    laborUnit: "gb",
    param: (c) => c.countFilled('chimney_cap_plain_1_length_m', 'chimney_cap_plain_2_length_m', 'chimney_cap_plain_3_length_m', 'chimney_cap_plain_4_length_m'),
    qty: (c) => c.countFilled('chimney_cap_plain_1_length_m', 'chimney_cap_plain_2_length_m', 'chimney_cap_plain_3_length_m', 'chimney_cap_plain_4_length_m', 'chimney_cap_screen_1_length_m', 'chimney_cap_screen_2_length_m', 'chimney_cap_screen_3_length_m'),
    reserve: 1,
    qtyRes: (c) => total([c.inp.chimney_cap_plain_1_area_m2, c.inp.chimney_cap_plain_2_area_m2, c.inp.chimney_cap_plain_3_area_m2, c.inp.chimney_cap_plain_4_area_m2])*c.this.reserve,
    unitPrice: (c) => c.price('skurstena_jumtins_bez_ekrana_cena_m2'),
    hoursPerUnit: (c) => c.norm('skurstena_jumtina.skurstena_jumtins_uzcelsana_dibelosana'),
    hours: (c) => c.this.hoursPerUnit*c.this.param,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.this.param,
    blockMaterials: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_bez_ekrana', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem', 'materials')),
    blockLabor: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_bez_ekrana', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem', 'labor')),
    blockHours: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_bez_ekrana', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2', 'hours')),
    blockTotal: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_bez_ekrana', 'skurstena_jumtins.skurstena_jumtins_bez_ekrana', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "skurstena_jumtins_bez_ekrana_cena_m2"},
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem",
    row: 211,
    block: "skurstena_jumtins",
    name: "Jumta skrūves 4.8x35mm,15gb ar dībeļiem",
    unit: "gb",
    param: 15,
    qty: (c) => c.line('skurstena_jumtins.skurstena_jumtins_bez_ekrana').param*c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_skruves_4_8x35'),
    blockTotal: (c) => total(c.span('skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x35"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "skurstena_jumtins.skurstena_jumtins_ar_ekranu",
    row: 212,
    block: "skurstena_jumtins",
    name: "Skursteņa jumtiņš ar ekrānu",
    unit: "m2",
    laborUnit: "gb",
    param: (c) => c.countFilled('chimney_cap_screen_1_length_m', 'chimney_cap_screen_2_length_m', 'chimney_cap_screen_3_length_m'),
    qty: (c) => total([c.inp.chimney_cap_screen_1_area_m2, c.inp.chimney_cap_screen_2_area_m2, c.inp.chimney_cap_screen_3_area_m2]),
    reserve: 1,
    unitPrice: (c) => c.price('skurstena_jumtins_ar_ekranu_cena_m2'),
    hoursPerUnit: (c) => c.norm('skurstena_jumtina.skurstena_jumtins_uzcelsana_dibelosana'),
    hours: (c) => c.this.hoursPerUnit*c.this.param,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.this.param,
    blockMaterials: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_ar_ekranu', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2', 'materials')),
    blockLabor: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_ar_ekranu', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2', 'labor')),
    blockTotal: (c) => total(c.span('skurstena_jumtins.skurstena_jumtins_ar_ekranu', 'skurstena_jumtins.skurstena_jumtins_ar_ekranu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "skurstena_jumtins_ar_ekranu_cena_m2"},
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2",
    row: 213,
    block: "skurstena_jumtins",
    name: "Jumta skrūves 4.8x35mm,15gb ar dībeļiem",
    unit: "gb",
    param: 15,
    qty: (c) => c.line('skurstena_jumtins.skurstena_jumtins_ar_ekranu').param*c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_skruves_4_8x35'),
    blockTotal: (c) => total(c.span('skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2', 'skurstena_jumtins.jumta_skruves_4_8x35mm_15gb_ar_dibeliem_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x35"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
];
