/**
 * Demolition and lifting.
 *
 * Generated from the estimator workbook (Tāme rows 2-24) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Demontāža ar nocelšanu, m2 ----
  line({
    id: "demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2",
    row: 2,
    block: "demontaza_ar_nocelsanu",
    name: "Šīfera demontāža 12kg/m2",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_slate_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.sifera_demontaza_demontaza'),
    blockMaterials: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_40m2', 'materials')),
    blockLabor: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_40m2', 'labor')),
    blockHours: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'demontaza_ar_nocelsanu.fleksa_ripas_1gb_5m', 'hours')),
    blockTotal: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'demontaza_ar_nocelsanu.fleksa_ripas_1gb_5m', 'blockMaterials', 'blockLabor')),
    tools: ["lauznis"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.apgerbs_sifera_demontazai_vienreizejas_l",
    row: 3,
    block: "demontaza_ar_nocelsanu",
    name: "Apģērbs šīfera demontāžai, vienreizējās lietošanas virsvalks, cimdi, respirators P3, mazgājami apavi 1gb/ 50m2",
    unit: "gb",
    param: 50,
    qty: (c) => ceilUp(c.inp.demo_slate_m2/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('apgerbs_sifera_demontazai_vienreizejas_lieto'),
    priceRef: {"type": "mat", "id": "apgerbs_sifera_demontazai_vienreizejas_lieto"},
    blank: ["labor"],
    tools: ["aizsargtērps", "respirātors"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_40m2",
    row: 4,
    block: "demontaza_ar_nocelsanu",
    name: "Big bag 90x90x110cm 1gb/40m2",
    unit: "gb",
    param: 40,
    qty: (c) => c.line('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('big_bag_90x90x110cm'),
    priceRef: {"type": "mat", "id": "big_bag_90x90x110cm"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_gb",
    row: 5,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, gb",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.line('demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_40m2').qtyRes,
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.valcprofila_demontaza",
    row: 6,
    block: "demontaza_ar_nocelsanu",
    name: "Valcprofila demontāža",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_standing_seam_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.valcprofila_demontaza_demontaza'),
    blockMaterials: (c) => total(c.this.materials),
    blockLabor: (c) => total(c.this.labor),
    tools: ["valcgriezējs", "lauznis", "šķēres"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_1gb_100m2",
    row: 7,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, 1gb / 100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.line('demontaza_ar_nocelsanu.valcprofila_demontaza').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.skarda_loksnu_demontaza",
    row: 8,
    block: "demontaza_ar_nocelsanu",
    name: "Skārda loksņu demontāža",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_sheet_metal_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.skarda_loksnu_demontaza_demontaza'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    tools: ["skrūvmašīna", "Muciņa 8mm", "lauznis"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_1gb_100m2_2",
    row: 9,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, 1gb / 100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.line('demontaza_ar_nocelsanu.skarda_loksnu_demontaza').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.sindelu_demontaza",
    row: 10,
    block: "demontaza_ar_nocelsanu",
    name: "Šindeļu demontāža",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_shingles_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.sindelu_demontaza_demontaza'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    tools: ["lāpstas", "lauznis", "dakša"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_1gb_100m2_3",
    row: 11,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, 1gb / 100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.line('demontaza_ar_nocelsanu.sindelu_demontaza').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.dakstinu_demontaza_50kg_m2",
    row: 12,
    block: "demontaza_ar_nocelsanu",
    name: "Dakstiņu demontāža, 50kg/m2",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_tiles_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.dakstinu_demontaza_demontaza'),
    blockMaterials: (c) => total(c.span('demontaza_ar_nocelsanu.dakstinu_demontaza_50kg_m2', 'demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_10m2', 'materials')),
    blockLabor: (c) => total(c.span('demontaza_ar_nocelsanu.dakstinu_demontaza_50kg_m2', 'demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_10m2', 'labor')),
    tools: ["lauznis"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_10m2",
    row: 13,
    block: "demontaza_ar_nocelsanu",
    name: "Big bag 90x90x110cm 1gb/10m2",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('demontaza_ar_nocelsanu.dakstinu_demontaza_50kg_m2').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('big_bag_90x90x110cm'),
    priceRef: {"type": "mat", "id": "big_bag_90x90x110cm"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_gb_2",
    row: 14,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, gb",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.line('demontaza_ar_nocelsanu.big_bag_90x90x110cm_1gb_10m2').qtyRes,
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => total(c.this.materials),
    blockLabor: (c) => total(c.this.labor),
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.latojuma_demontaza",
    row: 15,
    block: "demontaza_ar_nocelsanu",
    name: "Latojuma demontāža",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_battens_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.latojuma_demontaza_demontaza'),
    blockMaterials: (c) => total(c.this.materials),
    blockLabor: (c) => total(c.this.labor),
    tools: ["lauznis", "zāģis", "āmurs"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_1gb_100m2_4",
    row: 16,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, 1gb / 100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.line('demontaza_ar_nocelsanu.latojuma_demontaza').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => total(c.this.materials),
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.jumta_konstrukcijas_demontaza",
    row: 17,
    block: "demontaza_ar_nocelsanu",
    name: "Jumta konstrukcijas demontāža",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.demo_structure_m2,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.jumta_konstrukcijas_demontaza_demontaza'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    tools: ["lauznis", "zāģis", "āmurs"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.nocelsana_1gb_200m2",
    row: 18,
    block: "demontaza_ar_nocelsanu",
    name: "Nocelšana, 1gb / 200m2",
    unit: "gb",
    laborUnit: "gb",
    param: 200,
    qty: (c) => ceilUp(c.line('demontaza_ar_nocelsanu.jumta_konstrukcijas_demontaza').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_nocelsana_gb'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.nocelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    priceRef: {"type": "mat", "id": "materialu_nocelsana_gb"},
  }),
  line({
    id: "demontaza_ar_nocelsanu.noteksistemas_demontaza_m",
    row: 19,
    block: "demontaza_ar_nocelsanu",
    name: "Noteksistēmas demontāža, m",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.demo_gutters_m,
    reserve: 1.1,
    hoursPerUnit: (c) => c.norm('demontaza.noteksistemas_demontaza_m_demontaza'),
    blockMaterials: (c) => total(c.span('demontaza_ar_nocelsanu.noteksistemas_demontaza_m', 'demontaza_ar_nocelsanu.fleksa_ripas_1gb_5m', 'materials')),
    blockLabor: (c) => total(c.span('demontaza_ar_nocelsanu.noteksistemas_demontaza_m', 'demontaza_ar_nocelsanu.fleksa_ripas_1gb_5m', 'labor')),
    tools: ["lauznis", "fleksis"],
  }),
  line({
    id: "demontaza_ar_nocelsanu.fleksa_ripas_1gb_5m",
    row: 20,
    block: "demontaza_ar_nocelsanu",
    name: "Flekša ripas, 1gb/5m",
    unit: "gb",
    param: 5,
    qty: (c) => c.line('demontaza_ar_nocelsanu.noteksistemas_demontaza_m').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('fleksa_ripa_125mm'),
    priceRef: {"type": "mat", "id": "fleksa_ripa_125mm"},
  }),

  // ---- Uzcelšana ----
  line({
    id: "uzcelsana.latojuma_uzcelsana_1gb_100m2",
    row: 21,
    block: "uzcelsana",
    name: "Latojuma uzcelšana 1gb/100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.inp.batten_area_m2/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_uzcelsana'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.uzcelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockHours: (c) => total(c.span('uzcelsana.latojuma_uzcelsana_1gb_100m2', 'uzcelsana.jumta_siltinajuma_uzcelsana_1gb_100m2', 'hours')),
    blockTotal: (c) => total(c.span('uzcelsana.latojuma_uzcelsana_1gb_100m2', 'uzcelsana.latojuma_uzcelsana_1gb_100m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "materialu_uzcelsana"},
    tools: ["Rācija", "Štropes"],
  }),
  line({
    id: "uzcelsana.valcprofila_uzcelsana_1gb_100m2",
    row: 22,
    block: "uzcelsana",
    name: "Valcprofila uzcelšana 1gb/100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(total([c.inp.seam_zn_m2, c.inp.seam_rukki_m2])/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_uzcelsana'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.uzcelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('uzcelsana.valcprofila_uzcelsana_1gb_100m2', 'uzcelsana.valcprofila_uzcelsana_1gb_100m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "materialu_uzcelsana"},
    tools: ["Rācija", "Štropes"],
  }),
  line({
    id: "uzcelsana.jumta_konstrukcijas_uzcelsana_1gb_100m2",
    row: 23,
    block: "uzcelsana",
    name: "Jumta konstrukcijas uzcelšana 1gb/100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(c.inp.demo_structure_m2/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_uzcelsana'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.uzcelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('uzcelsana.jumta_konstrukcijas_uzcelsana_1gb_100m2', 'uzcelsana.jumta_konstrukcijas_uzcelsana_1gb_100m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "materialu_uzcelsana"},
    tools: ["Rācija", "Štropes"],
  }),
  line({
    id: "uzcelsana.jumta_siltinajuma_uzcelsana_1gb_100m2",
    row: 24,
    block: "uzcelsana",
    name: "Jumta siltinājuma uzcelšana 1gb/100m2",
    unit: "gb",
    laborUnit: "gb",
    param: 100,
    qty: (c) => ceilUp(total([c.inp.insulation_150_m2, c.inp.insulation_200_m2])/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('materialu_uzcelsana'),
    hoursPerUnit: (c) => c.norm('uzcelsana_nocelsan.uzcelsana_gb_palidzet_celamkranam'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('uzcelsana.jumta_siltinajuma_uzcelsana_1gb_100m2', 'uzcelsana.jumta_siltinajuma_uzcelsana_1gb_100m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "materialu_uzcelsana"},
    tools: ["Rācija", "Štropes"],
  }),
];
