/**
 * Abutments, chimney flashing, vents, hatches, parapet.
 *
 * Generated from the estimator workbook (Tāme rows 128-173) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Sienas pieslēgums, m ----
  line({
    id: "sienas_pieslegums.uzlocits_skards_30cm",
    row: 128,
    block: "sienas_pieslegums",
    name: "Uzlocīts skārds ~30cm",
    unit: "m",
    laborUnit: "m",
    note: "Darbība + ruļļu materiāls",
    qty: (c) => c.inp.wall_abutment_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => 0.3*c.price('valcprofils_rukki'),
    hoursPerUnit: (c) => c.norm('sienas_pieslegums.uzlocits_skards_30cm_locisana_dibelosana'),
    blockMaterials: (c) => total(c.span('sienas_pieslegums.uzlocits_skards_30cm', 'sienas_pieslegums.hermetikis_pu', 'materials')),
    blockLabor: (c) => total(c.span('sienas_pieslegums.uzlocits_skards_30cm', 'sienas_pieslegums.hermetikis_pu', 'labor')),
    blockHours: (c) => total(c.span('sienas_pieslegums.uzlocits_skards_30cm', 'sienas_pieslegums.hermetikis_pu', 'hours')),
    blockTotal: (c) => total(c.span('sienas_pieslegums.uzlocits_skards_30cm', 'sienas_pieslegums.uzlocits_skards_30cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcprofils_rukki"},
    tools: ["Benderis", "Lielās pacelšanas stangas", "Skārdnieka instrumenti"],
  }),
  line({
    id: "sienas_pieslegums.dibelnaglas_6x50_3gb_m",
    row: 129,
    block: "sienas_pieslegums",
    name: "Dībeļnaglas 6x50, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('sienas_pieslegums.uzlocits_skards_30cm').qty,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('dibelnaglas_ar_gremdgalvu_6x50mm'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.dibelnaglas_6x50_3gb_m', 'sienas_pieslegums.dibelnaglas_6x50_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dibelnaglas_ar_gremdgalvu_6x50mm"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sienas_pieslegums.urbis_betonam_7mm_1gb_20gb",
    row: 130,
    block: "sienas_pieslegums",
    name: "Urbis betonam 7mm, 1gb/ 20gb",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('sienas_pieslegums.dibelnaglas_6x50_3gb_m').qty/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('urbis_betonam_7mm'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.urbis_betonam_7mm_1gb_20gb', 'sienas_pieslegums.urbis_betonam_7mm_1gb_20gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_7mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "sienas_pieslegums.hermetikis_pu_1gb_10m",
    row: 131,
    block: "sienas_pieslegums",
    name: "Hermētiķis PU, 1gb/10m",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('sienas_pieslegums.uzlocits_skards_30cm').qty/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('hermetikis_sika'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.hermetikis_pu_1gb_10m', 'sienas_pieslegums.hermetikis_pu_1gb_10m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "hermetikis_sika"},
    blank: ["hours"],
    tools: ["Hermētiķa pistole"],
  }),
  line({
    id: "sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm",
    row: 132,
    block: "sienas_pieslegums",
    name: "Skārda noseglīste (2+2+10+2=16cm)",
    unit: "m",
    laborUnit: "m",
    note: "Garums, m",
    qty: (c) => c.line('sienas_pieslegums.uzlocits_skards_30cm').qty,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('skarda_nosegliste_2_2_10_2_16cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm_dibelosa'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm', 'sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "skarda_nosegliste_2_2_10_2_16cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "sienas_pieslegums.blivejosas_jumta_skruves_ar_dibeliem_4_8",
    row: 133,
    block: "sienas_pieslegums",
    name: "Blīvējošas jumta skrūves ar dībeļiem 4.8x50, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('jumta_skruves_4_8x50'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.blivejosas_jumta_skruves_ar_dibeliem_4_8', 'sienas_pieslegums.blivejosas_jumta_skruves_ar_dibeliem_4_8', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x50"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sienas_pieslegums.hermetikis_pu",
    row: 134,
    block: "sienas_pieslegums",
    name: "Hermētiķis PU",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('sienas_pieslegums.skarda_nosegliste_2_2_10_2_16cm').qty/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('hermetikis_sika'),
    blockTotal: (c) => total(c.span('sienas_pieslegums.hermetikis_pu', 'sienas_pieslegums.hermetikis_pu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "hermetikis_sika"},
    blank: ["hours"],
    tools: ["Hermētiķa pistole"],
  }),

  // ---- Ventilējams sienas pieslēgums bāņu galā, m ----
  line({
    id: "ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa",
    row: 135,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Vetikāli piedībeļotas brusas 50x50, Ik pa 60cm 20cm garas",
    unit: "m3",
    laborUnit: "m",
    param: 0.2,
    qty: (c) => c.inp.wall_abutment_ventilated_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*ceilUp(c.inp.wall_abutment_ventilated_m/0.6, 0)*c.this.param, 0)*0.05*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.vetikali_piedibelotas_brusas_50x50_ik_pa'),
    hours: (c) => c.this.hoursPerUnit*c.inp.wall_abutment_ventilated_m,
    blockMaterials: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa', 'ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m', 'materials')),
    blockLabor: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa', 'ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m', 'labor')),
    blockHours: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa', 'ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m', 'hours')),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa', 'ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Zobenzāģis", "līmeņrādis", "Striķis un krīts"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.dibelnaglas_8x100_2gb_x_posms",
    row: 136,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Dībeļnaglas 8x100, 2gb x posms",
    unit: "gb",
    param: 2,
    qty: (c) => ceilUp(c.line('ventilejams_sienas_pieslegums_ba.vetikali_piedibelotas_brusas_50x50_ik_pa').qty/0.2*c.this.param, 0),
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('dibelnaglas_ar_gremdgalvu_8x100mm'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.dibelnaglas_8x100_2gb_x_posms', 'ventilejams_sienas_pieslegums_ba.dibelnaglas_8x100_2gb_x_posms', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dibelnaglas_ar_gremdgalvu_8x100mm"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi", "āmurs"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_9mm_1gb_30_dibeli",
    row: 137,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Urbis ķieģeļiem 9mm, 1gb/ 30 dībeļi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('ventilejams_sienas_pieslegums_ba.dibelnaglas_8x100_2gb_x_posms').qty/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('urbis_betonam_9mm'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_9mm_1gb_30_dibeli', 'ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_9mm_1gb_30_dibeli', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_9mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.deli_25x100_2x_piesleguma_garums",
    row: 138,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Dēļi 25x100, 2x pieslēguma garums",
    unit: "m3",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.wall_abutment_ventilated_m*c.this.param,
    reserve: 1.3,
    qtyRes: (c) => c.this.reserve*c.this.qty*0.025*0.1,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.deli_25x100_2x_piesleguma_garums_zagesan'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.deli_25x100_2x_piesleguma_garums', 'ventilejams_sienas_pieslegums_ba.deli_25x100_2x_piesleguma_garums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Zobenzāģis", "līmeņrādis", "Striķis un krīts"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.kokskruves_5x70_3gb_m",
    row: 139,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Kokskrūves 5x70, 3gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('ventilejams_sienas_pieslegums_ba.deli_25x100_2x_piesleguma_garums').qty*c.this.param,
    reserve: 1.15,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('kokskruve_t_5x70'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.kokskruves_5x70_3gb_m', 'ventilejams_sienas_pieslegums_ba.kokskruves_5x70_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x70"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.kaiteklu_siets_50mm",
    row: 140,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Kaitēkļu siets 50mm",
    unit: "m",
    laborUnit: "m",
    note: "Pieslēguma garumā",
    qty: (c) => c.inp.wall_abutment_ventilated_m,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('kaiteklu_siets_5_2_7cm', 'perforated_07'),
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.kaiteklu_siets_50mm_skruvesana_griesana'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.kaiteklu_siets_50mm', 'ventilejams_sienas_pieslegums_ba.kaiteklu_siets_50mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "kaiteklu_siets_5_2_7cm", "variant": "perforated_07"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m",
    row: 141,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Klemmeru skrūves 4.5x25, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejams_sienas_pieslegums_ba.kaiteklu_siets_50mm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m', 'ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.uzlociti_banu_gali_20cm",
    row: 142,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Uzlocīti bāņu gali ~20cm",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.wall_abutment_ventilated_m,
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.uzlociti_banu_gali_20cm_locisana_griesan'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.uzlociti_banu_gali_20cm', 'ventilejams_sienas_pieslegums_ba.uzlociti_banu_gali_20cm', 'blockMaterials', 'blockLabor')),
    tools: ["Lielās pacelšanas stangas"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.apakseja_aizkabe_0_6mm_10_15_25cm",
    row: 143,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Apakšējā aizkabe 0.6mm (10+15=25cm)",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.wall_abutment_ventilated_m,
    reserve: 1.2,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.profile('apakseja_aizkabe_0_6mm_10_15_25cm', 'rukki_06'),
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.apakseja_aizkabe_0_6mm_10_15_25cm_skruve'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.apakseja_aizkabe_0_6mm_10_15_25cm', 'ventilejams_sienas_pieslegums_ba.apakseja_aizkabe_0_6mm_10_15_25cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "apakseja_aizkabe_0_6mm_10_15_25cm", "variant": "rukki_06"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m_2",
    row: 144,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Klemmeru skrūves 4.5x25, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('ventilejams_sienas_pieslegums_ba.apakseja_aizkabe_0_6mm_10_15_25cm').qty,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m_2', 'ventilejams_sienas_pieslegums_ba.klemmeru_skruves_4_5x25_3gb_m_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.nosedzosa_detala_2_15_10_5_32cm",
    row: 145,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Nosedzošā detaļa 2+15+10+5=32cm",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.wall_abutment_ventilated_m,
    reserve: 1.2,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.profile('nosedzosa_detala_2_15_10_5_32cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('ventilejams_sienas.nosedzosa_detala_2_15_10_5_32cm_dibelosa'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.nosedzosa_detala_2_15_10_5_32cm', 'ventilejams_sienas_pieslegums_ba.nosedzosa_detala_2_15_10_5_32cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "nosedzosa_detala_2_15_10_5_32cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.blivejosas_jumta_skruves_ar_dibeliem_4_8",
    row: 146,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Blīvējošas jumta skrūves ar dībeļiem 4.8x50, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejams_sienas_pieslegums_ba.nosedzosa_detala_2_15_10_5_32cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('jumta_skruves_4_8x50'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.blivejosas_jumta_skruves_ar_dibeliem_4_8', 'ventilejams_sienas_pieslegums_ba.blivejosas_jumta_skruves_ar_dibeliem_4_8', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x50"},
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_6mm_1gb_30_dibeli",
    row: 147,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Urbis ķieģeļiem 6mm, 1gb/30 dībeļi",
    unit: "gb",
    param: 30,
    qty: (c) => c.line('ventilejams_sienas_pieslegums_ba.blivejosas_jumta_skruves_ar_dibeliem_4_8').qty/c.this.param,
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('urbis_betonam_7mm'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_6mm_1gb_30_dibeli', 'ventilejams_sienas_pieslegums_ba.urbis_kiegeliem_6mm_1gb_30_dibeli', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_7mm"},
    tools: ["Urbjmašīna"],
  }),
  line({
    id: "ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m",
    row: 148,
    block: "ventilejams_sienas_pieslegums_ba",
    name: "Hermētiķis PU, 1gb/10m",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('ventilejams_sienas_pieslegums_ba.nosedzosa_detala_2_15_10_5_32cm').qty/c.this.param,
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('hermetikis_sika'),
    blockTotal: (c) => total(c.span('ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m', 'ventilejams_sienas_pieslegums_ba.hermetikis_pu_1gb_10m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "hermetikis_sika"},
    tools: ["Hermētiķa pistole"],
  }),

  // ---- Skursteņa pieslēgums, m ----
  line({
    id: "skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet",
    row: 149,
    block: "skurstena_pieslegums",
    name: "Lokšņu materiāls 125cm, skursteņa perimetrs +1m",
    unit: "m",
    laborUnit: "gb",
    param: 1,
    qty: (c) => c.inp.chimney_flashing_perimeter_m+(c.inp.chimney_flashing_count*c.this.param),
    reserve: 1.05,
    unitPrice: (c) => c.price('rulla_materials_cena_m_rukki'),
    hoursPerUnit: (c) => c.norm('skurstena_pieslegu.loksnu_materials_125cm_skurstena_perimet'),
    hours: (c) => c.this.hoursPerUnit*c.inp.chimney_flashing_count,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.chimney_flashing_count,
    blockMaterials: (c) => total(c.span('skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet', 'skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'materials')),
    blockLabor: (c) => total(c.span('skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet', 'skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'labor')),
    blockHours: (c) => total(c.span('skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet', 'skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'hours')),
    blockTotal: (c) => total(c.span('skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet', 'skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "rulla_materials_cena_m_rukki"},
    tools: ["Skārdnieka instrumenti, benderis, Lielās pacelšanas stangas"],
  }),
  line({
    id: "skurstena_pieslegums.klemmeri_7gb_m",
    row: 150,
    block: "skurstena_pieslegums",
    name: "Klemmeri, 7gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('skurstena_pieslegums.loksnu_materials_125cm_skurstena_perimet').qty,
    reserve: 1,
    unitPrice: (c) => c.price('klemmeri'),
    blockTotal: (c) => total(c.span('skurstena_pieslegums.klemmeri_7gb_m', 'skurstena_pieslegums.klemmeri_7gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri"},
    blank: ["hours"],
  }),
  line({
    id: "skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri",
    row: 151,
    block: "skurstena_pieslegums",
    name: "Klemmeru skrūves 4.5x25, 3gb x klemmeri",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('skurstena_pieslegums.klemmeri_7gb_m').qty,
    reserve: 1,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'skurstena_pieslegums.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
  }),

  // ---- Ventilācijas izvada montāža, gb ----
  line({
    id: "ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150",
    row: 152,
    block: "ventilacijas_izvada_montaza",
    name: "Skārda, ievalcēts Skārda caurule D100-150, 1m uz gb",
    unit: "gb",
    laborUnit: "gb",
    param: 1,
    qty: (c) => c.inp.vent_outlet_metal_count,
    reserve: 1,
    unitPrice: (c) => c.profile('skarda_caurule_d100', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('ventilacijas_izvad.skarda_caurule_d100_150_1m_uz_gb_valcesa'),
    blockMaterials: (c) => total(c.span('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150', 'ventilacijas_izvada_montaza.membranas_limlenta_1m_gb', 'materials')),
    blockLabor: (c) => total(c.span('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150', 'ventilacijas_izvada_montaza.membranas_limlenta_1m_gb', 'labor')),
    blockHours: (c) => total(c.span('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150', 'ventilacijas_izvada_montaza.membranas_limlenta_1m_gb', 'hours')),
    blockTotal: (c) => total(c.span('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150', 'ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "skarda_caurule_d100", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilacijas_izvada_montaza.cauruma_zagesana",
    row: 153,
    block: "ventilacijas_izvada_montaza",
    name: "Cauruma zāģēšana",
    unit: "gb",
    laborUnit: "gb",
    note: "Latojumā, membrānā, skārdā",
    qty: (c) => c.line('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150').qty,
    reserve: 1,
    hoursPerUnit: (c) => c.norm('ventilacijas_izvad.cauruma_zagesana_zagesana_griesana'),
    blockTotal: (c) => total(c.span('ventilacijas_izvada_montaza.cauruma_zagesana', 'ventilacijas_izvada_montaza.cauruma_zagesana', 'blockMaterials', 'blockLabor')),
    tools: ["Zobenzāģis", "fleksis", "Nazis un asmeņi"],
  }),
  line({
    id: "ventilacijas_izvada_montaza.skarda_cepurite",
    row: 154,
    block: "ventilacijas_izvada_montaza",
    name: "Skārda cepurīte",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.line('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150').qty,
    reserve: 1,
    unitPrice: (c) => c.profile('skarda_cepurite', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('ventilacijas_izvad.skarda_cepurite_kniedesana'),
    blockTotal: (c) => total(c.span('ventilacijas_izvada_montaza.skarda_cepurite', 'ventilacijas_izvada_montaza.skarda_cepurite', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "skarda_cepurite", "variant": "rukki_05"},
    tools: ["Kniedējamais"],
  }),
  line({
    id: "ventilacijas_izvada_montaza.kniedes_10gb_gb",
    row: 155,
    block: "ventilacijas_izvada_montaza",
    name: "Kniedes 10gb/gb",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('kniedes_3_2mm'),
    blockTotal: (c) => total(c.span('ventilacijas_izvada_montaza.kniedes_10gb_gb', 'ventilacijas_izvada_montaza.kniedes_10gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kniedes_3_2mm"},
    blank: ["hours"],
    tools: ["Kniedējamais"],
  }),
  line({
    id: "ventilacijas_izvada_montaza.membranas_limlenta_1m_gb",
    row: 156,
    block: "ventilacijas_izvada_montaza",
    name: "Membrānas līmlenta 1m/gb",
    unit: "m",
    param: 1,
    qty: (c) => c.line('ventilacijas_izvada_montaza.skarda_ievalcets_skarda_caurule_d100_150').qty*c.this.param,
    reserve: 1,
    unitPrice: 1,
    blockTotal: (c) => total(c.span('ventilacijas_izvada_montaza.membranas_limlenta_1m_gb', 'ventilacijas_izvada_montaza.membranas_limlenta_1m_gb', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
    tools: ["Nazis un asmeņi"],
  }),

  // ---- Plastmasas, skrūvējama ventilācijas izvada montāža, gb ----
  line({
    id: "plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts",
    row: 157,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Ventilācijas izvada komplekts",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.vent_outlet_plastic_count,
    reserve: 1,
    unitPrice: (c) => c.price('platsmasas_ventilacijas_izvada_komplekts'),
    hoursPerUnit: (c) => c.norm('ventilacijas_izvad.ventilacijas_izvada_komplekts_skruvesana'),
    blockMaterials: (c) => total(c.span('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts', 'plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb', 'materials')),
    blockLabor: (c) => total(c.span('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts', 'plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb', 'labor')),
    blockHours: (c) => total(c.span('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts', 'plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb', 'hours')),
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts', 'plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "platsmasas_ventilacijas_izvada_komplekts"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "plastmasas_skruvejama_ventilacij.cauruma_zagesana",
    row: 158,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Cauruma zāģēšana",
    unit: "gb",
    laborUnit: "gb",
    note: "Latojumā, membrānā, skārdā",
    qty: (c) => c.line('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts').qty,
    reserve: 1,
    hoursPerUnit: (c) => c.norm('ventilacijas_izvad.cauruma_zagesana_zagesana_griesana_2'),
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.cauruma_zagesana', 'plastmasas_skruvejama_ventilacij.cauruma_zagesana', 'blockMaterials', 'blockLabor')),
    tools: ["Zobenzāģis", "fleksis", "Nazis un asmeņi", "Skārdnieka instrumenti"],
  }),
  line({
    id: "plastmasas_skruvejama_ventilacij.jumta_skruves_4_8x35_20gb_gb",
    row: 159,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Jumta skrūves 4.8x35, 20gb/gb",
    unit: "gb",
    param: 20,
    qty: (c) => c.line('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('jumta_skruves_4_8x35'),
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.jumta_skruves_4_8x35_20gb_gb', 'plastmasas_skruvejama_ventilacij.jumta_skruves_4_8x35_20gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x35"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi", "Muciņa 8mm"],
  }),
  line({
    id: "plastmasas_skruvejama_ventilacij.kniedes_3gb_gb",
    row: 160,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Kniedes 3gb/gb",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kniedes_3_2mm'),
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.kniedes_3gb_gb', 'plastmasas_skruvejama_ventilacij.kniedes_3gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kniedes_3_2mm"},
    blank: ["hours"],
    tools: ["Kniedējamais"],
  }),
  line({
    id: "plastmasas_skruvejama_ventilacij.membranas_limlenta_1m_gb",
    row: 161,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Membrānas līmlenta 1m/gb",
    unit: "m",
    param: 1,
    qty: (c) => c.line('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts').qty*c.this.param,
    reserve: 1,
    unitPrice: 1,
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.membranas_limlenta_1m_gb', 'plastmasas_skruvejama_ventilacij.membranas_limlenta_1m_gb', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb",
    row: 162,
    block: "plastmasas_skruvejama_ventilacij",
    name: "Hermētiķis PU, 1gb/10gb",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('plastmasas_skruvejama_ventilacij.ventilacijas_izvada_komplekts').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('hermetikis_sika'),
    blockTotal: (c) => total(c.span('plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb', 'plastmasas_skruvejama_ventilacij.hermetikis_pu_1gb_10gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "hermetikis_sika"},
    blank: ["hours"],
    tools: ["Hermētiķa pistole"],
  }),

  // ---- Jumta lūkas montāža Ievalcējot pa vidu loksnei, gb ----
  line({
    id: "jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala",
    row: 163,
    block: "jumta_lukas_montaza_ievalcejot_p",
    name: "Jumta lūka bez pamatnes, ovāla",
    unit: "gb",
    laborUnit: "gb",
    note: "45x60",
    qty: (c) => c.inp.roof_hatch_oval_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_luka_bez_pamatnes_zn'),
    hoursPerUnit: (c) => c.norm('jumta_lukas_montaz.jumta_luka_bez_pamatnes_ovala_valcesana'),
    blockMaterials: (c) => total(c.span('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala', 'jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb', 'materials')),
    blockLabor: (c) => total(c.span('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala', 'jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb', 'labor')),
    blockHours: (c) => total(c.span('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala', 'jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb', 'hours')),
    blockTotal: (c) => total(c.span('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala', 'jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_luka_bez_pamatnes_zn"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb",
    row: 164,
    block: "jumta_lukas_montaza_ievalcejot_p",
    name: "Membrānas līmlenta, 10m/gb",
    unit: "m",
    laborUnit: "gb",
    param: 10,
    qty: (c) => c.line('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala').qty*c.this.param,
    reserve: 1.1,
    unitPrice: 1,
    hoursPerUnit: (c) => c.norm('jumta_lukas_montaz.membranas_limlenta_10m_gb_membranas_lime'),
    hours: (c) => c.this.hoursPerUnit*c.line('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala').qty,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.line('jumta_lukas_montaza_ievalcejot_p.jumta_luka_bez_pamatnes_ovala').qty,
    blockTotal: (c) => total(c.span('jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb', 'jumta_lukas_montaza_ievalcejot_p.membranas_limlenta_10m_gb', 'blockMaterials', 'blockLabor')),
    tools: ["Nazis un asmeņi"],
  }),

  // ---- Ievalcējot starp divām loksnēm, gb ----
  line({
    id: "ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k",
    row: 165,
    block: "ievalcejot_starp_divam_loksnem",
    name: "Jumta lūka ar pamatni (62.5x (30+60+līdz korei), ovāla",
    unit: "gb",
    laborUnit: "gb",
    note: "45x60 ar pamanti",
    unitPrice: (c) => c.price('jumta_luka_ar_pamatni_625x130_zn'),
    hoursPerUnit: (c) => c.norm('jumta_lukas_montaz.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k'),
    blockMaterials: (c) => total(c.span('ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k', 'ievalcejot_starp_divam_loksnem.membranas_limlenta', 'materials')),
    blockLabor: (c) => total(c.span('ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k', 'ievalcejot_starp_divam_loksnem.membranas_limlenta', 'labor')),
    blockHours: (c) => total(c.span('ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k', 'ievalcejot_starp_divam_loksnem.membranas_limlenta', 'hours')),
    blockTotal: (c) => total(c.span('ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k', 'ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_luka_ar_pamatni_625x130_zn"},
    tools: ["Skārdnieka instrumenti", "Aizvalcētājs"],
  }),
  line({
    id: "ievalcejot_starp_divam_loksnem.membranas_limlenta",
    row: 166,
    block: "ievalcejot_starp_divam_loksnem",
    name: "Membrānas līmlenta",
    unit: "m",
    laborUnit: "gb",
    note: "10m/gb",
    unitPrice: 1,
    hoursPerUnit: (c) => c.norm('jumta_lukas_montaz.membranas_limlenta_membranas_limesana'),
    hours: (c) => c.this.hoursPerUnit*c.line('ievalcejot_starp_divam_loksnem.jumta_luka_ar_pamatni_62_5x_30_60_lidz_k').qty,
    blockTotal: (c) => total(c.span('ievalcejot_starp_divam_loksnem.membranas_limlenta', 'ievalcejot_starp_divam_loksnem.membranas_limlenta', 'blockMaterials', 'blockLabor')),
    tools: ["Nazis un asmeņi"],
  }),

  // ---- Parapeta montāža, m ----
  line({
    id: "parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p",
    row: 167,
    block: "parapeta_montaza",
    name: "PVC hidroizolācija, uz 3 šķautnēm. Ruļļa platums 25cm",
    unit: "m",
    laborUnit: "m",
    param: 0.25,
    qty: (c) => total([c.inp.parapet_1_m, c.inp.parapet_2_m, c.inp.parapet_3_m]),
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*c.this.reserve*3,
    unitPrice: (c) => c.price('pvc_hidroizolacija_25cm'),
    hoursPerUnit: (c) => c.norm('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p'),
    blockMaterials: (c) => total(c.span('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p', 'parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m', 'materials')),
    blockLabor: (c) => total(c.span('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p', 'parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m', 'labor')),
    blockHours: (c) => total(c.span('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p', 'parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m', 'hours')),
    blockTotal: (c) => total(c.span('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p', 'parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_hidroizolacija_25cm"},
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "parapeta_montaza.mitrumizturigs_saplaksnis_12mm",
    row: 168,
    block: "parapeta_montaza",
    name: "Mitrumizturīgs saplāksnis 12mm",
    unit: "m2",
    laborUnit: "m2",
    note: "Parapeta platums+ uz sienas abās pusēs",
    qty: (c) => c.line('parapeta_montaza.pvc_hidroizolacija_uz_3_skautnem_rulla_p').param*3*total([c.inp.parapet_1_m, c.inp.parapet_2_m, c.inp.parapet_3_m]),
    reserve: 1.2,
    unitPrice: (c) => c.price('saplaksnis_mitrumizturigs_12mm'),
    hoursPerUnit: (c) => c.norm('parapeta_montaza.mitrumizturigs_saplaksnis_12mm_zagesana'),
    blockTotal: (c) => total(c.span('parapeta_montaza.mitrumizturigs_saplaksnis_12mm', 'parapeta_montaza.mitrumizturigs_saplaksnis_12mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "saplaksnis_mitrumizturigs_12mm"},
    tools: ["Cirkulārias zāģis"],
  }),
  line({
    id: "parapeta_montaza.dibelnaglas_6x80_7gb_m_parapeta",
    row: 169,
    block: "parapeta_montaza",
    name: "Dībeļnaglas 6x80, 7gb/m (parapeta)",
    unit: "gb",
    param: 7,
    qty: (c) => c.this.param*total([c.inp.parapet_1_m, c.inp.parapet_2_m, c.inp.parapet_3_m]),
    reserve: 1.1,
    unitPrice: (c) => c.price('dibelnaglas_ar_gremdgalvu_6x80mm'),
    blockTotal: (c) => total(c.span('parapeta_montaza.dibelnaglas_6x80_7gb_m_parapeta', 'parapeta_montaza.dibelnaglas_6x80_7gb_m_parapeta', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dibelnaglas_ar_gremdgalvu_6x80mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna", "Skrūvmašīna un uzgaļi", "Āmurs", "Stangas"],
  }),
  line({
    id: "parapeta_montaza.urbis_betona_7mm_1gb_30gb",
    row: 170,
    block: "parapeta_montaza",
    name: "Urbis betona 7mm 1gb/30gb",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('parapeta_montaza.dibelnaglas_6x80_7gb_m_parapeta').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('urbis_betonam_7mm'),
    blockTotal: (c) => total(c.span('parapeta_montaza.urbis_betona_7mm_1gb_30gb', 'parapeta_montaza.urbis_betona_7mm_1gb_30gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_7mm"},
    blank: ["hours"],
  }),
  line({
    id: "parapeta_montaza.skarda_parapets_izmeri_atkarigi_daba",
    row: 171,
    block: "parapeta_montaza",
    name: "Skārda parapets (izmēri atkarīgi dabā)",
    unit: "m",
    laborUnit: "m",
    qty: (c) => total([c.inp.parapet_1_m, c.inp.parapet_2_m, c.inp.parapet_3_m]),
    reserve: 1.1,
    unitPrice: (c) => c.profile('skarda_parapets_izmeri_atkarigi_daba', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('parapeta_montaza.skarda_parapets_izmeri_atkarigi_daba_mon'),
    blockTotal: (c) => total(c.span('parapeta_montaza.skarda_parapets_izmeri_atkarigi_daba', 'parapeta_montaza.skarda_parapets_izmeri_atkarigi_daba', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "skarda_parapets_izmeri_atkarigi_daba", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "parapeta_montaza.aizkabes_15cm_platuma_2x_parapeta_garums",
    row: 172,
    block: "parapeta_montaza",
    name: "Aizkabes 15cm platumā, 2x parapeta garums",
    unit: "m",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.line('parapeta_montaza.skarda_parapets_izmeri_atkarigi_daba').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.profile('aizkabes_15cm_platuma_2x_parapeta_ga', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('parapeta_montaza.aizkabes_15cm_platuma_2x_parapeta_garums'),
    blockTotal: (c) => total(c.span('parapeta_montaza.aizkabes_15cm_platuma_2x_parapeta_garums', 'parapeta_montaza.aizkabes_15cm_platuma_2x_parapeta_garums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "aizkabes_15cm_platuma_2x_parapeta_ga", "variant": "rukki_05"},
  }),
  line({
    id: "parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m",
    row: 173,
    block: "parapeta_montaza",
    name: "Klemmeru skrūves 4.5x25, 5gb/m",
    unit: "gb",
    param: 5,
    qty: (c) => c.this.param*c.line('parapeta_montaza.aizkabes_15cm_platuma_2x_parapeta_garums').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m', 'parapeta_montaza.klemmeru_skruves_4_5x25_5gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
];
