/**
 * Gutters, valley, roof windows.
 *
 * Generated from the estimator workbook (Tāme rows 89-117) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Teknes, m ----
  line({
    id: "teknes.teknes_apalas_125_zn",
    row: 89,
    block: "teknes",
    name: "Teknes apaļās 125 ZN",
    unit: "m",
    laborUnit: "m",
    param: (c) => c.inp.gutter_diameter_mm,
    qty: (c) => ceilUp(c.inp.gutter_m/3, 0)*3,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('teknes_apalas_125_zn'),
    hoursPerUnit: (c) => c.norm('teknes.teknes_apalas_125_zn_teknu_montaza'),
    blockMaterials: (c) => total(c.span('teknes.teknes_apalas_125_zn', 'teknes.kniedes_5gb_m_teknes_stavvadi', 'materials')),
    blockLabor: (c) => total(c.span('teknes.teknes_apalas_125_zn', 'teknes.kniedes_5gb_m_teknes_stavvadi', 'labor')),
    blockHours: (c) => total(c.span('teknes.teknes_apalas_125_zn', 'teknes.kniedes_5gb_m_teknes_stavvadi', 'hours')),
    blockTotal: (c) => total(c.span('teknes.teknes_apalas_125_zn', 'teknes.teknes_apalas_125_zn', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "teknes_apalas_125_zn"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts", "Līmeņrādis"],
  }),
  line({
    id: "teknes.aki_garie_solis_60",
    row: 90,
    block: "teknes",
    name: "Āķi, garie solis 60",
    unit: "gb",
    laborUnit: "gb",
    param: 0.6,
    qty: (c) => c.line('teknes.teknes_apalas_125_zn').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('aki_garie_125_zn'),
    hoursPerUnit: (c) => c.norm('teknes.aki_garie_solis_60_ar_frezesanu_un_locis'),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.qtyRes*c.this.rate,
    blockTotal: (c) => total(c.span('teknes.aki_garie_solis_60', 'teknes.aki_garie_solis_60', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "aki_garie_125_zn"},
    tools: ["Frēze", "Striķis un krīts", "Āķu locāmais", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "teknes.skruves_5x50_4gb_akis",
    row: 91,
    block: "teknes",
    name: "Skrūves 5x50 4gb/āķis",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('teknes.aki_garie_solis_60').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x50'),
    blockTotal: (c) => total(c.span('teknes.skruves_5x50_4gb_akis', 'teknes.skruves_5x50_4gb_akis', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x50"},
  }),
  line({
    id: "teknes.frezes_uzgali_1gb_30_aki",
    row: 92,
    block: "teknes",
    name: "Frēzes uzgaļi, 1gb/30 āķi",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('teknes.aki_garie_solis_60').qty/30, 0),
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('frezes_uzgali_1gb_30_aki'),
    blockTotal: (c) => total(c.span('teknes.frezes_uzgali_1gb_30_aki', 'teknes.frezes_uzgali_1gb_30_aki', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "frezes_uzgali_1gb_30_aki"},
  }),
  line({
    id: "teknes.teknes_arejie_sturi",
    row: 93,
    block: "teknes",
    name: "Teknes ārējie stūri",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.gutter_outer_corners_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('teknes_arejie_sturi_zn_125'),
    hoursPerUnit: (c) => c.norm('teknes.teknes_arejie_sturi_montaza'),
    blockTotal: (c) => total(c.span('teknes.teknes_arejie_sturi', 'teknes.teknes_arejie_sturi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "teknes_arejie_sturi_zn_125"},
    tools: ["Kniedētājs", "Skārdnieka instrumenti"],
  }),
  line({
    id: "teknes.teknes_ieksejie_sturi",
    row: 94,
    block: "teknes",
    name: "Teknes iekšējie stūri",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.gutter_inner_corners_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('teknes_ieksejie_sturi_zn_125'),
    hoursPerUnit: (c) => c.norm('teknes.teknes_ieksejie_sturi_montaza'),
    blockTotal: (c) => total(c.span('teknes.teknes_ieksejie_sturi', 'teknes.teknes_ieksejie_sturi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "teknes_ieksejie_sturi_zn_125"},
    tools: ["Kniedētājs", "Skārdnieka instrumenti"],
  }),
  line({
    id: "teknes.teknes_gali_125_zn",
    row: 95,
    block: "teknes",
    name: "Teknes gali 125 Zn",
    unit: "gb",
    laborUnit: "gb",
    note: "ar gumijas blīvi",
    qty: (c) => c.inp.gutter_end_caps_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('teknes_gali_zn_125'),
    hoursPerUnit: (c) => c.norm('teknes.teknes_gali_125_zn_ar_gumijas_blivi'),
    blockTotal: (c) => total(c.span('teknes.teknes_gali_125_zn', 'teknes.teknes_gali_125_zn', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "teknes_gali_zn_125"},
    tools: ["Kniedētājs", "Skārdnieka instrumenti"],
  }),
  line({
    id: "teknes.teknes_piltuves",
    row: 96,
    block: "teknes",
    name: "Teknes piltuves",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.gutter_outlets_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('teknes_piltuves_125_100'),
    hoursPerUnit: (c) => c.norm('teknes.teknes_piltuves_montaza'),
    blockTotal: (c) => total(c.span('teknes.teknes_piltuves', 'teknes.teknes_piltuves', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "teknes_piltuves_125_100"},
    tools: ["Kniedētājs", "Skārdnieka instrumenti"],
  }),
  line({
    id: "teknes.hermetikis_teknem_1gb_10_posmi",
    row: 97,
    block: "teknes",
    name: "Hermētiķis teknēm, 1gb/10 posmi",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('teknes.teknes_apalas_125_zn').qty/3/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('hermetikis_sika'),
    blockTotal: (c) => total(c.span('teknes.hermetikis_teknem_1gb_10_posmi', 'teknes.hermetikis_teknem_1gb_10_posmi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "hermetikis_sika"},
    tools: ["Hermētiķa pistole", "Skārdnieka instrumenti"],
  }),
  line({
    id: "teknes.noteces_d100",
    row: 98,
    block: "teknes",
    name: "Noteces D100",
    unit: "m",
    laborUnit: "m",
    param: (c) => c.inp.downpipe_diameter_mm,
    qty: (c) => ceilUp(c.inp.downpipe_m/3, 0)*3,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('noteces_caurule_d100_zn'),
    hoursPerUnit: (c) => c.norm('teknes.noteces_d100_dibelojot_stiprinajumus'),
    blockTotal: (c) => total(c.span('teknes.noteces_d100', 'teknes.noteces_d100', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "noteces_caurule_d100_zn"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts", "Līmeņrādis", "Kniedētājs"],
  }),
  line({
    id: "teknes.sienas_stiprinajumu_komplekts_1gb_1m",
    row: 99,
    block: "teknes",
    name: "Sienas stiprinājumu komplekts, 1gb/1m",
    unit: "gb",
    param: 1,
    qty: (c) => c.line('teknes.noteces_d100').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('sienas_stiprinajumu_komplekts_zn_100mm'),
    blockTotal: (c) => total(c.span('teknes.sienas_stiprinajumu_komplekts_1gb_1m', 'teknes.sienas_stiprinajumu_komplekts_1gb_1m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sienas_stiprinajumu_komplekts_zn_100mm"},
    blank: ["hours"],
    tools: ["Urbjmašīna", "Urbis betonam", "Skrūvmašīna un uzgaļi", "Seškantes atslēgas"],
  }),
  line({
    id: "teknes.tapskruves_200mm",
    row: 100,
    block: "teknes",
    name: "Tapskrūves 200mm",
    unit: "gb",
    note: "atkarībā no siltinājuma",
    qty: (c) => c.line('teknes.sienas_stiprinajumu_komplekts_1gb_1m').qty,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('tapskruves_200mm'),
    blockTotal: (c) => total(c.span('teknes.tapskruves_200mm', 'teknes.tapskruves_200mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "tapskruves_200mm"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "teknes.augsejo_likumu_komplekts",
    row: 101,
    block: "teknes",
    name: "Augšējo līkumu komplekts",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.downpipe_upper_bends_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('augsejo_likumu_komplekts_zn_100mm'),
    hoursPerUnit: (c) => c.norm('teknes.augsejo_likumu_komplekts_kniedesana_grie'),
    blockTotal: (c) => total(c.span('teknes.augsejo_likumu_komplekts', 'teknes.augsejo_likumu_komplekts', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "augsejo_likumu_komplekts_zn_100mm"},
    tools: ["Skārdnieka instrumenti", "Kniedētājs"],
  }),
  line({
    id: "teknes.apaksejais_likums",
    row: 102,
    block: "teknes",
    name: "Apakšējais līkums",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.downpipe_lower_bends_count,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('apaksejais_likums_zn_100mm'),
    hoursPerUnit: (c) => c.norm('teknes.apaksejais_likums_kniedesana'),
    blockTotal: (c) => total(c.span('teknes.apaksejais_likums', 'teknes.apaksejais_likums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "apaksejais_likums_zn_100mm"},
    tools: ["Skārdnieka instrumenti", "Kniedētājs"],
  }),
  line({
    id: "teknes.kniedes_5gb_m_teknes_stavvadi",
    row: 103,
    block: "teknes",
    name: "Kniedes 5gb/m teknes+stāvvadi",
    unit: "gb",
    param: 5,
    qty: (c) => c.this.param*c.line('teknes.teknes_apalas_125_zn').qty+c.line('teknes.noteces_d100').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('kniedes_3_2mm'),
    blockTotal: (c) => total(c.span('teknes.kniedes_5gb_m_teknes_stavvadi', 'teknes.kniedes_5gb_m_teknes_stavvadi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kniedes_3_2mm"},
    blank: ["hours"],
  }),

  // ---- Sateknes montāža, m ----
  line({
    id: "sateknes_montaza.sateknes_profils_2_30_30_2_64cm",
    row: 104,
    block: "sateknes_montaza",
    name: "Sateknes profils (2+30+30+2=64cm)",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.valley_m,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('sateknes_profils_2_30_30_2_64cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('sateknes_montaza.sateknes_profils_2_30_30_2_64cm_griesana'),
    blockMaterials: (c) => total(c.span('sateknes_montaza.sateknes_profils_2_30_30_2_64cm', 'sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m', 'materials')),
    blockLabor: (c) => total(c.span('sateknes_montaza.sateknes_profils_2_30_30_2_64cm', 'sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m', 'labor')),
    blockHours: (c) => total(c.span('sateknes_montaza.sateknes_profils_2_30_30_2_64cm', 'sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m', 'hours')),
    blockTotal: (c) => total(c.span('sateknes_montaza.sateknes_profils_2_30_30_2_64cm', 'sateknes_montaza.sateknes_profils_2_30_30_2_64cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "sateknes_profils_2_30_30_2_64cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "sateknes_montaza.aizkabes_paraleli_15cm_sateknes_garums_x",
    row: 105,
    block: "sateknes_montaza",
    name: "Aizkabes paralēli (15cm), Sateknes garums x 2",
    unit: "m",
    param: 2,
    qty: (c) => c.line('sateknes_montaza.sateknes_profils_2_30_30_2_64cm').qty*2,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('aizkabes_paraleli_15cm_sateknes_garu', 'rukki_05'),
    blockTotal: (c) => total(c.span('sateknes_montaza.aizkabes_paraleli_15cm_sateknes_garums_x', 'sateknes_montaza.aizkabes_paraleli_15cm_sateknes_garums_x', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "aizkabes_paraleli_15cm_sateknes_garu", "variant": "rukki_05"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sateknes_montaza.piebriestosa_poliuretana_lenta_sateknes",
    row: 106,
    block: "sateknes_montaza",
    name: "Piebriestoša poliuretāna lenta, Sateknes garums x 2 ",
    unit: "m",
    param: 2,
    qty: (c) => c.line('sateknes_montaza.sateknes_profils_2_30_30_2_64cm').qty*c.this.param,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('piebriestosa_poliuretana_lenta'),
    blockTotal: (c) => total(c.span('sateknes_montaza.piebriestosa_poliuretana_lenta_sateknes', 'sateknes_montaza.piebriestosa_poliuretana_lenta_sateknes', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "piebriestosa_poliuretana_lenta"},
    blank: ["hours"],
    tools: ["Nazis"],
  }),
  line({
    id: "sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m",
    row: 107,
    block: "sateknes_montaza",
    name: "Skrūves Klemmeru 4.5x2.5, 10gb/m",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('sateknes_montaza.sateknes_profils_2_30_30_2_64cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m', 'sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sateknes_montaza.aizkabes_perpendikulari_15cm_ik_pa_2m",
    row: 108,
    block: "sateknes_montaza",
    name: "Aizkabes perpendikulāri (15cm) ik pa 2m",
    unit: "m",
    param: 0.6,
    qty: (c) => ceilUp(c.line('sateknes_montaza.sateknes_profils_2_30_30_2_64cm').qty/2, 0)*c.this.param,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('aizkabes_paraleli_15cm_sateknes_garu', 'rukki_05'),
    blockTotal: (c) => total(c.span('sateknes_montaza.aizkabes_perpendikulari_15cm_ik_pa_2m', 'sateknes_montaza.aizkabes_perpendikulari_15cm_ik_pa_2m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "aizkabes_paraleli_15cm_sateknes_garu", "variant": "rukki_05"},
    blank: ["hours"],
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m_2",
    row: 109,
    block: "sateknes_montaza",
    name: "Skrūves Klemmeru 4.5x2.5, 10gb/m",
    unit: "gb",
    param: 10,
    qty: (c) => c.line('sateknes_montaza.aizkabes_perpendikulari_15cm_ik_pa_2m').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m_2', 'sateknes_montaza.skruves_klemmeru_4_5x2_5_10gb_m_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m",
    row: 110,
    block: "sateknes_montaza",
    name: "Piebriestoša poliuretāna lenta  ik pa 2m",
    unit: "m",
    param: 0.6,
    qty: (c) => c.line('sateknes_montaza.sateknes_profils_2_30_30_2_64cm').qty/2*c.this.param,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('piebriestosa_poliuretana_lenta'),
    blockTotal: (c) => total(c.span('sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m', 'sateknes_montaza.piebriestosa_poliuretana_lenta_ik_pa_2m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "piebriestosa_poliuretana_lenta"},
    blank: ["hours"],
    tools: ["Nazis"],
  }),

  // ---- Jumta logu montāža 1, gb ----
  line({
    id: "jumta_logu_montaza_1.jumta_logs_komplekts",
    row: 111,
    block: "jumta_logu_montaza_1",
    name: "Jumta logs, komplekts",
    unit: "gb",
    laborUnit: "gb",
    note: "veids, izmērs",
    qty: (c) => c.inp.roof_window_1_count,
    reserve: 1,
    unitPrice: (c) => c.inp.roof_window_1_kit_price,
    hoursPerUnit: (c) => c.norm('jumta_logu_montaza.jumta_logs_komplekts_veids_izmers'),
    blockMaterials: (c) => total(c.span('jumta_logu_montaza_1.jumta_logs_komplekts', 'jumta_logu_montaza_1.difuzijas_membranas_ramis', 'materials')),
    blockLabor: (c) => total(c.span('jumta_logu_montaza_1.jumta_logs_komplekts', 'jumta_logu_montaza_1.difuzijas_membranas_ramis', 'labor')),
    blockHours: (c) => total(c.span('jumta_logu_montaza_1.jumta_logs_komplekts', 'jumta_logu_montaza_1.difuzijas_membranas_ramis', 'hours')),
    blockTotal: (c) => total(c.span('jumta_logu_montaza_1.jumta_logs_komplekts', 'jumta_logu_montaza_1.jumta_logs_komplekts', 'blockMaterials', 'blockLabor')),
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_logu_montaza_1.difuzijas_membranas_ramis",
    row: 112,
    block: "jumta_logu_montaza_1",
    name: "Difūzijas membrānas rāmis",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.roof_window_1_count,
    reserve: 1,
    unitPrice: (c) => c.inp.roof_window_1_frame_price,
    hoursPerUnit: (c) => c.norm('jumta_logu_montaza.difuzijas_membranas_ramis'),
    hours: (c) => c.this.hoursPerUnit*c.line('jumta_logu_montaza_1.jumta_logs_komplekts').qty,
    blockTotal: (c) => total(c.span('jumta_logu_montaza_1.difuzijas_membranas_ramis', 'jumta_logu_montaza_1.difuzijas_membranas_ramis', 'blockMaterials', 'blockLabor')),
    tools: ["Nazis un asmeņi"],
  }),

  // ---- Jumta logu montāža 2, gb ----
  line({
    id: "jumta_logu_montaza_2.jumta_logs_komplekts",
    row: 113,
    block: "jumta_logu_montaza_2",
    name: "Jumta logs, komplekts",
    unit: "gb",
    laborUnit: "gb",
    note: "veids, izmērs",
    qty: (c) => c.inp.roof_window_2_count,
    reserve: 1,
    unitPrice: (c) => c.inp.roof_window_2_kit_price,
    hoursPerUnit: (c) => c.norm('jumta_logu_montaza.jumta_logs_komplekts_veids_izmers'),
    blockMaterials: (c) => total(c.span('jumta_logu_montaza_2.jumta_logs_komplekts', 'jumta_logu_montaza_2.difuzijas_membranas_ramis', 'materials')),
    blockLabor: (c) => total(c.span('jumta_logu_montaza_2.jumta_logs_komplekts', 'jumta_logu_montaza_2.difuzijas_membranas_ramis', 'labor')),
    blockHours: (c) => total(c.span('jumta_logu_montaza_2.jumta_logs_komplekts', 'jumta_logu_montaza_2.difuzijas_membranas_ramis', 'hours')),
    blockTotal: (c) => total(c.span('jumta_logu_montaza_2.jumta_logs_komplekts', 'jumta_logu_montaza_2.jumta_logs_komplekts', 'blockMaterials', 'blockLabor')),
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_logu_montaza_2.difuzijas_membranas_ramis",
    row: 114,
    block: "jumta_logu_montaza_2",
    name: "Difūzijas membrānas rāmis",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.roof_window_2_count,
    reserve: 1,
    unitPrice: (c) => c.inp.roof_window_2_frame_price,
    hoursPerUnit: 2,
    hours: (c) => c.this.hoursPerUnit*c.line('jumta_logu_montaza_2.jumta_logs_komplekts').qty,
    blockTotal: (c) => total(c.span('jumta_logu_montaza_2.difuzijas_membranas_ramis', 'jumta_logu_montaza_2.difuzijas_membranas_ramis', 'blockMaterials', 'blockLabor')),
    tools: ["Nazis un asmeņi"],
  }),

  // ---- Jumta logu pieslēgumu montāža, m ----
  line({
    id: "jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1",
    row: 115,
    block: "jumta_logu_pieslegumu_montaza",
    name: "Lokšņu materiāls 62.5cm, loga perimetrs +1m",
    unit: "m",
    laborUnit: "gb",
    param: 1,
    qty: (c) => (c.inp.roof_window_flashing_length_m+c.this.param*c.inp.roof_window_flashing_count)/2,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('rulla_materials_cena_m_rukki'),
    hoursPerUnit: (c) => c.norm('jumta_logu_piesleg.loksnu_materials_125cm_loga_perimetrs_5'),
    hours: (c) => c.this.hoursPerUnit*c.inp.roof_window_flashing_count,
    blockMaterials: (c) => total(c.span('jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1', 'jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'materials')),
    blockLabor: (c) => total(c.span('jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1', 'jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'labor')),
    blockHours: (c) => total(c.span('jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1', 'jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'hours')),
    blockTotal: (c) => total(c.span('jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1', 'jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "rulla_materials_cena_m_rukki"},
    tools: ["Skārdnieka instrumenti", "benderis"],
  }),
  line({
    id: "jumta_logu_pieslegumu_montaza.klemmeri_3gb_m",
    row: 116,
    block: "jumta_logu_pieslegumu_montaza",
    name: "Klemmeri, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('jumta_logu_pieslegumu_montaza.loksnu_materials_62_5cm_loga_perimetrs_1').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('klemmeri'),
    blockTotal: (c) => total(c.span('jumta_logu_pieslegumu_montaza.klemmeri_3gb_m', 'jumta_logu_pieslegumu_montaza.klemmeri_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri"},
  }),
  line({
    id: "jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri",
    row: 117,
    block: "jumta_logu_pieslegumu_montaza",
    name: "Klemmeru skrūves 4.5x25, 3gb x klemmeri",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('jumta_logu_pieslegumu_montaza.klemmeri_3gb_m').qty*c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'jumta_logu_pieslegumu_montaza.klemmeru_skruves_4_5x25_3gb_x_klemmeri', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
];
