/** Lead input fields (workbook sheet Ievade). Keys are the stable API and database names. */
import type { InputField } from '../line';

export const INPUT_FIELDS: InputField[] = [
  { key: "distance_km", section: "conditions", label: "Attālums līdz objektam, km", unit: "km", derived: false },
  { key: "crew_size", section: "conditions", label: "Cilvēku skaits objektā", unit: "people", derived: false },
  { key: "slope_labor_coef", section: "conditions", label: "Slīpuma koef", unit: "x", derived: false },
  { key: "travel_coef", section: "conditions", label: "Komandējuma piemaksas koef", unit: "x", derived: false },
  { key: "lodging_nights", section: "conditions", label: "Komandējuma izmitināšana, dienas", unit: "nights", derived: false },
  { key: "lodging_people", section: "conditions", label: "Komandējuma izmitināšana, cilvēku skaits", unit: "people", derived: false },
  { key: "site_manager_months", section: "conditions", label: "Būvdarbu vadītājs un dokumentācija, mēneši", unit: "months", derived: false },
  { key: "insurance_rate", section: "conditions", label: "Apdrošināšanas %", unit: "fraction", derived: false },
  { key: "demo_slate_m2", section: "demolition", label: "Šīfera demontāža 12kg/m2, m2", unit: "m2", derived: false },
  { key: "demo_standing_seam_m2", section: "demolition", label: "Valcprofila demontāža, m2", unit: "m2", derived: false },
  { key: "demo_sheet_metal_m2", section: "demolition", label: "Skārda loksņu demontāža, m2", unit: "m2", derived: false },
  { key: "demo_shingles_m2", section: "demolition", label: "Šindeļu demontāža, m2", unit: "m2", derived: false },
  { key: "demo_tiles_m2", section: "demolition", label: "Dakstiņu demontāža 50kg/m2, m2", unit: "m2", derived: false },
  { key: "demo_battens_m2", section: "demolition", label: "Latojuma demontāža, m2", unit: "m2", derived: false },
  { key: "demo_structure_m2", section: "demolition", label: "Jumta konstrukcijas demontāža, m2", unit: "m2", derived: false },
  { key: "demo_gutters_m", section: "demolition", label: "Noteksistēmas demontāža, m", unit: "m", derived: false },
  { key: "site_toilet_months", section: "site_setup", label: "Bio tualete, mēn", unit: "months", derived: false },
  { key: "site_skip_8m3_count", section: "site_setup", label: "Būvgružu konteiners 8m3, gb", unit: "pcs", derived: false },
  { key: "site_fence_length_m", section: "site_setup", label: "Nožogojuma garums, m", unit: "m", derived: false },
  { key: "site_fence_rent_days", section: "site_setup", label: "Nožogojuma nomas laiks, dienas", unit: "days", derived: false },
  { key: "site_tarps_count", section: "site_setup", label: "Materiālu novietnes Pārklājs 120g/m2, 4x6m\n", unit: "pcs", derived: false },
  { key: "site_scaffold_area_m2", section: "site_setup", label: "Sastatnes kopējā platība, m2", unit: "m2", derived: false },
  { key: "site_scaffold_rent_months", section: "site_setup", label: "Sastatnes nomas periods, mēn", unit: "months", derived: false },
  { key: "site_workbench_count", section: "site_setup", label: "Darba galds, gb", unit: "pcs", derived: false },
  { key: "site_lighting_count", section: "site_setup", label: "Apgaismojums, gb", unit: "pcs", derived: false },
  { key: "site_fire_kit_count", section: "site_setup", label: "Ugunsdrošības inventārs gb", unit: "pcs", derived: false },
  { key: "site_board_count", section: "site_setup", label: "Būvtāfele", unit: "pcs", derived: false },
  { key: "site_rubber_mats_count", section: "site_setup", label: "Iebrauktuves sagatvošana, Gumijas paklāji gb", unit: "pcs", derived: false },
  { key: "site_rubber_mats_days", section: "site_setup", label: "Iebrauktuves sagatvošana, Gumijas paklāji, nomas laiks", unit: "days", derived: false },
  { key: "site_protected_trees_count", section: "site_setup", label: "Aizsargājamo koku skaits", unit: "pcs", derived: false },
  { key: "site_container_months", section: "site_setup", label: "Pārvietojams konteiners strādniekiem un inventāram 6x2.4m, 1 gab nomas ilgums mēn", unit: "months", derived: false },
  { key: "site_safety_signs_count", section: "site_setup", label: "Aizsardzības zīmes, gb", unit: "pcs", derived: false },
  { key: "site_pedestrian_tunnel_m", section: "site_setup", label: "Sastatnes tunelis ielas pusē, garums, m", unit: "m", derived: false },
  { key: "site_construction_lift_days", section: "site_setup", label: "Celtniecības lifts, nomas dienas", unit: "days", derived: false },
  { key: "seam_zn_m2", section: "roofing", label: "Skārds Zn 0.5mm", unit: "m2", derived: false },
  { key: "seam_rukki_m2", section: "roofing", label: "Rukki Purmat 0.5mm", unit: "m2", derived: false },
  { key: "sliding_clips_share", section: "roofing", label: "Slīdošie klemmeri, plakne virs 6.5m", unit: "fraction", derived: false },
  { key: "batten_area_m2", section: "roofing", label: "Latojuma platība", unit: "m2", derived: false },
  { key: "roof_slope_deg", section: "roofing", label: "Jumta slīpums", unit: "deg", derived: false },
  { key: "membrane_area_m2", section: "roofing", label: "Membrāna Rukki 145", unit: "m2", derived: false },
  { key: "eaves_ventilated_m", section: "roofing", label: "Ventilējama dzega, m", unit: "m", derived: false },
  { key: "eaves_unventilated_m", section: "roofing", label: "Neventilējama dzega, m", unit: "m", derived: false },
  { key: "ridge_ventilated_m", section: "roofing", label: "Ventilējama kore, m", unit: "m", derived: false },
  { key: "ridge_screwed_m", section: "roofing", label: "Skrūvējama kore, m", unit: "m", derived: false },
  { key: "verge_1_m", section: "roofing", label: "Vējmala 1", unit: "m", derived: false },
  { key: "verge_1_width_mm", section: "roofing", label: "Vējmala 1", unit: "mm", derived: false },
  { key: "verge_2_m", section: "roofing", label: "Vējmala 2", unit: "m", derived: false },
  { key: "verge_2_width_mm", section: "roofing", label: "Vējmala 2", unit: "mm", derived: false },
  { key: "verge_3_m", section: "roofing", label: "Vējmala 3", unit: "m", derived: false },
  { key: "verge_4_m", section: "roofing", label: "Vējmala 4", unit: "m", derived: false },
  { key: "valley_m", section: "roofing", label: "Satekne, m", unit: "m", derived: false },
  { key: "chimney_flashing_count", section: "roofing", label: "Skursteņa pieslēgumu skaits", unit: "pcs", derived: false },
  { key: "chimney_flashing_perimeter_m", section: "roofing", label: "Skursteņa pieslēgumu kopgarums, m", unit: "m", derived: false },
  { key: "wall_abutment_ventilated_m", section: "roofing", label: "Ventilējams sienas pieslēgums", unit: "m", derived: false },
  { key: "wall_abutment_m", section: "roofing", label: "Sienas pieslēgums", unit: "m", derived: false },
  { key: "parapet_1_m", section: "roofing", label: "Parapets 1, m", unit: "m", derived: false },
  { key: "parapet_2_m", section: "roofing", label: "Parapets 2, m", unit: "m", derived: false },
  { key: "parapet_3_m", section: "roofing", label: "Parapets 3, m", unit: "m", derived: false },
  { key: "roof_hatch_oval_count", section: "roofing", label: "Jumta lūka ovāla 45x60, gb", unit: "pcs", derived: false },
  { key: "vent_outlet_metal_count", section: "roofing", label: "Ventilācijas izvads skārda", unit: "pcs", derived: false },
  { key: "vent_outlet_plastic_count", section: "roofing", label: "Ventilācijas izvads plastmasas", unit: "pcs", derived: false },
  { key: "gutter_m", section: "gutters", label: "Teknes, m", unit: "m", derived: false },
  { key: "gutter_diameter_mm", section: "gutters", label: "Teknes, m", unit: "mm", derived: false },
  { key: "gutter_outlets_count", section: "gutters", label: "Noteces gb", unit: "pcs", derived: false },
  { key: "downpipe_m", section: "gutters", label: "Noteces, m", unit: "m", derived: false },
  { key: "downpipe_diameter_mm", section: "gutters", label: "Noteces, m", unit: "mm", derived: false },
  { key: "downpipe_upper_bends_count", section: "gutters", label: "Augšējie līkumi", unit: "pcs", derived: false },
  { key: "downpipe_lower_bends_count", section: "gutters", label: "Apakšējie līkumi", unit: "pcs", derived: false },
  { key: "gutter_inner_corners_count", section: "gutters", label: "Iekšējie stūri", unit: "pcs", derived: false },
  { key: "gutter_outer_corners_count", section: "gutters", label: "Ārējie stūrī", unit: "pcs", derived: false },
  { key: "gutter_end_caps_count", section: "gutters", label: "Teknes Gali", unit: "pcs", derived: false },
  { key: "rafter_spacing_m", section: "battens", label: "Attālums starp spārēm, m", unit: "m", derived: false },
  { key: "counter_batten_thickness_m", section: "battens", label: "Starplatas biezums, m", unit: "m", derived: false },
  { key: "counter_batten_width_m", section: "battens", label: "Starplatas biezums, m", unit: "m", derived: false },
  { key: "cross_batten_thickness_m", section: "battens", label: "Šķērslatas biezums, m", unit: "m", derived: false },
  { key: "cross_batten_width_m", section: "battens", label: "Šķērslatas biezums, m", unit: "m", derived: false },
  { key: "batten_gap_mm", section: "battens", label: "Latojuma sprauga, mm", unit: "mm", derived: false },
  { key: "cross_batten_coverage_ratio", section: "battens", label: "Latojuma sprauga, mm", unit: "fraction", derived: false },
  { key: "leveling_area_m2", section: "battens", label: "Līmeņojamā platība, m2", unit: "m2", derived: false },
  { key: "insulation_150_m2", section: "insulation", label: "Paroc Ultra 150mm", unit: "m2", derived: false },
  { key: "insulation_200_m2", section: "insulation", label: "Paroc Ultra 200mm", unit: "m2", derived: false },
  { key: "vapour_barrier_m2", section: "insulation", label: "Tvaika barjera, m2", unit: "m2", derived: false },
  { key: "loose_fill_m3", section: "insulation", label: "Beramvate Paroc BLT3", unit: "m3", derived: false },
  { key: "attic_walkway_m", section: "insulation", label: "Bēniņu laipas izbūve 80cm platums, 55cm augstums, m", unit: "m", derived: false },
  { key: "rafters_150x50_count", section: "structure", label: "Spāre 1, gb (6m)", unit: "pcs", derived: false },
  { key: "rafters_200x50_count", section: "structure", label: "Spāre 2, gb (6m)", unit: "pcs", derived: false },
  { key: "wall_plate_150x150_m", section: "structure", label: "Mūrlata 1, m", unit: "m", derived: false },
  { key: "wall_plate_100x200_m", section: "structure", label: "Mūrlata 2, m", unit: "m", derived: false },
  { key: "trusses_1_count", section: "structure", label: "Jumta kopnes 1, gb", unit: "pcs", derived: false },
  { key: "trusses_2_count", section: "structure", label: "Jumta kopnes 2, gb", unit: "pcs", derived: false },
  { key: "rafter_splices_count", section: "structure", label: "Protēze 150x50, 1.5m, gb", unit: "pcs", derived: false },
  { key: "soffit_length_m", section: "soffit", label: "Vēja kaste dekoratīvi dēļi, garums/platība", unit: "m", derived: false },
  { key: "soffit_width_m", section: "soffit", label: "Vēja kaste dekoratīvi dēļi, garums/platība", unit: "m", derived: false },
  { key: "soffit_area_m2", section: "soffit", label: "Vēja kaste dekoratīvi dēļi, garums/platība", unit: "m2 (derived L*W)", derived: true },
  { key: "paint_wood_facade_cleaning_m2", section: "painting", label: "Koka fasādes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "paint_wood_facade_coats", section: "painting", label: "Koka fasādes krāsošana 2 kārtas", unit: "coats", derived: false },
  { key: "paint_wood_facade_area_m2", section: "painting", label: "Koka fasādes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "paint_soffit_cleaning_m2", section: "painting", label: "Vēja kastes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "paint_soffit_coats", section: "painting", label: "Vēja kastes krāsošana 2 kārtas", unit: "coats", derived: false },
  { key: "paint_soffit_area_m2", section: "painting", label: "Vēja kastes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "paint_masonry_cleaning_m2", section: "painting", label: "Mūra fasādes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "paint_masonry_coats", section: "painting", label: "Mūra fasādes krāsošana 2 kārtas", unit: "coats", derived: false },
  { key: "paint_masonry_area_m2", section: "painting", label: "Mūra fasādes krāsošana 2 kārtas", unit: "m2", derived: false },
  { key: "masonry_primer_coats", section: "painting", label: "Mūra gruntēšana", unit: "coats", derived: false },
  { key: "masonry_primer_area_m2", section: "painting", label: "Mūra gruntēšana", unit: "m2", derived: false },
  { key: "snow_guard_tube_m", section: "safety", label: "Sniega barjeras apaļās, m", unit: "m", derived: false },
  { key: "snow_guard_sheet_m", section: "safety", label: "Sniega barjeras skārda, m", unit: "m", derived: false },
  { key: "roof_railing_m", section: "safety", label: "Jumta nožogojums, m (3m posmi)", unit: "m", derived: false },
  { key: "walkway_3m_count", section: "safety", label: "Jumta laipas, 3m", unit: "pcs", derived: false },
  { key: "walkway_1_4m_count", section: "safety", label: "Jumta laipas, 1.4m", unit: "pcs", derived: false },
  { key: "walkway_0_6m_count", section: "safety", label: "Jumta laipas, 0.6m", unit: "pcs", derived: false },
  { key: "safety_rope_m", section: "safety", label: "Drošības trose, m", unit: "m", derived: false },
  { key: "safety_rope_segments", section: "safety", label: "Drošības troses posmi, gb", unit: "pcs", derived: false },
  { key: "roof_ladder_1_2m_count", section: "safety", label: "Jumta kāpnes 1.2m 400mm", unit: "pcs", derived: false },
  { key: "roof_ladder_2_7m_count", section: "safety", label: "Jumta kāpnes 2.7m 400mm", unit: "pcs", derived: false },
  { key: "roof_ladder_3_3m_count", section: "safety", label: "Jumta kāpnes 3.3m 400mm", unit: "pcs", derived: false },
  { key: "wall_ladder_m", section: "safety", label: "Sienas kāpnes, m", unit: "m", derived: false },
  { key: "fire_hatch_count", section: "safety", label: "Ugunsizturīga jumta/bēniņu lūka 1", unit: "pcs", derived: false },
  { key: "lightning_rod", section: "safety", label: "Zibens novedējs ", unit: "?", derived: false },
  { key: "chimney_rebuild_1_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 1, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_1_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 1, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_1_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 1, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_rebuild_2_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 2, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_2_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 2, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_2_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 2, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_rebuild_3_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 3, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_3_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 3, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_3_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 3, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_rebuild_4_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 4, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_4_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 4, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_4_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 4, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_rebuild_5_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 5, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_5_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 5, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_5_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 5, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_rebuild_6_perimeter_m", section: "chimneys", label: "Skurstņa pārmūrēšana 6, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_6_height_m", section: "chimneys", label: "Skurstņa pārmūrēšana 6, m2", unit: "m", derived: false },
  { key: "chimney_rebuild_6_area_m2", section: "chimneys", label: "Skurstņa pārmūrēšana 6, m2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_plaster_1_perimeter_m", section: "chimneys", label: "Skursteņa apmešana 1", unit: "m", derived: false },
  { key: "chimney_plaster_1_height_m", section: "chimneys", label: "Skursteņa apmešana 1", unit: "m", derived: false },
  { key: "chimney_plaster_1_area_m2", section: "chimneys", label: "Skursteņa apmešana 1", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_plaster_2_perimeter_m", section: "chimneys", label: "Skursteņa apmešana 2", unit: "m", derived: false },
  { key: "chimney_plaster_2_height_m", section: "chimneys", label: "Skursteņa apmešana 2", unit: "m", derived: false },
  { key: "chimney_plaster_2_area_m2", section: "chimneys", label: "Skursteņa apmešana 2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_plaster_3_perimeter_m", section: "chimneys", label: "Skursteņa apmešana 3", unit: "m", derived: false },
  { key: "chimney_plaster_3_height_m", section: "chimneys", label: "Skursteņa apmešana 3", unit: "m", derived: false },
  { key: "chimney_plaster_3_area_m2", section: "chimneys", label: "Skursteņa apmešana 3", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_plaster_4_perimeter_m", section: "chimneys", label: "Skursteņa apmešana 4", unit: "m", derived: false },
  { key: "chimney_plaster_4_height_m", section: "chimneys", label: "Skursteņa apmešana 4", unit: "m", derived: false },
  { key: "chimney_plaster_4_area_m2", section: "chimneys", label: "Skursteņa apmešana 4", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_plaster_5_perimeter_m", section: "chimneys", label: "Skursteņa apmešana 5", unit: "m", derived: false },
  { key: "chimney_plaster_5_height_m", section: "chimneys", label: "Skursteņa apmešana 5", unit: "m", derived: false },
  { key: "chimney_plaster_5_area_m2", section: "chimneys", label: "Skursteņa apmešana 5", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_1_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 1", unit: "m", derived: false },
  { key: "chimney_cladding_1_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 1", unit: "m", derived: false },
  { key: "chimney_cladding_1_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 1", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_2_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 2", unit: "m", derived: false },
  { key: "chimney_cladding_2_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 2", unit: "m", derived: false },
  { key: "chimney_cladding_2_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 2", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_3_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 3", unit: "m", derived: false },
  { key: "chimney_cladding_3_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 3", unit: "m", derived: false },
  { key: "chimney_cladding_3_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 3", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_4_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 4", unit: "m", derived: false },
  { key: "chimney_cladding_4_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 4", unit: "m", derived: false },
  { key: "chimney_cladding_4_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 4", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_5_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 5", unit: "m", derived: false },
  { key: "chimney_cladding_5_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 5", unit: "m", derived: false },
  { key: "chimney_cladding_5_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 5", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_6_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 6", unit: "m", derived: false },
  { key: "chimney_cladding_6_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 6", unit: "m", derived: false },
  { key: "chimney_cladding_6_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 6", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cladding_7_perimeter_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 7", unit: "m", derived: false },
  { key: "chimney_cladding_7_height_m", section: "chimneys", label: "Skursteņa apdare ar skārdu 7", unit: "m", derived: false },
  { key: "chimney_cladding_7_area_m2", section: "chimneys", label: "Skursteņa apdare ar skārdu 7", unit: "m2 (derived P*H)", derived: true },
  { key: "chimney_cap_plain_1_length_m", section: "chimneys", label: "Skursteņa jumtiņš 1 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_1_width_m", section: "chimneys", label: "Skursteņa jumtiņš 1 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_1_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 1 bez ekrāna", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_plain_2_length_m", section: "chimneys", label: "Skursteņa jumtiņš 2 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_2_width_m", section: "chimneys", label: "Skursteņa jumtiņš 2 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_2_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 2 bez ekrāna", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_plain_3_length_m", section: "chimneys", label: "Skursteņa jumtiņš 3 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_3_width_m", section: "chimneys", label: "Skursteņa jumtiņš 3 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_3_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 3 bez ekrāna", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_plain_4_length_m", section: "chimneys", label: "Skursteņa jumtiņš 4 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_4_width_m", section: "chimneys", label: "Skursteņa jumtiņš 4 bez ekrāna", unit: "m", derived: false },
  { key: "chimney_cap_plain_4_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 4 bez ekrāna", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_screen_1_length_m", section: "chimneys", label: "Skursteņa jumtiņš 1 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_1_width_m", section: "chimneys", label: "Skursteņa jumtiņš 1 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_1_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 1 ar ekrānu", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_screen_2_length_m", section: "chimneys", label: "Skursteņa jumtiņš 2 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_2_width_m", section: "chimneys", label: "Skursteņa jumtiņš 2 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_2_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 2 ar ekrānu", unit: "m2 (derived L*W)", derived: true },
  { key: "chimney_cap_screen_3_length_m", section: "chimneys", label: "Skursteņa jumtiņš 3 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_3_width_m", section: "chimneys", label: "Skursteņa jumtiņš 3 ar ekrānu", unit: "m", derived: false },
  { key: "chimney_cap_screen_3_area_m2", section: "chimneys", label: "Skursteņa jumtiņš 3 ar ekrānu", unit: "m2 (derived L*W)", derived: true },
  { key: "snow_melt_kit_1_label", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 1", unit: "text", derived: false },
  { key: "snow_melt_kit_1_length_m", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 1", unit: "m", derived: false },
  { key: "snow_melt_kit_1_price", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 1", unit: "EUR ex VAT", derived: false },
  { key: "snow_melt_kit_2_label", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 2", unit: "text", derived: false },
  { key: "snow_melt_kit_2_length_m", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 2", unit: "m", derived: false },
  { key: "snow_melt_kit_2_price", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 2", unit: "EUR ex VAT", derived: false },
  { key: "snow_melt_kit_3_label", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 3", unit: "text", derived: false },
  { key: "snow_melt_kit_3_length_m", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 3", unit: "m", derived: false },
  { key: "snow_melt_kit_3_price", section: "snow_melt", label: "Sniega un ledus kausēšanas sistēmas komplekts 3", unit: "EUR ex VAT", derived: false },
  { key: "electrical_install_label", section: "snow_melt", label: "Elektrokomponentu instalācija. kpl", unit: "text", derived: false },
  { key: "electrical_install_price", section: "snow_melt", label: "Elektrokomponentu instalācija. kpl", unit: "EUR ex VAT", derived: false },
  { key: "roof_window_1_count", section: "windows", label: "Jumta logs 1", unit: "pcs", derived: false },
  { key: "roof_window_1_kit_price", section: "windows", label: "Jumta logs 1", unit: "EUR ex VAT", derived: false },
  { key: "roof_window_1_frame_price", section: "windows", label: "Jumta logs 1", unit: "EUR ex VAT", derived: false },
  { key: "roof_window_2_count", section: "windows", label: "Jumta logs 2", unit: "pcs", derived: false },
  { key: "roof_window_2_kit_price", section: "windows", label: "Jumta logs 2", unit: "EUR ex VAT", derived: false },
  { key: "roof_window_2_frame_price", section: "windows", label: "Jumta logs 2", unit: "EUR ex VAT", derived: false },
  { key: "roof_window_flashing_length_m", section: "windows", label: "Jumta logu pieslēgumu kopgarums, m", unit: "m", derived: false },
  { key: "roof_window_flashing_count", section: "windows", label: "Jumta logu pieslēgumu skaits", unit: "pcs", derived: false },
  { key: "attic_walkway_label", section: "insulation", label: "Bēniņu laipas izbūve 80cm platums, 55cm augstums, m", unit: "text", derived: false },
];
