/**
 * Insulation, vapour barrier, diffusion membrane.
 *
 * Generated from the estimator workbook (Tāme rows 53-69) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Siltināšana un tvaika barjera, m2 ----
  line({
    id: "siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2",
    row: 53,
    block: "siltinasana_un_tvaika_barjera",
    name: "Vate Paroc Ultra 150mm, m2",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.insulation_150_m2,
    reserve: 1.2,
    unitPrice: (c) => c.price('vate_paroc_ultra_150mm'),
    hoursPerUnit: (c) => c.norm('siltinasana.vate_150mm_m2_vates_griesana_ieklasana'),
    blockMaterials: (c) => total(c.span('siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2', 'siltinasana_un_tvaika_barjera.attic_walkway_label', 'materials')),
    blockLabor: (c) => total(c.span('siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2', 'siltinasana_un_tvaika_barjera.attic_walkway_label', 'labor')),
    blockHours: (c) => total(c.span('siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2', 'siltinasana_un_tvaika_barjera.attic_walkway_label', 'hours')),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2', 'siltinasana_un_tvaika_barjera.vate_paroc_ultra_150mm_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vate_paroc_ultra_150mm"},
    tools: ["vates nazis", "respirātors"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.vate_paroc_ultra_200mm_m2",
    row: 54,
    block: "siltinasana_un_tvaika_barjera",
    name: "Vate Paroc Ultra 200mm, m2",
    unit: "m2",
    laborUnit: "m3",
    qty: (c) => c.inp.insulation_200_m2,
    reserve: 1.2,
    unitPrice: (c) => c.price('vate_paroc_ultra_200mm'),
    hoursPerUnit: (c) => c.norm('siltinasana.vate_150mm_m2_vates_griesana_ieklasana'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.vate_paroc_ultra_200mm_m2', 'siltinasana_un_tvaika_barjera.vate_paroc_ultra_200mm_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vate_paroc_ultra_200mm"},
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.beramvate_40cm_paroc_blt3",
    row: 55,
    block: "siltinasana_un_tvaika_barjera",
    name: "Beramvate 40cm Paroc BLT3",
    unit: "m3",
    note: "Paroc BLT3",
    qty: (c) => c.inp.loose_fill_m3,
    reserve: 1.05,
    unitPrice: (c) => c.price('beramvate_1m3'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.beramvate_40cm_paroc_blt3', 'siltinasana_un_tvaika_barjera.beramvate_40cm_paroc_blt3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "beramvate_1m3"},
    blank: ["hours", "rate", "labor", "hoursMarkedPerUnit", "laborMarked"],
    tools: ["respirātors"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.beramvates_iestrade_pakalpojums",
    row: 56,
    block: "siltinasana_un_tvaika_barjera",
    name: "Beramvates iestrāde, pakalpojums",
    unit: "m3",
    qty: (c) => c.inp.loose_fill_m3,
    reserve: 1.05,
    unitPrice: (c) => c.price('beramvates_iestrade_pakalpojums_1m3'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.beramvates_iestrade_pakalpojums', 'siltinasana_un_tvaika_barjera.beramvates_iestrade_pakalpojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "beramvates_iestrade_pakalpojums_1m3"},
    blank: ["hours", "rate", "labor", "hoursMarkedPerUnit", "laborMarked"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.tvaika_barjera_200mkr",
    row: 57,
    block: "siltinasana_un_tvaika_barjera",
    name: "Tvaika barjera 200mkr",
    unit: "m2",
    laborUnit: "m4",
    qty: (c) => c.inp.vapour_barrier_m2,
    reserve: 1.3,
    unitPrice: (c) => c.price('tvaika_barjera_200mkr'),
    hoursPerUnit: (c) => c.norm('siltinasana.tvaika_barjera_ieklasana_kniedesana_grie'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.tvaika_barjera_200mkr', 'siltinasana_un_tvaika_barjera.tvaika_barjera_200mkr', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "tvaika_barjera_200mkr"},
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.tvaika_bareras_limelnta_1m_m2_25m_rulli",
    row: 58,
    block: "siltinasana_un_tvaika_barjera",
    name: "Tvaika bareras līmelnta, 1m/m2, 25m rullī",
    unit: "gb",
    laborUnit: "m",
    param: 25,
    qty: (c) => c.line('siltinasana_un_tvaika_barjera.tvaika_barjera_200mkr').qty/1,
    reserve: 1.3,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve/25, 0),
    unitPrice: 17.8,
    hoursPerUnit: (c) => c.norm('siltinasana.tvaika_bareras_limelnta_1m_m2_25m_rulli'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.tvaika_bareras_limelnta_1m_m2_25m_rulli', 'siltinasana_un_tvaika_barjera.tvaika_bareras_limelnta_1m_m2_25m_rulli', 'blockMaterials', 'blockLabor')),
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.skerslatas_50x50_vates_noturesanai",
    row: 59,
    block: "siltinasana_un_tvaika_barjera",
    name: "Šķērslatas 50x50 vates noturēšanai",
    unit: "m3",
    laborUnit: "m",
    note: "Solis 60cm",
    qty: 250,
    reserve: 1.2,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.05*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('siltinasana.skerslatas_50x50_vates_noturesanai_zages'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.skerslatas_50x50_vates_noturesanai', 'siltinasana_un_tvaika_barjera.skerslatas_50x50_vates_noturesanai', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.naglas_pneimatiskai_pistolei_3_1xl90mm_3",
    row: 60,
    block: "siltinasana_un_tvaika_barjera",
    name: "Naglas pneimatiskai pistolei Ø3.1xL90mm 34°, gb/m",
    unit: "gb",
    param: 4,
    qty: (c) => c.line('siltinasana_un_tvaika_barjera.skerslatas_50x50_vates_noturesanai').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('naglas_pneimatiskai_pistolei_3_1xl90mm_34'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.naglas_pneimatiskai_pistolei_3_1xl90mm_3', 'siltinasana_un_tvaika_barjera.naglas_pneimatiskai_pistolei_3_1xl90mm_3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "naglas_pneimatiskai_pistolei_3_1xl90mm_34"},
    tools: ["Naglu pistole"],
  }),
  line({
    id: "siltinasana_un_tvaika_barjera.attic_walkway_label",
    row: 61,
    block: "siltinasana_un_tvaika_barjera",
    name: "",
    nameFrom: "input:attic_walkway_label",
    unit: "m",
    laborUnit: "m2",
    qty: (c) => c.inp.attic_walkway_m,
    reserve: 1.1,
    unitPrice: (c) => c.price('koka_laipas_izbuve_beninos_80cm_platuma_ar_b'),
    hoursPerUnit: (c) => c.norm('citi.koka_laipas_izbuve_beninos_koka_darbi'),
    blockTotal: (c) => total(c.span('siltinasana_un_tvaika_barjera.attic_walkway_label', 'siltinasana_un_tvaika_barjera.attic_walkway_label', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_laipas_izbuve_beninos_80cm_platuma_ar_b"},
    tools: ["skrūvmašīna un uzgaļi", "Cirkulārais zāģis", "Zobenzāģis"],
  }),

  // ---- Difūzijas membrāna, m2 ----
  line({
    id: "difuzijas_membrana.rukki_145g",
    row: 62,
    block: "difuzijas_membrana",
    name: "Rukki 145g",
    unit: "gb",
    laborUnit: "m2",
    note: "Pašlīmējošā 75m2/rulli",
    qty: (c) => c.inp.membrane_area_m2,
    reserve: 1.3,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve/75, 0),
    unitPrice: (c) => c.price('difuzijas_membrana_rukki_145g_75m2_rullis'),
    hoursPerUnit: (c) => c.norm('difuzijas_membrana.rukki_145g_skavosana_griesana'),
    blockMaterials: (c) => total(c.span('difuzijas_membrana.rukki_145g', 'difuzijas_membrana.none_5', 'materials')),
    blockLabor: (c) => total(c.span('difuzijas_membrana.rukki_145g', 'difuzijas_membrana.none_5', 'labor')),
    blockHours: (c) => total(c.span('difuzijas_membrana.rukki_145g', 'difuzijas_membrana.none_5', 'hours')),
    blockTotal: (c) => total(c.span('difuzijas_membrana.rukki_145g', 'difuzijas_membrana.rukki_145g', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "difuzijas_membrana_rukki_145g_75m2_rullis"},
    tools: ["Skavotājs"],
  }),
  line({
    id: "difuzijas_membrana.skavas_gb_m_starplatu_garums",
    row: 63,
    block: "difuzijas_membrana",
    name: "Skavas gb/m (starplatu garums)",
    unit: "gb",
    param: 5,
    qty: (c) => c.this.param*c.line('latojums.starplatojums').qty,
    reserve: 1.2,
    unitPrice: (c) => c.price('skavas_10mm'),
    blockTotal: (c) => total(c.span('difuzijas_membrana.skavas_gb_m_starplatu_garums', 'difuzijas_membrana.skavas_gb_m_starplatu_garums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "skavas_10mm"},
    blank: ["hours"],
  }),
  line({
    id: "difuzijas_membrana.membranas_limlenta",
    row: 64,
    block: "difuzijas_membrana",
    name: "Membrānas līmlenta",
    unit: "gb",
    laborUnit: "m",
    note: "Ruļļu skaits 25m/rullī",
    qtyRes: (c) => ceilUp(total(c.span('difuzijas_membrana.none', 'difuzijas_membrana.none_5', 'qtyRes'))/25, 0),
    unitPrice: (c) => c.price('difuzijas_limlente_gerlinger_gerband_outside'),
    hoursPerUnit: (c) => c.norm('difuzijas_membrana.membranas_limlenta_limesana_griesana'),
    hours: (c) => c.this.hoursPerUnit*total(c.span('difuzijas_membrana.none', 'difuzijas_membrana.none_5', 'qtyRes')),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*total(c.span('difuzijas_membrana.none', 'difuzijas_membrana.none_5', 'qtyRes'))*c.this.rate,
    blockTotal: (c) => total(c.span('difuzijas_membrana.membranas_limlenta', 'difuzijas_membrana.membranas_limlenta', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "difuzijas_limlente_gerlinger_gerband_outside"},
    tools: ["Nazis un asmeņi"],
  }),
  line({
    id: "difuzijas_membrana.none",
    row: 65,
    block: "difuzijas_membrana",
    name: null,
    note: "Pa perimetru apakšlāsenei",
    qty: (c) => c.inp.eaves_ventilated_m+c.inp.eaves_unventilated_m,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    blockTotal: (c) => total(c.span('difuzijas_membrana.none', 'difuzijas_membrana.none', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "difuzijas_membrana.none_2",
    row: 66,
    block: "difuzijas_membrana",
    name: null,
    note: "Kores līnijai",
    qty: (c) => c.inp.ridge_ventilated_m+c.inp.ridge_screwed_m,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    blockTotal: (c) => total(c.span('difuzijas_membrana.none_2', 'difuzijas_membrana.none_2', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "difuzijas_membrana.none_3",
    row: 67,
    block: "difuzijas_membrana",
    name: null,
    note: "Ap skursteņiem",
    qty: (c) => c.inp.chimney_flashing_perimeter_m,
    reserve: 2,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    blockTotal: (c) => total(c.span('difuzijas_membrana.none_3', 'difuzijas_membrana.none_3', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "difuzijas_membrana.none_4",
    row: 68,
    block: "difuzijas_membrana",
    name: null,
    note: "Pie sienas pieslēgumiem",
    qty: (c) => total([c.inp.wall_abutment_ventilated_m, c.inp.wall_abutment_m]),
    reserve: 1.2,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    blockTotal: (c) => total(c.span('difuzijas_membrana.none_4', 'difuzijas_membrana.none_4', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "difuzijas_membrana.none_5",
    row: 69,
    block: "difuzijas_membrana",
    name: null,
    note: "Logu pieslēgumi",
    qty: (c) => c.inp.bug_unlabeled_P9,
    reserve: 2,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    blockTotal: (c) => total(c.span('difuzijas_membrana.none_5', 'difuzijas_membrana.none_5', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
];
