/**
 * Ridge and verges.
 *
 * Generated from the estimator workbook (Tāme rows 174-193) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Ventilējama kore, m ----
  line({
    id: "ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga",
    row: 174,
    block: "ventilejama_kore",
    name: "Lāsene 90 grādi (13+3+5+2+2=25cm) Kores garums x 2",
    unit: "m",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.ridge_ventilated_m*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('lasene_90_gradi_13_3_5_2_2_25cm_kore', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga'),
    blockMaterials: (c) => total(c.span('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga', 'ventilejama_kore.banu_uzlocisana_un_griesana', 'materials')),
    blockLabor: (c) => total(c.span('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga', 'ventilejama_kore.banu_uzlocisana_un_griesana', 'labor')),
    blockHours: (c) => total(c.span('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga', 'ventilejama_kore.banu_uzlocisana_un_griesana', 'hours')),
    blockTotal: (c) => total(c.span('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga', 'ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "lasene_90_gradi_13_3_5_2_2_25cm_kore", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m",
    row: 175,
    block: "ventilejama_kore",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_kore.lasene_90_gradi_13_3_5_2_2_25cm_kores_ga').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m', 'ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_kore.perferets_skards_2_5_7cm_kores_garums_x",
    row: 176,
    block: "ventilejama_kore",
    name: "Perferēts skārds (2+5=7cm) Kores garums x 2",
    unit: "m",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.ridge_ventilated_m*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('perferets_skards_2_5_7cm_kores_garum', 'perforated_07'),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.perferets_skards_2_5_7cm_kores_garums_x'),
    blockTotal: (c) => total(c.span('ventilejama_kore.perferets_skards_2_5_7cm_kores_garums_x', 'ventilejama_kore.perferets_skards_2_5_7cm_kores_garums_x', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "perferets_skards_2_5_7cm_kores_garum", "variant": "perforated_07"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m_2",
    row: 177,
    block: "ventilejama_kore",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_kore.perferets_skards_2_5_7cm_kores_garums_x').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m_2', 'ventilejama_kore.skruves_klemmeru_4_5x2_5_3gb_m_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_kore.brusas_50x50_kores_garums_x_2",
    row: 178,
    block: "ventilejama_kore",
    name: "Brusas 50x50, Kores garums x 2",
    unit: "m3",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.ridge_ventilated_m*c.this.param,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0)*0.05*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.brusas_50x50_kores_garums_x_2_zagesana_s'),
    blockTotal: (c) => total(c.span('ventilejama_kore.brusas_50x50_kores_garums_x_2', 'ventilejama_kore.brusas_50x50_kores_garums_x_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_kore.kokskruves_5x100_3gb_m",
    row: 179,
    block: "ventilejama_kore",
    name: "Kokskrūves 5x100, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_kore.brusas_50x50_kores_garums_x_2').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x100'),
    blockTotal: (c) => total(c.span('ventilejama_kore.kokskruves_5x100_3gb_m', 'ventilejama_kore.kokskruves_5x100_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x100"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_kore.delis_25x100_kores_garums_x_2",
    row: 180,
    block: "ventilejama_kore",
    name: "Dēlis 25x100, Kores garums x 2",
    unit: "m3",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.ridge_ventilated_m*c.this.param,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0)*0.025*0.1,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.delis_25x100_kores_garums_x_2_zagesana_s'),
    blockTotal: (c) => total(c.span('ventilejama_kore.delis_25x100_kores_garums_x_2', 'ventilejama_kore.delis_25x100_kores_garums_x_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["Cirkulārais zāģis", "Striķis un krīts"],
  }),
  line({
    id: "ventilejama_kore.kokskruves_5x70_3gb_m",
    row: 181,
    block: "ventilejama_kore",
    name: "Kokskrūves 5x70, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('ventilejama_kore.delis_25x100_kores_garums_x_2').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x70'),
    blockTotal: (c) => total(c.span('ventilejama_kore.kokskruves_5x70_3gb_m', 'ventilejama_kore.kokskruves_5x70_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x70"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "ventilejama_kore.kores_nosegelemnts_2_20_20_2_44cm",
    row: 182,
    block: "ventilejama_kore",
    name: "Kores nosegelemnts (2+20+20+2=44cm)",
    unit: "m",
    laborUnit: "m",
    note: "Kores garums",
    qty: (c) => c.inp.ridge_ventilated_m,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('kores_nosegelemnts_2_20_20_2_44cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.kores_nosegelemnts_2_20_20_2_44cm_kores'),
    blockTotal: (c) => total(c.span('ventilejama_kore.kores_nosegelemnts_2_20_20_2_44cm', 'ventilejama_kore.kores_nosegelemnts_2_20_20_2_44cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "kores_nosegelemnts_2_20_20_2_44cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "ventilejama_kore.banu_uzlocisana_un_griesana",
    row: 183,
    block: "ventilejama_kore",
    name: "Bāņu uzlocīšana un griešana",
    unit: "gb",
    laborUnit: "gb",
    note: "Papildus darbība, bāņu skaits",
    qty: (c) => ceilUp(c.inp.ridge_ventilated_m/0.55, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    hoursPerUnit: (c) => c.norm('ventilejama_kore.banu_uzlocisana_un_griesana_banu_uzlocis'),
    blockTotal: (c) => total(c.span('ventilejama_kore.banu_uzlocisana_un_griesana', 'ventilejama_kore.banu_uzlocisana_un_griesana', 'blockMaterials', 'blockLabor')),
    tools: ["Lielās pacelšanas stangas", "Skārdnieka instrumenti"],
  }),

  // ---- Skrūvējamajai korei, m ----
  line({
    id: "skruvejamajai_korei.apakskores_profils_kores_garums_x_2",
    row: 184,
    block: "skruvejamajai_korei",
    name: "Apakškores profils, Kores garums x 2",
    unit: "m",
    laborUnit: "m",
    param: 2,
    qty: (c) => c.inp.ridge_screwed_m*c.this.param,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('apakskores_profils_2_5_2_5_5_1_11cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('skruvejamajai_kore.apakskores_profils_kores_garums_x_2_grie'),
    blockMaterials: (c) => total(c.span('skruvejamajai_korei.apakskores_profils_kores_garums_x_2', 'skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m', 'materials')),
    blockLabor: (c) => total(c.span('skruvejamajai_korei.apakskores_profils_kores_garums_x_2', 'skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m', 'labor')),
    blockHours: (c) => total(c.span('skruvejamajai_korei.apakskores_profils_kores_garums_x_2', 'skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m', 'hours')),
    blockTotal: (c) => total(c.span('skruvejamajai_korei.apakskores_profils_kores_garums_x_2', 'skruvejamajai_korei.apakskores_profils_kores_garums_x_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "apakskores_profils_2_5_2_5_5_1_11cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "skruvejamajai_korei.klemmeru_skruves_6gb_m",
    row: 185,
    block: "skruvejamajai_korei",
    name: "Klemmeru skrūves 6gb/m",
    unit: "gb",
    param: 6,
    qty: (c) => c.line('skruvejamajai_korei.apakskores_profils_kores_garums_x_2').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('skruvejamajai_korei.klemmeru_skruves_6gb_m', 'skruvejamajai_korei.klemmeru_skruves_6gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "skruvejamajai_korei.kores_profils_2_20_20_2_44cm",
    row: 186,
    block: "skruvejamajai_korei",
    name: "Kores profils (2+20+20+2= 44cm)",
    unit: "m",
    laborUnit: "m",
    note: "Kores garums ",
    qty: (c) => c.inp.ridge_screwed_m,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('kores_profils_2_20_20_2_44cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('skruvejamajai_kore.kores_profils_2_20_20_2_44cm_griesana_sk'),
    blockTotal: (c) => total(c.span('skruvejamajai_korei.kores_profils_2_20_20_2_44cm', 'skruvejamajai_korei.kores_profils_2_20_20_2_44cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "kores_profils_2_20_20_2_44cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts"],
  }),
  line({
    id: "skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m",
    row: 187,
    block: "skruvejamajai_korei",
    name: "Jumta skrūves 4.8x35mm, 6gb/m",
    unit: "gb",
    param: 6,
    qty: (c) => c.line('skruvejamajai_korei.kores_profils_2_20_20_2_44cm').qty*c.this.param,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('jumta_skruves_4_8x35'),
    blockTotal: (c) => total(c.span('skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m', 'skruvejamajai_korei.jumta_skruves_4_8x35mm_6gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_skruves_4_8x35"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),

  // ---- Vējmalu montāža uz aizkabēm, m ----
  line({
    id: "vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm",
    row: 188,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Aizkabes (2+8=10cm)",
    unit: "m",
    laborUnit: "m",
    qty: (c) => total([c.inp.verge_1_m, c.inp.verge_2_m, c.inp.verge_3_m, c.inp.verge_4_m]),
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('aizkabes_2_8_10cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('vejmalu_montaza_uz.aizkabes_2_8_10cm_griesana_skruvesana'),
    blockMaterials: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm', 'vejmalu_montaza_uz_aizkabem.vejmalas_4', 'materials')),
    blockLabor: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm', 'vejmalu_montaza_uz_aizkabem.vejmalas_4', 'labor')),
    blockHours: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm', 'vejmalu_montaza_uz_aizkabem.vejmalas_4', 'hours')),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm', 'vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "aizkabes_2_8_10cm", "variant": "rukki_05"},
    tools: ["Skārdnieka instrumenti"],
  }),
  line({
    id: "vejmalu_montaza_uz_aizkabem.skruves_klemmeru_4_5x2_5_3gb_m",
    row: 189,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Skrūves Klemmeru 4.5x2.5, 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => c.line('vejmalu_montaza_uz_aizkabem.aizkabes_2_8_10cm').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.skruves_klemmeru_4_5x2_5_3gb_m', 'vejmalu_montaza_uz_aizkabem.skruves_klemmeru_4_5x2_5_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi", "Striķis un krīts"],
  }),
  line({
    id: "vejmalu_montaza_uz_aizkabem.vejmalas_1",
    row: 190,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Vējmalas 1",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.verge_1_m,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('vejmalas_1_1_1_25_1_5_28_5cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('vejmalu_montaza_uz.vejmalas_1'),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.vejmalas_1', 'vejmalu_montaza_uz_aizkabem.vejmalas_1', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "vejmalas_1_1_1_25_1_5_28_5cm", "variant": "rukki_05"},
  }),
  line({
    id: "vejmalu_montaza_uz_aizkabem.vejmalas_2",
    row: 191,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Vējmalas 2",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.verge_2_m,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.profile('vejmalas_2_1_1_20_1_5_23_5cm', 'rukki_05'),
    hoursPerUnit: (c) => c.norm('vejmalu_montaza_uz.vejmalas_1'),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.vejmalas_2', 'vejmalu_montaza_uz_aizkabem.vejmalas_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "sd", "id": "vejmalas_2_1_1_20_1_5_23_5cm", "variant": "rukki_05"},
  }),
  line({
    id: "vejmalu_montaza_uz_aizkabem.vejmalas_3",
    row: 192,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Vējmalas 3",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.verge_3_m,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    hoursPerUnit: (c) => c.norm('vejmalu_montaza_uz.vejmalas_1'),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.vejmalas_3', 'vejmalu_montaza_uz_aizkabem.vejmalas_3', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "vejmalu_montaza_uz_aizkabem.vejmalas_4",
    row: 193,
    block: "vejmalu_montaza_uz_aizkabem",
    name: "Vējmalas 4",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.verge_4_m,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    hoursPerUnit: (c) => c.norm('vejmalu_montaza_uz.vejmalas_1'),
    blockTotal: (c) => total(c.span('vejmalu_montaza_uz_aizkabem.vejmalas_4', 'vejmalu_montaza_uz_aizkabem.vejmalas_4', 'blockMaterials', 'blockLabor')),
  }),
];
