/**
 * Snow guards, ladders, walkways, rope, railing, fire hatch, snow melting.
 *
 * Generated from the estimator workbook (Tāme rows 252-280) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Sniega barjeras, m ----
  line({
    id: "sniega_barjeras.apalas_caurulveida",
    row: 252,
    block: "sniega_barjeras",
    name: "Apaļās cauruļveida",
    laborUnit: "m",
    note: "m",
    qty: (c) => c.inp.snow_guard_tube_m,
    hoursPerUnit: (c) => c.norm('sniega_barjeras.apalas_caurulveida_skruvesana'),
    blockMaterials: (c) => total(c.span('sniega_barjeras.apalas_caurulveida', 'sniega_barjeras.stienu_posmu_fiksatoru_pari_pe', 'materials')),
    blockLabor: (c) => total(c.span('sniega_barjeras.apalas_caurulveida', 'sniega_barjeras.stienu_posmu_fiksatoru_pari_pe', 'labor')),
    blockHours: (c) => total(c.span('sniega_barjeras.apalas_caurulveida', 'sniega_barjeras.stienu_posmu_fiksatoru_pari_pe', 'hours')),
    blockTotal: (c) => total(c.span('sniega_barjeras.apalas_caurulveida', 'sniega_barjeras.apalas_caurulveida', 'blockMaterials', 'blockLabor')),
    blank: ["qtyRes"],
  }),
  line({
    id: "sniega_barjeras.sniega_barjeras_stienu_pari_pe",
    row: 253,
    block: "sniega_barjeras",
    name: "Sniega barjeras stieņu pāri, PE",
    unit: "gb",
    param: 2,
    qty: (c) => ceilUp(c.line('sniega_barjeras.apalas_caurulveida').qty/c.this.param, 0),
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('sniega_barjeras_stienu_pari_pe_2m'),
    blockTotal: (c) => total(c.span('sniega_barjeras.sniega_barjeras_stienu_pari_pe', 'sniega_barjeras.sniega_barjeras_stienu_pari_pe', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sniega_barjeras_stienu_pari_pe_2m"},
    blank: ["hours"],
  }),
  line({
    id: "sniega_barjeras.sniega_barjera_stiprinajums_valcprofilam",
    row: 254,
    block: "sniega_barjeras",
    name: "Sniega barjera stiprinājums Valcprofilam, PE (ik pa 0.8m)",
    unit: "gb",
    param: 0.8,
    qty: (c) => c.line('sniega_barjeras.apalas_caurulveida').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('sniega_barjera_stiprinajums_valcprofilam_pe'),
    blockTotal: (c) => total(c.span('sniega_barjeras.sniega_barjera_stiprinajums_valcprofilam', 'sniega_barjeras.sniega_barjera_stiprinajums_valcprofilam', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sniega_barjera_stiprinajums_valcprofilam_pe"},
    blank: ["hours"],
    tools: ["Muciņa", "Seškantes atslēga", "Strīķis un krīts"],
  }),
  line({
    id: "sniega_barjeras.stienu_posmu_savienojumu_pari",
    row: 255,
    block: "sniega_barjeras",
    name: "Stieņu Posmu savienojumu pāri",
    unit: "gb",
    qty: (c) => c.line('sniega_barjeras.sniega_barjeras_stienu_pari_pe').qty/2,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('stienu_posmu_savienojumu_pari'),
    blockTotal: (c) => total(c.span('sniega_barjeras.stienu_posmu_savienojumu_pari', 'sniega_barjeras.stienu_posmu_savienojumu_pari', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "stienu_posmu_savienojumu_pari"},
    blank: ["hours"],
  }),
  line({
    id: "sniega_barjeras.stienu_posmu_fiksatoru_pari_pe",
    row: 256,
    block: "sniega_barjeras",
    name: "Stieņu Posmu fiksatoru pāri, PE",
    unit: "gb",
    qty: (c) => c.line('sniega_barjeras.apalas_caurulveida').qty/6,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.reserve*c.this.qty, 0),
    unitPrice: (c) => c.price('stienu_posmu_fiksatoru_pari_pe'),
    blockTotal: (c) => total(c.span('sniega_barjeras.stienu_posmu_fiksatoru_pari_pe', 'sniega_barjeras.stienu_posmu_fiksatoru_pari_pe', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "stienu_posmu_fiksatoru_pari_pe"},
    blank: ["hours"],
  }),

  // ---- Jumta kāpnes, gb ----
  line({
    id: "jumta_kapnes.jumta_kapnes_1_2m_400mm",
    row: 257,
    block: "jumta_kapnes",
    name: "Jumta kāpnes 1.2m 400mm",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.roof_ladder_1_2m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_kapnes_1_2m_400mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_kapnes_komplekts_m_montaza'),
    blockMaterials: (c) => total(c.span('jumta_kapnes.jumta_kapnes_1_2m_400mm', 'jumta_kapnes.jumt_kapnu_balstu_paris', 'materials')),
    blockLabor: (c) => total(c.span('jumta_kapnes.jumta_kapnes_1_2m_400mm', 'jumta_kapnes.jumt_kapnu_balstu_paris', 'labor')),
    blockHours: (c) => total(c.span('jumta_kapnes.jumta_kapnes_1_2m_400mm', 'jumta_kapnes.jumt_kapnu_balstu_paris', 'hours')),
    blockTotal: (c) => total(c.span('jumta_kapnes.jumta_kapnes_1_2m_400mm', 'jumta_kapnes.jumta_kapnes_1_2m_400mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_kapnes_1_2m_400mm"},
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_kapnes.jumta_kapnes_2_7m_400mm",
    row: 258,
    block: "jumta_kapnes",
    name: "Jumta kāpnes 2.7m 400mm",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.roof_ladder_2_7m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_kapnes_2_7m_400mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_kapnes_komplekts_m_montaza'),
    blockTotal: (c) => total(c.span('jumta_kapnes.jumta_kapnes_2_7m_400mm', 'jumta_kapnes.jumta_kapnes_2_7m_400mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_kapnes_2_7m_400mm"},
  }),
  line({
    id: "jumta_kapnes.jumta_kapnes_3_3m_400mm",
    row: 259,
    block: "jumta_kapnes",
    name: "Jumta kāpnes 3.3m 400mm",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.roof_ladder_3_3m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_kapnes_3_3m_400mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_kapnes_komplekts_m_montaza'),
    blockTotal: (c) => total(c.span('jumta_kapnes.jumta_kapnes_3_3m_400mm', 'jumta_kapnes.jumta_kapnes_3_3m_400mm', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_kapnes_3_3m_400mm"},
  }),
  line({
    id: "jumta_kapnes.jumt_kapnu_balstu_paris",
    row: 260,
    block: "jumta_kapnes",
    name: "Jumt kāpņu balstu pāris",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*total(c.span('jumta_kapnes.jumta_kapnes_1_2m_400mm', 'jumta_kapnes.jumta_kapnes_3_3m_400mm', 'qty')),
    reserve: 1,
    unitPrice: (c) => c.price('jumt_kapnu_balstu_paris'),
    blockTotal: (c) => total(c.span('jumta_kapnes.jumt_kapnu_balstu_paris', 'jumta_kapnes.jumt_kapnu_balstu_paris', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumt_kapnu_balstu_paris"},
    blank: ["hours"],
  }),

  // ---- Sienas kāpnes, m ----
  line({
    id: "sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl",
    row: 261,
    block: "sienas_kapnes",
    name: "Sienas kāpnes 700mm karsti cinkotas kpl./m",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.wall_ladder_m,
    reserve: 1,
    unitPrice: (c) => c.price('sienas_kapnes_700mm_karsti_cinkotas_komplekt'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.sienas_kapnes_700mm_dibelosana_montaza'),
    blockMaterials: (c) => total(c.span('sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl', 'sienas_kapnes.urbis_betonam_14mm_1gb_10gb', 'materials')),
    blockLabor: (c) => total(c.span('sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl', 'sienas_kapnes.urbis_betonam_14mm_1gb_10gb', 'labor')),
    blockHours: (c) => total(c.span('sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl', 'sienas_kapnes.urbis_betonam_14mm_1gb_10gb', 'hours')),
    blockTotal: (c) => total(c.span('sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl', 'sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sienas_kapnes_700mm_karsti_cinkotas_komplekt"},
  }),
  line({
    id: "sienas_kapnes.urbis_betonam_14mm_1gb_10gb",
    row: 262,
    block: "sienas_kapnes",
    name: "Urbis betonam 14mm, 1gb/10gb",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.line('sienas_kapnes.sienas_kapnes_700mm_karsti_cinkotas_kpl').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('urbis_betonam_14mm'),
    blockTotal: (c) => total(c.span('sienas_kapnes.urbis_betonam_14mm_1gb_10gb', 'sienas_kapnes.urbis_betonam_14mm_1gb_10gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "urbis_betonam_14mm"},
    blank: ["hours"],
  }),

  // ---- Jumta laipas, gb ----
  line({
    id: "jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu",
    row: 263,
    block: "jumta_laipas",
    name: "Jumta laipas 3m, 4 stiprinājumi uz posmu",
    unit: "gb",
    laborUnit: "gb",
    param: 4,
    qty: (c) => c.inp.walkway_3m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_laipa_3000mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_laipas_viena_posma_montaza_vienalg'),
    blockMaterials: (c) => total(c.span('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu', 'jumta_laipas.lenka_regulatori', 'materials')),
    blockLabor: (c) => total(c.span('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu', 'jumta_laipas.lenka_regulatori', 'labor')),
    blockHours: (c) => total(c.span('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu', 'jumta_laipas.lenka_regulatori', 'hours')),
    blockTotal: (c) => total(c.span('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu', 'jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_laipa_3000mm"},
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_laipas.jumta_laipa_1_4m_3_stiprinajumi_uz_posmu",
    row: 264,
    block: "jumta_laipas",
    name: "Jumta laipa 1.4m, 3 stiprinājumi uz posmu",
    unit: "gb",
    laborUnit: "gb",
    param: 2,
    qty: (c) => c.inp.walkway_1_4m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_laipa_1400mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_laipas_viena_posma_montaza_vienalg'),
    blockTotal: (c) => total(c.span('jumta_laipas.jumta_laipa_1_4m_3_stiprinajumi_uz_posmu', 'jumta_laipas.jumta_laipa_1_4m_3_stiprinajumi_uz_posmu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_laipa_1400mm"},
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_laipas.jumta_laipa_0_6m_2_stiprinajumi_uz_posmu",
    row: 265,
    block: "jumta_laipas",
    name: "Jumta laipa 0.6m, 2 stiprinājumi uz posmu",
    unit: "gb",
    laborUnit: "gb",
    param: 2,
    qty: (c) => c.inp.walkway_0_6m_count,
    reserve: 1,
    unitPrice: (c) => c.price('jumta_laipa_600mm'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_laipas_viena_posma_montaza_vienalg'),
    blockTotal: (c) => total(c.span('jumta_laipas.jumta_laipa_0_6m_2_stiprinajumi_uz_posmu', 'jumta_laipas.jumta_laipa_0_6m_2_stiprinajumi_uz_posmu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_laipa_600mm"},
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_laipas.stiprinajumi_pie_valcprofila_gb",
    row: 266,
    block: "jumta_laipas",
    name: "Stiprinājumi pie valcprofila, gb",
    unit: "gb",
    qty: (c) => c.line('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu').qty*c.line('jumta_laipas.jumta_laipas_3m_4_stiprinajumi_uz_posmu').param+c.line('jumta_laipas.jumta_laipa_1_4m_3_stiprinajumi_uz_posmu').qty*c.line('jumta_laipas.jumta_laipa_1_4m_3_stiprinajumi_uz_posmu').param+c.line('jumta_laipas.jumta_laipa_0_6m_2_stiprinajumi_uz_posmu').qty*c.line('jumta_laipas.jumta_laipa_0_6m_2_stiprinajumi_uz_posmu').param,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('jumta_laipas_stiprinajums_valcprofils'),
    blockTotal: (c) => total(c.span('jumta_laipas.stiprinajumi_pie_valcprofila_gb', 'jumta_laipas.stiprinajumi_pie_valcprofila_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_laipas_stiprinajums_valcprofils"},
    blank: ["hours"],
  }),
  line({
    id: "jumta_laipas.lenka_regulatori",
    row: 267,
    block: "jumta_laipas",
    name: "Leņķa regulātori",
    unit: "gb",
    note: "gb=stiprinājumu skaits",
    qty: (c) => c.line('jumta_laipas.stiprinajumi_pie_valcprofila_gb').qty,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('jumta_laipas_slipuma_regulesanas_plaksne'),
    blockTotal: (c) => total(c.span('jumta_laipas.lenka_regulatori', 'jumta_laipas.lenka_regulatori', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_laipas_slipuma_regulesanas_plaksne"},
    blank: ["hours"],
  }),

  // ---- Drošības trose, m ----
  line({
    id: "drosibas_trose.drosibas_troses_8mm",
    row: 268,
    block: "drosibas_trose",
    name: "Drošības troses 8mm",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.safety_rope_m,
    reserve: 1.2,
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.drosibas_troses_8mm_stiprinajumu_montaza'),
    blockMaterials: (c) => total(c.span('drosibas_trose.drosibas_troses_8mm', 'drosibas_trose.vidusbalsti_ik_pa_5m', 'materials')),
    blockLabor: (c) => total(c.span('drosibas_trose.drosibas_troses_8mm', 'drosibas_trose.vidusbalsti_ik_pa_5m', 'labor')),
    blockHours: (c) => total(c.span('drosibas_trose.drosibas_troses_8mm', 'drosibas_trose.vidusbalsti_ik_pa_5m', 'hours')),
    blockTotal: (c) => total(c.span('drosibas_trose.drosibas_troses_8mm', 'drosibas_trose.drosibas_troses_8mm', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "drosibas_trose.gala_balsti_ar_spriegotajiem_posmu_skait",
    row: 269,
    block: "drosibas_trose",
    name: "Gala balsti ar spriegotājiem posmu skaits x 2",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*c.inp.safety_rope_segments,
    reserve: 1,
    blockTotal: (c) => total(c.span('drosibas_trose.gala_balsti_ar_spriegotajiem_posmu_skait', 'drosibas_trose.gala_balsti_ar_spriegotajiem_posmu_skait', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "drosibas_trose.vidusbalsti_ik_pa_5m",
    row: 270,
    block: "drosibas_trose",
    name: "Vidusbalsti,  ik pa 5m",
    unit: "gb",
    param: 5,
    qty: (c) => (c.line('drosibas_trose.drosibas_troses_8mm').qty-10)/c.this.param,
    reserve: 1,
    blockTotal: (c) => total(c.span('drosibas_trose.vidusbalsti_ik_pa_5m', 'drosibas_trose.vidusbalsti_ik_pa_5m', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),

  // ---- Jumta nožogojums, m ----
  line({
    id: "jumta_nozogojums.jumta_nozogojuma_barjera_komplekts_ar_st",
    row: 271,
    block: "jumta_nozogojums",
    name: "Jumta nožogojuma barjera komplekts ar stiprinājumiem 3m posmi, m",
    unit: "m",
    laborUnit: "m",
    qty: (c) => c.inp.roof_railing_m,
    reserve: 1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('jumta_nozogojuma_barjera_ar_stiprinajumiem_k'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_nozogojuma_barjera_m_montaza_skruv'),
    blockMaterials: (c) => total(c.this.materials),
    blockLabor: (c) => total(c.this.labor),
    blockHours: (c) => total(c.this.hours),
    blockTotal: (c) => total(c.span('jumta_nozogojums.jumta_nozogojuma_barjera_komplekts_ar_st', 'jumta_nozogojums.jumta_nozogojuma_barjera_komplekts_ar_st', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "jumta_nozogojuma_barjera_ar_stiprinajumiem_k"},
    tools: ["Muciņa", "Seškantes atslēga", "Skrūvmašīna un uzgaļi", "Strīkis un krīts"],
  }),

  // ---- Zibens novedēji ----
  line({
    id: "zibens_novedeji.zibens_novedejs_pasivais",
    row: 272,
    block: "zibens_novedeji",
    name: "Zibens novedējs pasīvais",
    blockMaterials: (c) => total(c.span('zibens_novedeji.zibens_novedejs_pasivais', 'zibens_novedeji.novadisana_lidz_zemei', 'materials')),
    blockLabor: (c) => total(c.span('zibens_novedeji.zibens_novedejs_pasivais', 'zibens_novedeji.novadisana_lidz_zemei', 'labor')),
    blockHours: (c) => total(c.span('zibens_novedeji.zibens_novedejs_pasivais', 'zibens_novedeji.novadisana_lidz_zemei', 'hours')),
    blockTotal: (c) => total(c.span('zibens_novedeji.zibens_novedejs_pasivais', 'zibens_novedeji.zibens_novedejs_pasivais', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
    tools: ["atslēgas"],
  }),
  line({
    id: "zibens_novedeji.stiprinajumi_pie_jumta",
    row: 273,
    block: "zibens_novedeji",
    name: "Stiprinājumi pie jumta",
    note: "3gb/m",
    blockTotal: (c) => total(c.span('zibens_novedeji.stiprinajumi_pie_jumta', 'zibens_novedeji.stiprinajumi_pie_jumta', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
  line({
    id: "zibens_novedeji.novadisana_lidz_zemei",
    row: 274,
    block: "zibens_novedeji",
    name: "Novadīšana līdz zemei",
    blockTotal: (c) => total(c.span('zibens_novedeji.novadisana_lidz_zemei', 'zibens_novedeji.novadisana_lidz_zemei', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),

  // ---- Ugunsdroša lūka, gb ----
  line({
    id: "ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka",
    row: 275,
    block: "ugunsdrosa_luka",
    name: "Jumta/ bēniņu Ugunsdroša lūka",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.fire_hatch_count,
    reserve: 1,
    unitPrice: (c) => c.price('ugunsdrosa_ei30_necaurspidiga_jumta_luka_600'),
    hoursPerUnit: (c) => c.norm('jumta_drosibas_ele.jumta_beninu_ugunsdrosa_luka_montaza_ar'),
    blockMaterials: (c) => total(c.span('ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka', 'ugunsdrosa_luka.stiprinajumi', 'materials')),
    blockLabor: (c) => total(c.span('ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka', 'ugunsdrosa_luka.stiprinajumi', 'labor')),
    blockHours: (c) => total(c.span('ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka', 'ugunsdrosa_luka.stiprinajumi', 'hours')),
    blockTotal: (c) => total(c.span('ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka', 'ugunsdrosa_luka.jumta_beninu_ugunsdrosa_luka', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ugunsdrosa_ei30_necaurspidiga_jumta_luka_600"},
  }),
  line({
    id: "ugunsdrosa_luka.stiprinajumi",
    row: 276,
    block: "ugunsdrosa_luka",
    name: "Stiprinājumi",
    blockTotal: (c) => total(c.span('ugunsdrosa_luka.stiprinajumi', 'ugunsdrosa_luka.stiprinajumi', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),

  // ---- Sniega un ledus kausēšanas kabeļa montāža, m ----
  line({
    id: "sniega_un_ledus_kausesanas_kabel.snow_melt_kit_1_label",
    row: 277,
    block: "sniega_un_ledus_kausesanas_kabel",
    name: "",
    nameFrom: "input:snow_melt_kit_1_label",
    unit: "kpl",
    laborUnit: "m",
    param: (c) => c.inp.snow_melt_kit_1_price,
    qty: (c) => c.inp.snow_melt_kit_1_length_m,
    reserve: 1.2,
    qtyRes: (c) => c.this.param*c.this.reserve,
    unitPrice: 1,
    hoursPerUnit: (c) => c.norm('ledus_kausesanas_k.kabela_instalacija_ar_stiprinajumiem_mon'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockHours: (c) => c.this.hours,
    blockTotal: (c) => total(c.span('sniega_un_ledus_kausesanas_kabel.snow_melt_kit_1_label', 'sniega_un_ledus_kausesanas_kabel.snow_melt_kit_1_label', 'blockMaterials', 'blockLabor')),
    tools: ["Kabeļu instalācijas materiāli"],
  }),

  // ---- Sniega un ledus kausēšanas kabeļa montāža, m ----
  line({
    id: "sniega_un_ledus_kausesanas_kabel_2.snow_melt_kit_2_label",
    row: 278,
    block: "sniega_un_ledus_kausesanas_kabel_2",
    name: "",
    nameFrom: "input:snow_melt_kit_2_label",
    unit: "kpl",
    laborUnit: "m",
    param: (c) => c.inp.snow_melt_kit_2_price,
    qty: (c) => c.inp.snow_melt_kit_2_length_m,
    reserve: 1.2,
    qtyRes: (c) => c.this.param*c.this.reserve,
    unitPrice: 1,
    hoursPerUnit: (c) => c.norm('ledus_kausesanas_k.kabela_instalacija_ar_stiprinajumiem_mon'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockHours: (c) => c.this.hours,
    blockTotal: (c) => total(c.span('sniega_un_ledus_kausesanas_kabel_2.snow_melt_kit_2_label', 'sniega_un_ledus_kausesanas_kabel_2.snow_melt_kit_2_label', 'blockMaterials', 'blockLabor')),
    tools: ["Kabeļu instalācijas materiāli"],
  }),

  // ---- Sniega un ledus kausēšanas kabeļa montāža, m ----
  line({
    id: "sniega_un_ledus_kausesanas_kabel_3.snow_melt_kit_3_label",
    row: 279,
    block: "sniega_un_ledus_kausesanas_kabel_3",
    name: "",
    nameFrom: "input:snow_melt_kit_3_label",
    unit: "kpl",
    laborUnit: "m",
    param: (c) => c.inp.snow_melt_kit_3_length_m,
    qty: (c) => c.inp.snow_melt_kit_3_price,
    reserve: 1.2,
    unitPrice: 1,
    hoursPerUnit: (c) => c.norm('ledus_kausesanas_k.kabela_instalacija_ar_stiprinajumiem_mon'),
    hours: (c) => c.this.hoursPerUnit*c.this.param,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.this.param,
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockHours: (c) => c.this.hours,
    blockTotal: (c) => total(c.span('sniega_un_ledus_kausesanas_kabel_3.snow_melt_kit_3_label', 'sniega_un_ledus_kausesanas_kabel_3.snow_melt_kit_3_label', 'blockMaterials', 'blockLabor')),
    tools: ["Kabeļu instalācijas materiāli"],
  }),

  // ---- in.electrical_install_label ----
  line({
    id: "electrical_install_label.electrical_install_label",
    row: 280,
    block: "electrical_install_label",
    name: "",
    nameFrom: "input:electrical_install_label",
    unit: "kpl",
    qty: (c) => c.inp.electrical_install_price,
    reserve: 1.2,
    unitPrice: 1,
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockHours: (c) => c.this.hours,
    blockTotal: (c) => total(c.span('electrical_install_label.electrical_install_label', 'electrical_install_label.electrical_install_label', 'blockMaterials', 'blockLabor')),
    blank: ["hours"],
  }),
];
