/**
 * Standing seam covering.
 *
 * Generated from the estimator workbook (Tāme rows 118-127) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Valcprofils Rukki, m2 ----
  line({
    id: "valcprofils_rukki.valcprofils_rukki",
    row: 118,
    block: "valcprofils_rukki",
    name: "Valcprofils Rukki",
    unit: "m2",
    laborUnit: "m2",
    note: "Tīrā platība",
    qty: (c) => c.inp.seam_rukki_m2,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('valcprofils_rukki'),
    hoursPerUnit: (c) => c.norm('valcprofils.valcprofils_rukki_klemmeri_aizvalcesana'),
    blockMaterials: (c) => total(c.span('valcprofils_rukki.valcprofils_rukki', 'valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2', 'materials')),
    blockLabor: (c) => total(c.span('valcprofils_rukki.valcprofils_rukki', 'valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2', 'labor')),
    blockHours: (c) => total(c.span('valcprofils_rukki.valcprofils_rukki', 'valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2', 'hours')),
    blockTotal: (c) => total(c.span('valcprofils_rukki.valcprofils_rukki', 'valcprofils_rukki.valcprofils_rukki', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcprofils_rukki"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts", "Aizvalcētājs"],
  }),
  line({
    id: "valcprofils_rukki.klemmeri_parastie_3gb_m",
    row: 119,
    block: "valcprofils_rukki",
    name: "Klemmeri parastie 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => ceilUp(c.line('valcprofils_rukki.valcprofils_rukki').qty/0.55*c.this.param, 0),
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('klemmeri'),
    blockTotal: (c) => total(c.span('valcprofils_rukki.klemmeri_parastie_3gb_m', 'valcprofils_rukki.klemmeri_parastie_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "valcprofils_rukki.klemmeri_slidosie_50_ja_loksnes_garakas",
    row: 120,
    block: "valcprofils_rukki",
    name: "Klemmeri, Slīdošie 50%  (Ja loksnes garākas par 6.5m)",
    unit: "gb",
    param: (c) => c.inp.sliding_clips_share,
    qty: (c) => c.this.param*c.line('valcprofils_rukki.klemmeri_parastie_3gb_m').qty,
    reserve: 1,
    unitPrice: (c) => c.price('klemmeri_slidosie'),
    blockTotal: (c) => total(c.span('valcprofils_rukki.klemmeri_slidosie_50_ja_loksnes_garakas', 'valcprofils_rukki.klemmeri_slidosie_50_ja_loksnes_garakas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri_slidosie"},
    blank: ["hours"],
  }),
  line({
    id: "valcprofils_rukki.klemmeru_skruves_4_5x25_2gb_klemmeris",
    row: 121,
    block: "valcprofils_rukki",
    name: "Klemmeru skrūves 4.5x25 2gb/klemmeris",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*c.line('valcprofils_rukki.klemmeri_parastie_3gb_m').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('valcprofils_rukki.klemmeru_skruves_4_5x25_2gb_klemmeris', 'valcprofils_rukki.klemmeru_skruves_4_5x25_2gb_klemmeris', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
  }),
  line({
    id: "valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2",
    row: 122,
    block: "valcprofils_rukki",
    name: "Valcgēls, ja slīpums zem 18 grādiem, 1gb/25m bāņu garums",
    unit: "gb",
    laborUnit: "gb",
    param: (c) => if_(c.inp.roof_slope_deg<18.5, 1, 0),
    qty: (c) => c.line('valcprofils_rukki.valcprofils_rukki').qty/0.55*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve/25, 0),
    unitPrice: (c) => c.price('valcgels'),
    hoursPerUnit: (c) => c.norm('valcprofils.valcgels_ja_slipums_zem_18_gradiem_1gb_2'),
    hours: (c) => c.this.qtyRes*c.this.hoursPerUnit,
    blockTotal: (c) => total(c.span('valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2', 'valcprofils_rukki.valcgels_ja_slipums_zem_18_gradiem_1gb_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcgels"},
    tools: ["Hermētiķa pistole"],
  }),

  // ---- Valcprofils Zn, m2 ----
  line({
    id: "valcprofils_zn.valcprofils_zn",
    row: 123,
    block: "valcprofils_zn",
    name: "Valcprofils Zn",
    unit: "m2",
    laborUnit: "m2",
    note: "Tīrā platība",
    qty: (c) => c.inp.seam_zn_m2,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('valcprofils_zn'),
    hoursPerUnit: (c) => c.norm('valcprofils.valcprofils_rukki_klemmeri_aizvalcesana'),
    blockMaterials: (c) => total(c.span('valcprofils_zn.valcprofils_zn', 'valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem', 'materials')),
    blockLabor: (c) => total(c.span('valcprofils_zn.valcprofils_zn', 'valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem', 'labor')),
    blockHours: (c) => total(c.span('valcprofils_zn.valcprofils_zn', 'valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem', 'hours')),
    blockTotal: (c) => total(c.span('valcprofils_zn.valcprofils_zn', 'valcprofils_zn.valcprofils_zn', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcprofils_zn"},
    tools: ["Skārdnieka instrumenti", "Striķis un krīts", "Aizvalcētājs"],
  }),
  line({
    id: "valcprofils_zn.klemmeri_parastie_3gb_m",
    row: 124,
    block: "valcprofils_zn",
    name: "Klemmeri parastie 3gb/m",
    unit: "gb",
    param: 3,
    qty: (c) => ceilUp(c.line('valcprofils_zn.valcprofils_zn').qty/0.55*c.this.param, 0),
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('klemmeri'),
    blockTotal: (c) => total(c.span('valcprofils_zn.klemmeri_parastie_3gb_m', 'valcprofils_zn.klemmeri_parastie_3gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri"},
    blank: ["hours"],
    tools: ["Skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "valcprofils_zn.klemmeri_slidosie_50_ja_loksnes_garakas",
    row: 125,
    block: "valcprofils_zn",
    name: "Klemmeri, Slīdošie 50%  (Ja loksnes garākas par 6.5m)",
    unit: "gb",
    param: (c) => c.inp.sliding_clips_share,
    qty: (c) => c.this.param*c.line('valcprofils_zn.klemmeri_parastie_3gb_m').qty,
    reserve: 1,
    unitPrice: (c) => c.price('klemmeri_slidosie'),
    blockTotal: (c) => total(c.span('valcprofils_zn.klemmeri_slidosie_50_ja_loksnes_garakas', 'valcprofils_zn.klemmeri_slidosie_50_ja_loksnes_garakas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeri_slidosie"},
    blank: ["hours"],
  }),
  line({
    id: "valcprofils_zn.klemmeru_skruves_4_5x25_2gb_klemmeris",
    row: 126,
    block: "valcprofils_zn",
    name: "Klemmeru skrūves 4.5x25 2gb/klemmeris",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*c.line('valcprofils_zn.klemmeri_parastie_3gb_m').qty,
    reserve: 1.15,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('klemmeru_skruves_pz_4_5x25'),
    blockTotal: (c) => total(c.span('valcprofils_zn.klemmeru_skruves_4_5x25_2gb_klemmeris', 'valcprofils_zn.klemmeru_skruves_4_5x25_2gb_klemmeris', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "klemmeru_skruves_pz_4_5x25"},
    blank: ["hours"],
  }),
  line({
    id: "valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem",
    row: 127,
    block: "valcprofils_zn",
    name: "Valcgēls, ja slīpums zem 18 grādiem",
    unit: "gb",
    laborUnit: "gb",
    param: (c) => if_(c.inp.roof_slope_deg<18.5, 1, 0),
    qty: (c) => c.line('valcprofils_zn.valcprofils_zn').qty/0.55*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve/25, 0),
    unitPrice: (c) => c.price('valcgels'),
    hoursPerUnit: (c) => c.norm('valcprofils.valcgels_ja_slipums_zem_18_gradiem_1gb_2'),
    hours: (c) => c.this.hoursPerUnit*c.this.qtyRes,
    blockTotal: (c) => total(c.span('valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem', 'valcprofils_zn.valcgels_ja_slipums_zem_18_gradiem', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "valcgels"},
    tools: ["Hermētiķa pistole"],
  }),
];
