/**
 * Waste, site setup, scaffold, transport, lodging, insurance, totals.
 *
 * Generated from the estimator workbook (Tāme rows 309-342) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Atkritumu apsaimniekošana ----
  line({
    id: "atkritumu_apsaimniekosana.buvgruz_konteiners_8m3",
    row: 309,
    block: "atkritumu_apsaimniekosana",
    name: "Būvgruž konteiners 8m3",
    unit: "gb",
    qty: (c) => c.inp.site_skip_8m3_count,
    reserve: 1,
    unitPrice: (c) => c.price('buvgruzu_konteiners_8m3'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.buvgruzu_konteinera_8m3_piebildisana_pie'),
    blockMaterials: (c) => total(c.span('atkritumu_apsaimniekosana.buvgruz_konteiners_8m3', 'atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2', 'materials')),
    blockLabor: (c) => total(c.span('atkritumu_apsaimniekosana.buvgruz_konteiners_8m3', 'atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2', 'labor')),
    blockHours: (c) => total(c.span('atkritumu_apsaimniekosana.buvgruz_konteiners_8m3', 'atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2', 'hours')),
    blockTotal: (c) => total(c.span('atkritumu_apsaimniekosana.buvgruz_konteiners_8m3', 'atkritumu_apsaimniekosana.buvgruz_konteiners_8m3', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "buvgruzu_konteiners_8m3"},
    tools: ["Ķerra", "Lāpsta"],
  }),
  line({
    id: "atkritumu_apsaimniekosana.objekta_satirisana_un_sakartosana_buvgru",
    row: 310,
    block: "atkritumu_apsaimniekosana",
    name: "Objekta satīrīšana un sakārtošana, būvgružu maisi 0.5gb/1m2",
    unit: "gb",
    laborUnit: "gb",
    param: 0.15,
    qty: (c) => total([c.inp.demo_slate_m2, c.inp.demo_standing_seam_m2, c.inp.demo_sheet_metal_m2, c.inp.demo_shingles_m2, c.inp.demo_tiles_m2, c.inp.demo_battens_m2, c.inp.demo_structure_m2])*c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('buvgruzu_maisi_polipropilena_maiss_55x100cm'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.objekta_satirisana_pec_darbiem_satirisan'),
    blockTotal: (c) => total(c.span('atkritumu_apsaimniekosana.objekta_satirisana_un_sakartosana_buvgru', 'atkritumu_apsaimniekosana.objekta_satirisana_un_sakartosana_buvgru', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "buvgruzu_maisi_polipropilena_maiss_55x100cm"},
    tools: ["Būgružu maisi", "Slota un šaufele", "Lāpsta"],
  }),
  line({
    id: "atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2",
    row: 311,
    block: "atkritumu_apsaimniekosana",
    name: "Šīfera utilizācija ar izvešanu, m2",
    unit: "m2",
    qty: (c) => c.inp.demo_slate_m2,
    reserve: 1.1,
    unitPrice: (c) => c.price('sifera_utilizacija_eur_m2'),
    blockTotal: (c) => total(c.span('atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2', 'atkritumu_apsaimniekosana.sifera_utilizacija_ar_izvesanu_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sifera_utilizacija_eur_m2"},
    tools: ["BigBag maisi", "Būgružu maisi", "Slota un šaufele", "Lāpsta"],
  }),

  // ---- Būvobjekta iekārtošana ----
  line({
    id: "buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko",
    row: 312,
    block: "buvobjekta_iekartosana",
    name: "Koka aizsardzības materiālu komplekts, kokmateriāli, gofrēta caurule, stiprinājumi",
    unit: "gb",
    laborUnit: "gb",
    note: "Ar dēļiem montēti uz gofras",
    qty: (c) => c.inp.site_protected_trees_count,
    reserve: 1,
    unitPrice: (c) => c.price('koku_aizsardzibas_komplekts_kokmateriali_un'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.koka_aizsardziba_ar_deliem_monteti_uz_go'),
    blockMaterials: (c) => total(c.span('buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko', 'buvobjekta_iekartosana.aizsardzibas_zimes', 'materials')),
    blockLabor: (c) => total(c.span('buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko', 'buvobjekta_iekartosana.aizsardzibas_zimes', 'labor')),
    blockHours: (c) => total(c.span('buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko', 'buvobjekta_iekartosana.aizsardzibas_zimes', 'hours')),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko', 'buvobjekta_iekartosana.koka_aizsardzibas_materialu_komplekts_ko', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koku_aizsardzibas_komplekts_kokmateriali_un"},
    tools: ["Skrūvmašīna un uzgaļi", "Nazis un asmeņi"],
  }),
  line({
    id: "buvobjekta_iekartosana.koka_aizsardzibas_specialists_arborists",
    row: 313,
    block: "buvobjekta_iekartosana",
    name: "Koka aizsardzības speciālists, Arborists  ETT vai ETW kvalifikāciju, 5 koki 1gb",
    unit: "gb",
    param: 5,
    qty: (c) => ceilUp(c.inp.site_protected_trees_count/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('koku_aizsardzibas_specialists_atzinuma_akti'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.koka_aizsardzibas_specialists_arborists', 'buvobjekta_iekartosana.koka_aizsardzibas_specialists_arborists', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koku_aizsardzibas_specialists_atzinuma_akti"},
  }),
  line({
    id: "buvobjekta_iekartosana.buvtafele",
    row: 314,
    block: "buvobjekta_iekartosana",
    name: "Būvtāfele",
    unit: "gb",
    qty: (c) => c.inp.site_board_count,
    reserve: 1,
    unitPrice: (c) => c.price('buvtafele'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.buvtafele_montaza'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.buvtafele', 'buvobjekta_iekartosana.buvtafele', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "buvtafele"},
    tools: ["Savilcēji", "Nazis un asmeņi"],
  }),
  line({
    id: "buvobjekta_iekartosana.bio_toalete_menesi",
    row: 315,
    block: "buvobjekta_iekartosana",
    name: "BIO toalete mēneši",
    unit: "gb",
    qty: (c) => c.inp.site_toilet_months,
    reserve: 1,
    unitPrice: (c) => c.price('toaletes_noma_apkalposana_menesi'),
    total: (c) => total(c.this.materials+c.this.labor),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.bio_toalete_menesi', 'buvobjekta_iekartosana.bio_toalete_menesi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "toaletes_noma_apkalposana_menesi"},
    blank: ["hours", "rate", "labor", "hoursMarkedPerUnit", "laborMarked"],
    tools: ["Toaletes papīrs"],
  }),
  line({
    id: "buvobjekta_iekartosana.iebrauktuves_sagatvosana_gumijas_paklaji",
    row: 316,
    block: "buvobjekta_iekartosana",
    name: "Iebrauktuves sagatvošana, Gumijas paklāji, noma",
    unit: "gb",
    param: (c) => c.inp.site_rubber_mats_days,
    qty: (c) => c.inp.site_rubber_mats_count,
    reserve: 1,
    unitPrice: (c) => c.price('iebrauktuves_sagatvosana_gumijas_paklaji_nom'),
    materials: (c) => c.this.unitPrice*c.this.qtyRes*c.this.param,
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.iebrauktuves_sagatvosana_gumijas_paklaji', 'buvobjekta_iekartosana.iebrauktuves_sagatvosana_gumijas_paklaji', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "iebrauktuves_sagatvosana_gumijas_paklaji_nom"},
  }),
  line({
    id: "buvobjekta_iekartosana.materialu_novietnes_sagatvosana_tenta_pa",
    row: 317,
    block: "buvobjekta_iekartosana",
    name: "Materiālu novietnes sagatvošana, tenta pārklāji",
    unit: "gb",
    qty: (c) => c.inp.site_tarps_count,
    reserve: 1,
    unitPrice: (c) => c.price('materialu_parklajs_120g_m2_4x6m'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.materialu_novietnes_sagatvosana_tenta_pa', 'buvobjekta_iekartosana.materialu_novietnes_sagatvosana_tenta_pa', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "materialu_parklajs_120g_m2_4x6m"},
  }),
  line({
    id: "buvobjekta_iekartosana.ugunsdzesibas_inventars_gb",
    row: 318,
    block: "buvobjekta_iekartosana",
    name: "Ugunsdzēsības inventārs gb",
    unit: "gb",
    qty: (c) => c.inp.site_fire_kit_count,
    reserve: 1,
    unitPrice: (c) => c.price('ugunsdzesibas_inventars_ik_pa_20m'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.ugunsdzesibas_inventars_gb', 'buvobjekta_iekartosana.ugunsdzesibas_inventars_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ugunsdzesibas_inventars_ik_pa_20m"},
  }),
  line({
    id: "buvobjekta_iekartosana.parvietojams_konteiners_stradniekiem_un",
    row: 319,
    block: "buvobjekta_iekartosana",
    name: "Pārvietojams konteiners strādniekiem un inventāram 6x2.4m, 1 gab nomas ilgums mēn",
    unit: "gb",
    qty: (c) => c.inp.site_container_months,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('parvietojams_konteiners_stradniekiem_un_inve'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.parvietojams_konteiners_stradniekiem_un', 'buvobjekta_iekartosana.parvietojams_konteiners_stradniekiem_un', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "parvietojams_konteiners_stradniekiem_un_inve"},
  }),
  line({
    id: "buvobjekta_iekartosana.parvietojama_konteinera_piegade",
    row: 320,
    block: "buvobjekta_iekartosana",
    name: "Pārvietojamā konteinera piegāde",
    unit: "km",
    qty: 0,
    reserve: 1.1,
    unitPrice: (c) => c.price('konteinera_piegade_km'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.parvietojama_konteinera_piegade', 'buvobjekta_iekartosana.parvietojama_konteinera_piegade', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "konteinera_piegade_km"},
    blank: ["hours", "rate", "labor", "hoursMarkedPerUnit", "laborMarked", "total"],
  }),
  line({
    id: "buvobjekta_iekartosana.darba_galds",
    row: 321,
    block: "buvobjekta_iekartosana",
    name: "Darba galds",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.site_workbench_count,
    reserve: 1,
    unitPrice: (c) => c.price('darba_galds_kokmateriali_un_stiprinajumi'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.darba_galds_izveide'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.darba_galds', 'buvobjekta_iekartosana.darba_galds', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "darba_galds_kokmateriali_un_stiprinajumi"},
    tools: ["Skrūvmašīna un uzgaļi", "Cirkulārais zāgis"],
  }),
  line({
    id: "buvobjekta_iekartosana.apgaismojums_gb",
    row: 322,
    block: "buvobjekta_iekartosana",
    name: "Apgaismojums, gb",
    unit: "gb",
    laborUnit: "gb",
    qty: (c) => c.inp.site_lighting_count,
    reserve: 1,
    unitPrice: (c) => c.price('apgaismojums_gb'),
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.apgaismojums_uzstadisana'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.apgaismojums_gb', 'buvobjekta_iekartosana.apgaismojums_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "apgaismojums_gb"},
    tools: ["Savilcēji", "Nazis un asmeņi"],
  }),
  line({
    id: "buvobjekta_iekartosana.aizsardzibas_zimes",
    row: 323,
    block: "buvobjekta_iekartosana",
    name: "Aizsardzības zīmes",
    unit: "gb",
    note: "darbs augstumā, troksnis, vibrācijas, sprādziena bīstamība, aizdegšanās, aizķeršanās, nokrišana, sasitumi, putekļi.\n",
    qty: (c) => c.inp.site_safety_signs_count,
    reserve: 1,
    unitPrice: (c) => c.price('aizsardzibas_zimes'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.aizsardzibas_zimes', 'buvobjekta_iekartosana.aizsardzibas_zimes', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "aizsardzibas_zimes"},
  }),
  line({
    id: "buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena",
    row: 324,
    block: "buvobjekta_iekartosana",
    name: "Nožogojums, 2x3.5m gb, noma, dienā",
    unit: "m",
    laborUnit: "m",
    qty: (c) => ceilUp(c.inp.site_fence_length_m/3.5, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('nozogojums_2x3_5m_gb_noma_diena'),
    materials: (c) => c.this.unitPrice*c.this.qtyRes*c.inp.site_fence_rent_days,
    hoursPerUnit: (c) => c.norm('buvobjekta_iekarto.nozogojums_montaza_ar_sietu'),
    blockMaterials: (c) => total(c.span('buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena', 'buvobjekta_iekartosana.aizsargtikls_eur_m2', 'materials')),
    blockLabor: (c) => total(c.span('buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena', 'buvobjekta_iekartosana.aizsargtikls_eur_m2', 'labor')),
    blockHours: (c) => total(c.span('buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena', 'buvobjekta_iekartosana.aizsargtikls_eur_m2', 'hours')),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena', 'buvobjekta_iekartosana.nozogojums_2x3_5m_gb_noma_diena', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nozogojums_2x3_5m_gb_noma_diena"},
    tools: ["Savilcēji", "Nazis un asmeņi"],
  }),
  line({
    id: "buvobjekta_iekartosana.aizsargtikls_eur_m2",
    row: 325,
    block: "buvobjekta_iekartosana",
    name: "Aizsargtīkls EUR/m2",
    unit: "m2",
    qty: (c) => c.inp.site_fence_length_m*2,
    reserve: 1.1,
    unitPrice: (c) => c.price('aizsargtikls_eur_m2'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.aizsargtikls_eur_m2', 'buvobjekta_iekartosana.aizsargtikls_eur_m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "aizsargtikls_eur_m2"},
    blank: ["labor"],
  }),
  line({
    id: "buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits",
    row: 326,
    block: "buvobjekta_iekartosana",
    name: "Sastatnes noma EUR/m2, mēnešu skaits",
    unit: "m2",
    qty: (c) => c.inp.site_scaffold_area_m2,
    reserve: 1.05,
    unitPrice: (c) => c.price('sastatnes_noma_eur_m2_men'),
    materials: (c) => c.this.unitPrice*c.this.qtyRes*c.inp.site_scaffold_rent_months,
    blockMaterials: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits', 'buvobjekta_iekartosana.celtniecibas_lifts', 'materials')),
    blockLabor: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits', 'buvobjekta_iekartosana.celtniecibas_lifts', 'labor')),
    blockHours: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits', 'buvobjekta_iekartosana.gajeju_tunela_izbuve_m', 'hours')),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits', 'buvobjekta_iekartosana.sastatnes_noma_eur_m2_menesu_skaits', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sastatnes_noma_eur_m2_men"},
    blank: ["labor"],
  }),
  line({
    id: "buvobjekta_iekartosana.sastatnes_aizsargtikls",
    row: 327,
    block: "buvobjekta_iekartosana",
    name: "Sastatnes aizsargtīkls",
    unit: "m2",
    qty: (c) => c.inp.site_scaffold_area_m2,
    reserve: 1.5,
    unitPrice: (c) => c.price('sastatnes_aizsargtikls_m2_eur'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_aizsargtikls', 'buvobjekta_iekartosana.sastatnes_aizsargtikls', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sastatnes_aizsargtikls_m2_eur"},
    blank: ["labor"],
    tools: ["Savilcēji", "Nazis un asmeņi"],
  }),
  line({
    id: "buvobjekta_iekartosana.sastatnes_montaza_pakalpojums",
    row: 328,
    block: "buvobjekta_iekartosana",
    name: "Sastatnes montāža, pakalpojums",
    unit: "m2",
    qty: (c) => c.inp.site_scaffold_area_m2,
    reserve: 1,
    unitPrice: (c) => c.price('sastatnes_montaza_pakalpojums'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_montaza_pakalpojums', 'buvobjekta_iekartosana.sastatnes_montaza_pakalpojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sastatnes_montaza_pakalpojums"},
    blank: ["labor"],
  }),
  line({
    id: "buvobjekta_iekartosana.sastatnes_demontaza_pakalpojums",
    row: 329,
    block: "buvobjekta_iekartosana",
    name: "Sastatnes demontāža, pakalpojums",
    unit: "m2",
    qty: (c) => c.inp.site_scaffold_area_m2,
    reserve: 1,
    unitPrice: (c) => c.price('sastatnes_demontaza_pakalpojums'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_demontaza_pakalpojums', 'buvobjekta_iekartosana.sastatnes_demontaza_pakalpojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sastatnes_demontaza_pakalpojums"},
    blank: ["labor"],
  }),
  line({
    id: "buvobjekta_iekartosana.sastatnes_piegade_pakalpojums",
    row: 330,
    block: "buvobjekta_iekartosana",
    name: "Sastatnes piegāde, pakalpojums",
    unit: "m2",
    qty: (c) => c.inp.site_scaffold_area_m2,
    reserve: 1.1,
    unitPrice: (c) => c.price('sastatnes_piegade_pakalpojums'),
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.sastatnes_piegade_pakalpojums', 'buvobjekta_iekartosana.sastatnes_piegade_pakalpojums', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "sastatnes_piegade_pakalpojums"},
    blank: ["labor"],
  }),
  line({
    id: "buvobjekta_iekartosana.gajeju_tunela_izbuve_m",
    row: 331,
    block: "buvobjekta_iekartosana",
    name: "Gājēju tuneļa izbūve, m",
    unit: "m",
    note: " Fasāžu sastatņu/stalažu uzstādīšana un to norobežošana, saskaņā ar MK noteiktumiem Nr.92 ",
    reserve: 1,
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.gajeju_tunela_izbuve_m', 'buvobjekta_iekartosana.gajeju_tunela_izbuve_m', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "buvobjekta_iekartosana.celtniecibas_lifts",
    row: 332,
    block: "buvobjekta_iekartosana",
    name: "Celtniecības lifts",
    unit: "gb",
    blockTotal: (c) => total(c.span('buvobjekta_iekartosana.celtniecibas_lifts', 'buvobjekta_iekartosana.celtniecibas_lifts', 'blockMaterials', 'blockLabor')),
  }),

  // ---- Transporta izmaksas  ----
  line({
    id: "transporta_izmaksas.skarda_piegade_1gb_400m2",
    row: 333,
    block: "transporta_izmaksas",
    name: "Skārda piegāde 1gb/ 400m2",
    unit: "km",
    param: 400,
    qty: (c) => ceilUp(total([c.inp.seam_zn_m2, c.inp.seam_rukki_m2])/c.this.param, 0)*c.inp.distance_km*2,
    reserve: 1.2,
    unitPrice: (c) => c.price('manipulatora_transporta_pakalpojumi_eur_km'),
    blockMaterials: (c) => total(c.span('transporta_izmaksas.skarda_piegade_1gb_400m2', 'transporta_izmaksas.citu_mat_sagades_izmaksas_1_no_kopejas_m', 'materials')),
    blockLabor: (c) => total(c.span('transporta_izmaksas.skarda_piegade_1gb_400m2', 'transporta_izmaksas.citu_mat_sagades_izmaksas_1_no_kopejas_m', 'labor')),
    blockTotal: (c) => total(c.span('transporta_izmaksas.skarda_piegade_1gb_400m2', 'transporta_izmaksas.skarda_piegade_1gb_400m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "manipulatora_transporta_pakalpojumi_eur_km"},
    blank: ["hours", "labor"],
    tools: ["Rācija", "Štropes"],
  }),
  line({
    id: "transporta_izmaksas.latojuma_piegade_1gb_400m2",
    row: 334,
    block: "transporta_izmaksas",
    name: "Latojuma piegāde 1gb/400m2",
    unit: "km",
    param: 400,
    qty: (c) => ceilUp(c.inp.batten_area_m2/c.this.param, 0)*c.inp.distance_km*2,
    reserve: 1.2,
    unitPrice: (c) => c.price('manipulatora_transporta_pakalpojumi_eur_km'),
    blockTotal: (c) => total(c.span('transporta_izmaksas.latojuma_piegade_1gb_400m2', 'transporta_izmaksas.latojuma_piegade_1gb_400m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "manipulatora_transporta_pakalpojumi_eur_km"},
    blank: ["hours", "labor"],
    tools: ["Rācija", "Štropes"],
  }),
  line({
    id: "transporta_izmaksas.transports_uz_objektu",
    row: 335,
    block: "transporta_izmaksas",
    name: "Transports uz objektu",
    unit: "km",
    qty: (c) => iferror(() => ((c.inp.distance_km*2*(c.line('totals.all').hours/8/c.inp.crew_size))), 0),
    reserve: 1.2,
    unitPrice: (c) => c.price('transports_uz_objektu_eur_km'),
    blockTotal: (c) => total(c.span('transporta_izmaksas.transports_uz_objektu', 'transporta_izmaksas.transports_uz_objektu', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "transports_uz_objektu_eur_km"},
    blank: ["hours", "labor"],
  }),
  line({
    id: "transporta_izmaksas.citu_mat_sagades_izmaksas_1_no_kopejas_m",
    row: 336,
    block: "transporta_izmaksas",
    name: "Citu Mat Sagādes izmaksas 1% no kopējās materiālu summas",
    unit: "%",
    param: 0.01,
    qty: (c) => total(c.span('valcprofils_rukki.valcprofils_rukki', 'buvobjekta_iekartosana.celtniecibas_lifts', 'materials')),
    reserve: 1,
    materials: (c) => c.this.param*c.this.qtyRes,
    blockTotal: (c) => total(c.span('transporta_izmaksas.citu_mat_sagades_izmaksas_1_no_kopejas_m', 'transporta_izmaksas.citu_mat_sagades_izmaksas_1_no_kopejas_m', 'blockMaterials', 'blockLabor')),
    blank: ["hours", "labor"],
  }),

  // ---- Citi ----
  line({
    id: "citi.komandejuma_naktsmitnes_izmaksas",
    row: 338,
    block: "citi",
    name: "Komandējuma naktsmītnes izmaksas",
    unit: "gb",
    qty: (c) => c.inp.lodging_nights*c.inp.lodging_people,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('dzivosana_nakts_1_cilveks_lv'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('citi.komandejuma_naktsmitnes_izmaksas', 'citi.komandejuma_naktsmitnes_izmaksas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dzivosana_nakts_1_cilveks_lv"},
    blank: ["hours", "labor"],
  }),
  line({
    id: "citi.buvdarbu_vaditajs",
    row: 339,
    block: "citi",
    name: "Būvdarbu vadītājs",
    unit: "mēn",
    qty: (c) => c.inp.site_manager_months,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('buvdarbu_vaditaja_izmaksas_1men'),
    blockMaterials: (c) => c.this.materials,
    blockLabor: (c) => c.this.labor,
    blockTotal: (c) => total(c.span('citi.buvdarbu_vaditajs', 'citi.buvdarbu_vaditajs', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "buvdarbu_vaditaja_izmaksas_1men"},
    blank: ["hours", "labor"],
  }),
  line({
    id: "citi.apdrosinasana",
    row: 340,
    block: "citi",
    name: "Apdrošināšana",
    unit: "kpl",
    param: (c) => c.inp.insurance_rate,
    qty: (c) => c.this.param*(total(c.span('valcprofils_rukki.valcprofils_rukki', 'buvobjekta_iekartosana.celtniecibas_lifts', 'materials'))+total(c.line('totals.all').labor)),
    reserve: 1,
    unitPrice: 1,
    blockMaterials: (c) => c.this.materials,
    blockTotal: (c) => total(c.span('citi.apdrosinasana', 'citi.apdrosinasana', 'blockMaterials', 'blockLabor')),
    blank: ["hours", "labor"],
  }),

  // ---- Kopā: ----
  line({
    id: "totals.all",
    row: 342,
    block: "kopa",
    name: null,
    materials: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'citi.apdrosinasana', 'materials')),
    hours: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'citi.apdrosinasana', 'hours')),
    labor: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'citi.apdrosinasana', 'labor')),
    laborMarked: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'citi.apdrosinasana', 'laborMarked')),
    total: (c) => total(c.span('demontaza_ar_nocelsanu.sifera_demontaza_12kg_m2', 'citi.apdrosinasana', 'total')),
    blockTotal: (c) => total(c.span('totals.all', 'totals.all', 'blockMaterials', 'blockLabor')),
    blank: ["qtyRes", "rate", "hoursMarkedPerUnit"],
  }),
];
