/**
 * Soffit box and painting.
 *
 * Generated from the estimator workbook (Tāme rows 214-251) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Vēja kastes izbūve, m2 ----
  line({
    id: "veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums",
    row: 214,
    block: "veja_kastes_izbuve",
    name: "Vēja kastes karkas, solis 60cm, platums",
    laborUnit: "m",
    param: (c) => c.inp.soffit_width_m,
    qty: (c) => c.inp.soffit_area_m2,
    hoursPerUnit: (c) => c.norm('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_50x50_brus'),
    hours: (c) => c.this.hoursPerUnit*c.inp.soffit_length_m,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.soffit_length_m,
    blockMaterials: (c) => total(c.span('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums', 'veja_kastes_izbuve.spainitis_2', 'materials')),
    blockLabor: (c) => total(c.span('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums', 'veja_kastes_izbuve.spainitis_2', 'labor')),
    blockHours: (c) => total(c.span('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums', 'veja_kastes_izbuve.spainitis_2', 'hours')),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums', 'veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "veja_kastes_izbuve.n50x50_brusas_platums_x2_solis_60",
    row: 215,
    block: "veja_kastes_izbuve",
    name: "50x50 brusas platums x2, solis 60",
    unit: "m3",
    param: (c) => c.line('veja_kastes_izbuve.veja_kastes_karkas_solis_60cm_platums').param*2,
    qty: (c) => ceilUp(c.inp.soffit_length_m/0.6*c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.05*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.n50x50_brusas_platums_x2_solis_60', 'veja_kastes_izbuve.n50x50_brusas_platums_x2_solis_60', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    blank: ["hours"],
    tools: ["Cirkulārais zāģis", "Zobenzāģis", "līmeņrādis", "Striķis un krīts"],
  }),
  line({
    id: "veja_kastes_izbuve.kokskruves_5x80_6gb_1gb",
    row: 216,
    block: "veja_kastes_izbuve",
    name: "Kokskrūves 5x80, 6gb/ 1gb",
    unit: "gb",
    param: 6,
    qty: (c) => ceilUp(c.inp.soffit_length_m/0.6*c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x80'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.kokskruves_5x80_6gb_1gb', 'veja_kastes_izbuve.kokskruves_5x80_6gb_1gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x80"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "veja_kastes_izbuve.kokskruves_5x120_2gb_1gb",
    row: 217,
    block: "veja_kastes_izbuve",
    name: "Kokskrūves 5x120, 2gb/ 1gb",
    unit: "gb",
    param: 2,
    qty: (c) => ceilUp(c.inp.soffit_length_m/0.6*c.this.param, 0),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_5x120'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.kokskruves_5x120_2gb_1gb', 'veja_kastes_izbuve.kokskruves_5x120_2gb_1gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_5x120"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "veja_kastes_izbuve.lenkis_50x50_0_5gb_gb",
    row: 218,
    block: "veja_kastes_izbuve",
    name: "Leņkis 50x50, 0.5gb / gb",
    unit: "gb",
    param: 0.5,
    qty: (c) => ceilUp(c.inp.soffit_length_m/0.6*c.this.param, 0),
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('stura_lenkis_50x50x40x2mm'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.lenkis_50x50_0_5gb_gb', 'veja_kastes_izbuve.lenkis_50x50_0_5gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "stura_lenkis_50x50x40x2mm"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "veja_kastes_izbuve.kokskruves_4_5x45_6gb_lenkis",
    row: 219,
    block: "veja_kastes_izbuve",
    name: "Kokskrūves 4.5x45, 6gb/leņķis",
    unit: "gb",
    param: 6,
    qty: (c) => c.line('veja_kastes_izbuve.lenkis_50x50_0_5gb_gb').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_4_5x45'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.kokskruves_4_5x45_6gb_lenkis', 'veja_kastes_izbuve.kokskruves_4_5x45_6gb_lenkis', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4_5x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "veja_kastes_izbuve.apdares_deli_ar_vienu_spundi_20x95",
    row: 220,
    block: "veja_kastes_izbuve",
    name: "Apdares dēļi ar vienu spundi, 20x95",
    unit: "m3",
    laborUnit: "m2",
    note: "20x95",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/0.095, 0),
    reserve: 1.2,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.095*0.02,
    unitPrice: (c) => c.price('apdares_deli'),
    hoursPerUnit: (c) => c.norm('veja_kastes_izbuve.apdares_deli_ar_vienu_spundi_20x95_zages'),
    hours: (c) => c.inp.soffit_area_m2*c.this.hoursPerUnit,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.soffit_area_m2,
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.apdares_deli_ar_vienu_spundi_20x95', 'veja_kastes_izbuve.apdares_deli_ar_vienu_spundi_20x95', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "apdares_deli"},
    tools: ["Cirkulārais zāģis", "Zobenzāģis", "līmeņrādis", "Striķis un krīts"],
  }),
  line({
    id: "veja_kastes_izbuve.apdares_delu_skruves_4x45_6gb_m",
    row: 221,
    block: "veja_kastes_izbuve",
    name: "Apdares dēļu skrūves 4x45, 6gb/m",
    unit: "gb",
    param: 6,
    qty: (c) => c.line('veja_kastes_izbuve.apdares_deli_ar_vienu_spundi_20x95').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_4x45'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.apdares_delu_skruves_4x45_6gb_m', 'veja_kastes_izbuve.apdares_delu_skruves_4x45_6gb_m', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi", "Trīstūris"],
  }),
  line({
    id: "veja_kastes_izbuve.koka_fasades_krasa_1_slanis_objekta_40m2",
    row: 222,
    block: "veja_kastes_izbuve",
    name: "Koka fasādes krāsa 1 slānis objektā, 40m2/l",
    unit: "l",
    laborUnit: "m2",
    param: 40,
    qty: (c) => c.inp.soffit_area_m2/c.this.param,
    reserve: 1.1,
    unitPrice: (c) => c.price('koka_fasades_krasa_l'),
    hoursPerUnit: (c) => c.norm('veja_kastes_izbuve.koka_fasades_krasa_1_slanis_objekta_8m2'),
    hours: (c) => c.this.hoursPerUnit*c.inp.soffit_area_m2,
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.soffit_area_m2,
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.koka_fasades_krasa_1_slanis_objekta_40m2', 'veja_kastes_izbuve.koka_fasades_krasa_1_slanis_objekta_40m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_fasades_krasa_l"},
    tools: ["Krāsošanas piederumi", "Lupatas", "Trauki iemērkšanai", "Nazis un asmeņi"],
  }),
  line({
    id: "veja_kastes_izbuve.nosegsanas_pleves_materiali",
    row: 223,
    block: "veja_kastes_izbuve",
    name: "Nosegšanas plēves materiāli",
    unit: "m2",
    laborUnit: "m2",
    note: "1m2-1/m2",
    qty: (c) => c.inp.soffit_area_m2,
    reserve: 1,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    hoursPerUnit: (c) => c.norm('veja_kastes_izbuve.nosegsanas_pleves_materiali_nosegsana'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.nosegsanas_pleves_materiali', 'veja_kastes_izbuve.nosegsanas_pleves_materiali', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
  }),
  line({
    id: "veja_kastes_izbuve.pvc_limlenta_nosegsanai_1gb_10m2",
    row: 224,
    block: "veja_kastes_izbuve",
    name: "PVC līmlenta nosegšanai, 1gb/10m2",
    unit: "gb",
    param: 10,
    qty: (c) => ceilUp(c.inp.soffit_area_m2/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('pvc_limlenta_nosegsanai'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.pvc_limlenta_nosegsanai_1gb_10m2', 'veja_kastes_izbuve.pvc_limlenta_nosegsanai_1gb_10m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_limlenta_nosegsanai"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.ota_akrila_krasai_maza",
    row: 225,
    block: "veja_kastes_izbuve",
    name: "Ota akrila krāsai mazā",
    unit: "gb",
    note: "1gb/ 20m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/20, 0),
    reserve: 1,
    unitPrice: (c) => c.price('ota_akrila_krasai_maza'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.ota_akrila_krasai_maza', 'veja_kastes_izbuve.ota_akrila_krasai_maza', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ota_akrila_krasai_maza"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.ota_akrila_krasai_liela",
    row: 226,
    block: "veja_kastes_izbuve",
    name: "Ota akrila krāsai lielā",
    unit: "gb",
    note: "1gb/ 50m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/50, 0),
    reserve: 1,
    unitPrice: (c) => c.price('ota_akrila_krasai_liela'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.ota_akrila_krasai_liela', 'veja_kastes_izbuve.ota_akrila_krasai_liela', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ota_akrila_krasai_liela"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.rullis_ar_rokturi",
    row: 227,
    block: "veja_kastes_izbuve",
    name: "Rullis ar rokturi",
    unit: "gb",
    note: "1gb/ 50m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/50, 0),
    reserve: 1,
    unitPrice: (c) => c.price('rullis_ar_rokturi'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.rullis_ar_rokturi', 'veja_kastes_izbuve.rullis_ar_rokturi', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "rullis_ar_rokturi"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.vannite",
    row: 228,
    block: "veja_kastes_izbuve",
    name: "Vannīte",
    unit: "gb",
    note: "1gb/ 40m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/40, 0),
    reserve: 1,
    unitPrice: (c) => c.price('vannite'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.vannite', 'veja_kastes_izbuve.vannite', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vannite"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.spainitis",
    row: 229,
    block: "veja_kastes_izbuve",
    name: "Spainītis",
    unit: "gb",
    note: "1gb/ 40m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/40, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spainitis'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.spainitis', 'veja_kastes_izbuve.spainitis', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spainitis"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.koka_fasades_krasa_2_slani_darbnica_6m2",
    row: 230,
    block: "veja_kastes_izbuve",
    name: "Koka fasādes krāsa 2 slāņi darbnīcā, 6m2/l",
    unit: "l",
    laborUnit: "m2",
    param: 6,
    qty: (c) => c.inp.soffit_area_m2/c.this.param,
    reserve: 1.2,
    unitPrice: (c) => c.price('koka_fasades_krasa_l'),
    hoursPerUnit: (c) => c.norm('veja_kastes_izbuve.koka_fasades_krasa_2_slani_darbnica_4m2'),
    hours: (c) => c.this.hoursPerUnit*(c.inp.soffit_area_m2*1.3),
    laborMarked: (c) => c.this.hoursMarkedPerUnit*c.this.rate*c.inp.soffit_area_m2,
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.koka_fasades_krasa_2_slani_darbnica_6m2', 'veja_kastes_izbuve.koka_fasades_krasa_2_slani_darbnica_6m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_fasades_krasa_l"},
    tools: ["Krāsošanas piederumi", "Lupatas", "Trauki iemērkšanai", "Nazis un asmeņi"],
  }),
  line({
    id: "veja_kastes_izbuve.ota_akrila_krasai_maza_2",
    row: 231,
    block: "veja_kastes_izbuve",
    name: "Ota akrila krāsai mazā",
    unit: "gb",
    note: "1gb/ 20m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/20, 0),
    reserve: 1,
    unitPrice: (c) => c.price('ota_akrila_krasai_maza'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.ota_akrila_krasai_maza_2', 'veja_kastes_izbuve.ota_akrila_krasai_maza_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ota_akrila_krasai_maza"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.ota_akrila_krasai_liela_2",
    row: 232,
    block: "veja_kastes_izbuve",
    name: "Ota akrila krāsai lielā",
    unit: "gb",
    note: "1gb/ 20m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/20, 0),
    reserve: 1,
    unitPrice: (c) => c.price('ota_akrila_krasai_liela'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.ota_akrila_krasai_liela_2', 'veja_kastes_izbuve.ota_akrila_krasai_liela_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "ota_akrila_krasai_liela"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.rullis_ar_rokturi_2",
    row: 233,
    block: "veja_kastes_izbuve",
    name: "Rullis ar rokturi",
    unit: "gb",
    note: "1gb/ 50m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/50, 0),
    reserve: 1,
    unitPrice: (c) => c.price('rullis_ar_rokturi'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.rullis_ar_rokturi_2', 'veja_kastes_izbuve.rullis_ar_rokturi_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "rullis_ar_rokturi"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.vannite_2",
    row: 234,
    block: "veja_kastes_izbuve",
    name: "Vannīte",
    unit: "gb",
    note: "1gb/ 40m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/40, 0),
    reserve: 1,
    unitPrice: (c) => c.price('vannite'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.vannite_2', 'veja_kastes_izbuve.vannite_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vannite"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_izbuve.spainitis_2",
    row: 235,
    block: "veja_kastes_izbuve",
    name: "Spainītis",
    unit: "gb",
    note: "1gb/ 40m2",
    qty: (c) => ceilUp(c.inp.soffit_area_m2/40, 0),
    reserve: 1,
    unitPrice: (c) => c.price('spainitis'),
    blockTotal: (c) => total(c.span('veja_kastes_izbuve.spainitis_2', 'veja_kastes_izbuve.spainitis_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "spainitis"},
    blank: ["hours"],
  }),

  // ---- Vēja kastes krāsošana, m2 ----
  line({
    id: "veja_kastes_krasosana.veja_kastes_krasosana_kartas",
    row: 236,
    block: "veja_kastes_krasosana",
    name: "Vēja kastes krāsošana Kārtas",
    unit: "m2",
    laborUnit: "m2",
    param: (c) => c.inp.paint_soffit_coats,
    qty: (c) => c.inp.paint_soffit_area_m2*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.veja_kastes_krasosana_1_kartas_krasosana'),
    blockMaterials: (c) => total(c.span('veja_kastes_krasosana.veja_kastes_krasosana_kartas', 'veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2', 'materials')),
    blockLabor: (c) => total(c.span('veja_kastes_krasosana.veja_kastes_krasosana_kartas', 'veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2', 'labor')),
    blockHours: (c) => total(c.span('veja_kastes_krasosana.veja_kastes_krasosana_kartas', 'veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2', 'hours')),
    blockTotal: (c) => total(c.span('veja_kastes_krasosana.veja_kastes_krasosana_kartas', 'veja_kastes_krasosana.veja_kastes_krasosana_kartas', 'blockMaterials', 'blockLabor')),
    tools: ["Krāsošanas piederumi", "Lupatas", "Trauki iemērkšanai", "Nazis un asmeņi"],
  }),
  line({
    id: "veja_kastes_krasosana.tirisana",
    row: 237,
    block: "veja_kastes_krasosana",
    name: "Tīrīšana",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.paint_soffit_cleaning_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.tirisana_pirms_krasosanas_tirisana'),
    blockTotal: (c) => total(c.span('veja_kastes_krasosana.tirisana', 'veja_kastes_krasosana.tirisana', 'blockMaterials', 'blockLabor')),
    tools: ["drāšu birste", "fleksis", "lapiņu diski", "brilles"],
  }),
  line({
    id: "veja_kastes_krasosana.koka_fasades_krasa_6m2_l",
    row: 238,
    block: "veja_kastes_krasosana",
    name: "Koka fasādes krāsa 6m2/l",
    unit: "l",
    param: 6,
    qty: (c) => c.line('veja_kastes_krasosana.veja_kastes_krasosana_kartas').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('koka_fasades_krasa_l'),
    blockTotal: (c) => total(c.span('veja_kastes_krasosana.koka_fasades_krasa_6m2_l', 'veja_kastes_krasosana.koka_fasades_krasa_6m2_l', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_fasades_krasa_l"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_krasosana.krasosanas_paliglidzekli_30m2",
    row: 239,
    block: "veja_kastes_krasosana",
    name: "Krāsošanas palīglīdzekļi 30m2",
    unit: "kpl",
    param: 30,
    qty: (c) => ceilUp(c.inp.paint_soffit_area_m2/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('krasosanas_paligmaterialu_komplekts_30m2'),
    blockTotal: (c) => total(c.span('veja_kastes_krasosana.krasosanas_paliglidzekli_30m2', 'veja_kastes_krasosana.krasosanas_paliglidzekli_30m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "krasosanas_paligmaterialu_komplekts_30m2"},
    blank: ["hours"],
  }),
  line({
    id: "veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2",
    row: 240,
    block: "veja_kastes_krasosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    qty: (c) => c.inp.paint_soffit_area_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    blockTotal: (c) => total(c.span('veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2', 'veja_kastes_krasosana.nosegsanas_materiali_1m2_1m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
    blank: ["hours"],
  }),

  // ---- Koka fasādes krāsošana, m2 ----
  line({
    id: "koka_fasades_krasosana.koka_fasade",
    row: 241,
    block: "koka_fasades_krasosana",
    name: "Koka fasāde",
    unit: "m2",
    laborUnit: "m2",
    param: (c) => c.inp.paint_wood_facade_coats,
    qty: (c) => c.this.param*c.inp.paint_wood_facade_area_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.koka_fasades_krasosana_1_kartas_krasosan'),
    blockMaterials: (c) => total(c.span('koka_fasades_krasosana.koka_fasade', 'koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'materials')),
    blockLabor: (c) => total(c.span('koka_fasades_krasosana.koka_fasade', 'koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'labor')),
    blockHours: (c) => total(c.span('koka_fasades_krasosana.koka_fasade', 'koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'hours')),
    blockTotal: (c) => total(c.span('koka_fasades_krasosana.koka_fasade', 'koka_fasades_krasosana.koka_fasade', 'blockMaterials', 'blockLabor')),
    tools: ["Krāsošanas piederumi", "Lupatas", "Trauki iemērkšanai", "Nazis un asmeņi"],
  }),
  line({
    id: "koka_fasades_krasosana.tirisana",
    row: 242,
    block: "koka_fasades_krasosana",
    name: "Tīrīšana",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.paint_wood_facade_cleaning_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.tirisana_pirms_krasosanas_tirisana'),
    blockTotal: (c) => total(c.span('koka_fasades_krasosana.tirisana', 'koka_fasades_krasosana.tirisana', 'blockMaterials', 'blockLabor')),
    tools: ["drāšu birste", "fleksis", "lapiņu diski", "brilles"],
  }),
  line({
    id: "koka_fasades_krasosana.koka_fasades_krasa_6m2_l",
    row: 243,
    block: "koka_fasades_krasosana",
    name: "Koka fasādes krāsa 6m2/l",
    unit: "l",
    param: 6,
    qty: (c) => c.line('koka_fasades_krasosana.koka_fasade').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('koka_fasades_krasa_l'),
    blockTotal: (c) => total(c.span('koka_fasades_krasosana.koka_fasades_krasa_6m2_l', 'koka_fasades_krasosana.koka_fasades_krasa_6m2_l', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_fasades_krasa_l"},
    blank: ["hours"],
  }),
  line({
    id: "koka_fasades_krasosana.krasosanas_paliglidzekli_30m2",
    row: 244,
    block: "koka_fasades_krasosana",
    name: "Krāsošanas palīglīdzekļi 30m2",
    unit: "kpl",
    param: 30,
    qty: (c) => ceilUp(c.inp.paint_wood_facade_area_m2/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('krasosanas_paligmaterialu_komplekts_30m2'),
    blockTotal: (c) => total(c.span('koka_fasades_krasosana.krasosanas_paliglidzekli_30m2', 'koka_fasades_krasosana.krasosanas_paliglidzekli_30m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "krasosanas_paligmaterialu_komplekts_30m2"},
    blank: ["hours"],
  }),
  line({
    id: "koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2",
    row: 245,
    block: "koka_fasades_krasosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    qty: (c) => c.inp.paint_wood_facade_area_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    blockTotal: (c) => total(c.span('koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'koka_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
    blank: ["hours"],
  }),

  // ---- Mūra fasādes krāsošana, m2 ----
  line({
    id: "mura_fasades_krasosana.mura_fasade_kartas",
    row: 246,
    block: "mura_fasades_krasosana",
    name: "Mūra fasāde, Kārtas",
    unit: "m2",
    laborUnit: "m2",
    param: (c) => c.inp.paint_masonry_coats,
    qty: (c) => c.inp.paint_masonry_area_m2*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.mura_fasades_krasosana_1_kartas_krasosan'),
    blockMaterials: (c) => total(c.span('mura_fasades_krasosana.mura_fasade_kartas', 'mura_fasades_krasosana.grunts', 'materials')),
    blockLabor: (c) => total(c.span('mura_fasades_krasosana.mura_fasade_kartas', 'mura_fasades_krasosana.grunts', 'labor')),
    blockHours: (c) => total(c.span('mura_fasades_krasosana.mura_fasade_kartas', 'mura_fasades_krasosana.grunts', 'hours')),
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.mura_fasade_kartas', 'mura_fasades_krasosana.mura_fasade_kartas', 'blockMaterials', 'blockLabor')),
    tools: ["Krāsošanas piederumi", "Lupatas", "Trauki iemērkšanai", "Nazis un asmeņi"],
  }),
  line({
    id: "mura_fasades_krasosana.tirisana",
    row: 247,
    block: "mura_fasades_krasosana",
    name: "Tīrīšana",
    unit: "m2",
    laborUnit: "m2",
    qty: (c) => c.inp.paint_masonry_cleaning_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    hoursPerUnit: (c) => c.norm('krasosana.tirisana_pirms_krasosanas_tirisana'),
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.tirisana', 'mura_fasades_krasosana.tirisana', 'blockMaterials', 'blockLabor')),
    tools: ["drāšu birste", "fleksis", "lapiņu diski", "brilles"],
  }),
  line({
    id: "mura_fasades_krasosana.mat_152_name",
    row: 248,
    block: "mura_fasades_krasosana",
    name: "",
    nameFrom: "material:caparol_fasades_krasa_universala_akrilata_kr",
    unit: "l",
    param: 7.5,
    qty: (c) => c.line('mura_fasades_krasosana.mura_fasade_kartas').qty/c.this.param,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('caparol_fasades_krasa_universala_akrilata_kr'),
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.mat_152_name', 'mura_fasades_krasosana.mat_152_name', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "caparol_fasades_krasa_universala_akrilata_kr"},
    blank: ["hours"],
  }),
  line({
    id: "mura_fasades_krasosana.krasosanas_paliglidzekli_30m2",
    row: 249,
    block: "mura_fasades_krasosana",
    name: "Krāsošanas palīglīdzekļi 30m2",
    unit: "kpl",
    param: 30,
    qty: (c) => ceilUp(c.inp.paint_masonry_area_m2/c.this.param, 0),
    reserve: 1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('krasosanas_paligmaterialu_komplekts_30m2'),
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.krasosanas_paliglidzekli_30m2', 'mura_fasades_krasosana.krasosanas_paliglidzekli_30m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "krasosanas_paligmaterialu_komplekts_30m2"},
    blank: ["hours"],
  }),
  line({
    id: "mura_fasades_krasosana.nosegsanas_materiali_1m2_1m2",
    row: 250,
    block: "mura_fasades_krasosana",
    name: "Nosegšanas materiāli 1m2=1m2",
    unit: "m2",
    qty: (c) => c.inp.paint_masonry_area_m2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('nosegsanas_pleve_m2'),
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'mura_fasades_krasosana.nosegsanas_materiali_1m2_1m2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "nosegsanas_pleve_m2"},
    blank: ["hours"],
  }),
  line({
    id: "mura_fasades_krasosana.grunts",
    row: 251,
    block: "mura_fasades_krasosana",
    name: "Grunts",
    unit: "l",
    laborUnit: "m2",
    param: (c) => c.inp.masonry_primer_coats,
    qty: (c) => c.inp.masonry_primer_area_m2*c.this.param/2,
    reserve: 1.1,
    qtyRes: (c) => c.this.reserve*c.this.qty,
    unitPrice: (c) => c.price('dzilumgrunts_cena_l'),
    hoursPerUnit: (c) => c.norm('krasosana.gruntesana_gruntesana'),
    hours: (c) => c.this.hoursPerUnit*c.inp.masonry_primer_area_m2*c.inp.masonry_primer_coats,
    blockTotal: (c) => total(c.span('mura_fasades_krasosana.grunts', 'mura_fasades_krasosana.grunts', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "dzilumgrunts_cena_l"},
  }),
];
