/**
 * Wall plates, rafters, trusses, splices.
 *
 * Generated from the estimator workbook (Tāme rows 25-52) by tools/generate-rules.py.
 * Each line mirrors one workbook row (`row` keeps the trace). Fields that are not listed use the standard
 * formulas in engine/line.ts; fields in `blank` are empty in the workbook and count as 0.
 */
import { line, type LineRule } from '../line';
import { ceilUp, total, if_, iferror } from '../functions';

export const LINES: LineRule[] = [

  // ---- Mūrlatas montāža, m ----
  line({
    id: "murlatas_montaza.n150x150",
    row: 25,
    block: "murlatas_montaza",
    name: "150x150, ",
    unit: "m3",
    laborUnit: "m",
    note: "garums/m +1m uz katru savienojumu",
    qty: (c) => c.inp.wall_plate_150x150_m,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0)*0.15*0.15,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('murlatas_montaza.murlatas_montaza_zagesana_ubrsana_kimisk'),
    blockMaterials: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni', 'materials')),
    blockLabor: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni', 'labor')),
    blockHours: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni', 'hours')),
    blockTotal: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.n150x150', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris", "Striķis un krīts"],
  }),
  line({
    id: "murlatas_montaza.n100x200",
    row: 26,
    block: "murlatas_montaza",
    name: "100x200",
    unit: "m3",
    laborUnit: "m",
    note: "garums/m +1m uz katru savienojumu",
    qty: (c) => c.inp.wall_plate_100x200_m,
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0)*0.1*0.2,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('murlatas_montaza.murlatas_montaza_zagesana_ubrsana_kimisk'),
    blockTotal: (c) => total(c.span('murlatas_montaza.n100x200', 'murlatas_montaza.n100x200', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris", "Striķis un krīts"],
  }),
  line({
    id: "murlatas_montaza.hidroizolacija_pvc_25cm_plata",
    row: 27,
    block: "murlatas_montaza",
    name: "Hidroizolācija PVC 25cm plata",
    unit: "m",
    laborUnit: "m",
    note: "mūrlatas garums",
    qty: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.n100x200', 'qty')),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('pvc_hidroizolacija_25cm'),
    hoursPerUnit: (c) => c.norm('murlatas_montaza.hidroizolacija_pvc_25cm_plata_murlatas_g'),
    blockTotal: (c) => total(c.span('murlatas_montaza.hidroizolacija_pvc_25cm_plata', 'murlatas_montaza.hidroizolacija_pvc_25cm_plata', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pvc_hidroizolacija_25cm"},
    tools: ["nazis"],
  }),
  line({
    id: "murlatas_montaza.vitnstieni_m12_30cm_3gb_m_kmpl_ar_uzgrie",
    row: 28,
    block: "murlatas_montaza",
    name: "Vītņstieņi M12, 30cm, 3gb/m kmpl ar uzgriežņiem",
    unit: "gb",
    param: 3,
    qty: (c) => total(c.span('murlatas_montaza.n150x150', 'murlatas_montaza.n100x200', 'qty'))*c.this.param,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('vitnstieni_m12_30cm_komplekts_ar_uzgriezniem'),
    blockTotal: (c) => total(c.span('murlatas_montaza.vitnstieni_m12_30cm_3gb_m_kmpl_ar_uzgrie', 'murlatas_montaza.vitnstieni_m12_30cm_3gb_m_kmpl_ar_uzgrie', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vitnstieni_m12_30cm_komplekts_ar_uzgriezniem"},
    blank: ["hours"],
    tools: ["fleksis", "flekša ripas", "seškantes atslēga M12"],
  }),
  line({
    id: "murlatas_montaza.koka_urbis_d14_1gb_30gb",
    row: 29,
    block: "murlatas_montaza",
    name: "Koka urbis D14, 1gb/30gb",
    unit: "gb",
    param: 30,
    qty: (c) => c.line('murlatas_montaza.vitnstieni_m12_30cm_3gb_m_kmpl_ar_uzgrie').qtyRes/c.this.param,
    reserve: 1,
    unitPrice: (c) => c.price('koka_urbis_d14_1gb_50gb'),
    blockTotal: (c) => total(c.span('murlatas_montaza.koka_urbis_d14_1gb_30gb', 'murlatas_montaza.koka_urbis_d14_1gb_30gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_urbis_d14_1gb_50gb"},
    blank: ["hours", "labor"],
    tools: ["urbjmašina"],
  }),
  line({
    id: "murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni",
    row: 30,
    block: "murlatas_montaza",
    name: "Ķīmiskais enkurs, 1gb/ 15gb vītņstieņi",
    unit: "gb",
    param: 15,
    qty: (c) => ceilUp(c.line('murlatas_montaza.vitnstieni_m12_30cm_3gb_m_kmpl_ar_uzgrie').qty/c.this.param, 0),
    reserve: 1.2,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kimiskais_enkurs'),
    blockTotal: (c) => total(c.span('murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni', 'murlatas_montaza.kimiskais_enkurs_1gb_15gb_vitnstieni', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kimiskais_enkurs"},
    blank: ["hours"],
    tools: ["hermētiķa pistole", "putekļu sūcējs"],
  }),

  // ---- Spāru montāža gb ----
  line({
    id: "sparu_montaza.n150x50",
    row: 31,
    block: "sparu_montaza",
    name: "150x50",
    unit: "m3",
    laborUnit: "gb",
    note: "solis 60cm, gb 6m",
    qty: (c) => c.inp.rafters_150x50_count,
    reserve: 1.15,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.15*0.05*6,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('sparu_montaza.sparu_montaza_iezagis_zagesana_montaza_s'),
    blockMaterials: (c) => total(c.span('sparu_montaza.n150x50', 'sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2', 'materials')),
    blockLabor: (c) => total(c.span('sparu_montaza.n150x50', 'sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2', 'labor')),
    blockHours: (c) => total(c.span('sparu_montaza.n150x50', 'sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2', 'hours')),
    blockTotal: (c) => total(c.span('sparu_montaza.n150x50', 'sparu_montaza.n150x50', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris", "Striķis un krīts"],
  }),
  line({
    id: "sparu_montaza.n200x50",
    row: 32,
    block: "sparu_montaza",
    name: "200x50",
    unit: "m3",
    laborUnit: "gb",
    note: "solis 60cm, gb 6m",
    qty: (c) => c.inp.rafters_200x50_count,
    reserve: 1.15,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.2*0.05*6,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('sparu_montaza.sparu_montaza_iezagis_zagesana_montaza_s'),
    blockTotal: (c) => total(c.span('sparu_montaza.n200x50', 'sparu_montaza.n200x50', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris", "Striķis un krīts"],
  }),
  line({
    id: "sparu_montaza.centrala_skruve_8x300mm_3gb_gb",
    row: 33,
    block: "sparu_montaza",
    name: "Centrālā skrūve 8x300mm, 3gb/gb",
    unit: "gb",
    param: 3,
    qty: (c) => total(c.span('sparu_montaza.n150x50', 'sparu_montaza.n200x50', 'qty'))*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_8x300'),
    blockTotal: (c) => total(c.span('sparu_montaza.centrala_skruve_8x300mm_3gb_gb', 'sparu_montaza.centrala_skruve_8x300mm_3gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_8x300"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sparu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas",
    row: 34,
    block: "sparu_montaza",
    name: "Leņķi 90x90 nostiprināšanai uz mūrlatas, 4gb/ gb",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*total(c.span('sparu_montaza.n150x50', 'sparu_montaza.n200x50', 'qty')),
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('pastiprinats_stura_lenkis_90x90x65x2m'),
    blockTotal: (c) => total(c.span('sparu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas', 'sparu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pastiprinats_stura_lenkis_90x90x65x2m"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits",
    row: 35,
    block: "sparu_montaza",
    name: "Skrūves 4.5x45, 6gb x leņķu skaits",
    unit: "gb",
    param: 6,
    qty: (c) => c.this.param*c.line('sparu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('kokskruve_t_4_5x45'),
    blockTotal: (c) => total(c.span('sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits', 'sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4_5x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sparu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits",
    row: 36,
    block: "sparu_montaza",
    name: "Enkurnaglas 70mm, 4gb x leņķu skaits",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*c.line('sparu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('enkurnaglas_70mm'),
    blockTotal: (c) => total(c.span('sparu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits', 'sparu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "enkurnaglas_70mm"},
    blank: ["hours"],
    tools: ["āmurs"],
  }),
  line({
    id: "sparu_montaza.starpsparu_balsti_galos_150x50_60cm_2gb",
    row: 37,
    block: "sparu_montaza",
    name: "Starpspāru balsti galos 150x50, 60cm, 2gb x spāres",
    unit: "m3",
    laborUnit: "gb",
    param: 2,
    qty: (c) => ceilUp(c.this.param*c.line('sparu_montaza.n150x50').qty*0.6, 0),
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.15*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('sparu_montaza.starpsparu_balsti_galos_150x50_60cm_2gb'),
    hours: (c) => c.this.hoursPerUnit*c.this.param*c.line('sparu_montaza.n150x50').qty,
    blockTotal: (c) => total(c.span('sparu_montaza.starpsparu_balsti_galos_150x50_60cm_2gb', 'sparu_montaza.starpsparu_balsti_galos_150x50_60cm_2gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris"],
  }),
  line({
    id: "sparu_montaza.starpsparu_balsti_galos_200x50_60cm_2gb",
    row: 38,
    block: "sparu_montaza",
    name: "Starpspāru balsti galos 200x50, 60cm, 2gb x spāres",
    unit: "m3",
    laborUnit: "gb",
    param: 2,
    qty: (c) => ceilUp(c.this.param*c.line('sparu_montaza.n200x50').qty*0.6, 0),
    reserve: 1.1,
    qtyRes: (c) => c.this.qty*c.this.reserve*0.2*0.05,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('sparu_montaza.starpsparu_balsti_galos_150x50_60cm_2gb'),
    hours: (c) => c.this.hoursPerUnit*c.this.param*c.line('sparu_montaza.n200x50').qty,
    blockTotal: (c) => total(c.span('sparu_montaza.starpsparu_balsti_galos_200x50_60cm_2gb', 'sparu_montaza.starpsparu_balsti_galos_200x50_60cm_2gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris"],
  }),
  line({
    id: "sparu_montaza.centrala_skruve_8x200mm_4gb_1gb_starpbal",
    row: 39,
    block: "sparu_montaza",
    name: "Centrālā skrūve 8x200mm 4gb/ 1gb starpbalsts",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*(c.line('sparu_montaza.n150x50').qty+c.line('sparu_montaza.n200x50').qty)*2,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_8x200'),
    blockTotal: (c) => total(c.span('sparu_montaza.centrala_skruve_8x200mm_4gb_1gb_starpbal', 'sparu_montaza.centrala_skruve_8x200mm_4gb_1gb_starpbal', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_8x200"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sparu_montaza.lenki_90x90_nostiprinasanai_2gb_1gb_stap",
    row: 40,
    block: "sparu_montaza",
    name: "Leņķi 90x90 nostiprināšanai, 2gb/ 1gb staprbalsts",
    unit: "gb",
    param: 2,
    qty: (c) => c.this.param*total(c.span('sparu_montaza.n150x50', 'sparu_montaza.n200x50', 'qty'))*2,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('pastiprinats_stura_lenkis_90x90x65x2m'),
    blockTotal: (c) => total(c.span('sparu_montaza.lenki_90x90_nostiprinasanai_2gb_1gb_stap', 'sparu_montaza.lenki_90x90_nostiprinasanai_2gb_1gb_stap', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pastiprinats_stura_lenkis_90x90x65x2m"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2",
    row: 41,
    block: "sparu_montaza",
    name: "Skrūves 4.5x45, 6gb x leņķu skaits\n",
    unit: "gb",
    param: 6,
    qty: (c) => c.line('sparu_montaza.lenki_90x90_nostiprinasanai_2gb_1gb_stap').qty*c.this.param,
    reserve: 1.1,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('kokskruve_t_4_5x45'),
    blockTotal: (c) => total(c.span('sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2', 'sparu_montaza.skruves_4_5x45_6gb_x_lenku_skaits_2', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4_5x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),

  // ---- Jumta kopņu montāža gb ----
  line({
    id: "jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas",
    row: 42,
    block: "jumta_kopnu_montaza",
    name: "Jumta kopnes pasūtītas, projektētas.",
    unit: "gb",
    laborUnit: "gb",
    note: "gb",
    qty: (c) => total([c.inp.trusses_1_count, c.inp.trusses_2_count]),
    reserve: 1,
    hoursPerUnit: (c) => c.norm('jumta_kopnu_montaz.jumta_kopnes_pasutitas_projektetas_monta'),
    blockMaterials: (c) => total(c.span('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas', 'jumta_kopnu_montaza.skerssijas', 'materials')),
    blockLabor: (c) => total(c.span('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas', 'jumta_kopnu_montaza.skerssijas', 'labor')),
    blockHours: (c) => total(c.span('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas', 'jumta_kopnu_montaza.stiprinajumi', 'hours')),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas', 'jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas', 'blockMaterials', 'blockLabor')),
  }),
  line({
    id: "jumta_kopnu_montaza.centrala_skruve_8x300mm_3gb_gb",
    row: 43,
    block: "jumta_kopnu_montaza",
    name: "Centrālā skrūve 8x300mm, 3gb/gb",
    unit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('kokskruve_t_8x300'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.centrala_skruve_8x300mm_3gb_gb', 'jumta_kopnu_montaza.centrala_skruve_8x300mm_3gb_gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_8x300"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi", "Striķis un krīts"],
  }),
  line({
    id: "jumta_kopnu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas",
    row: 44,
    block: "jumta_kopnu_montaza",
    name: "Leņķi 90x90 nostiprināšanai uz mūrlatas, 4gb/ gb",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*c.line('jumta_kopnu_montaza.jumta_kopnes_pasutitas_projektetas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('pastiprinats_stura_lenkis_90x90x65x2m'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas', 'jumta_kopnu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "pastiprinats_stura_lenkis_90x90x65x2m"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_kopnu_montaza.skruves_4_5x45_6gb_x_lenku_skaits",
    row: 45,
    block: "jumta_kopnu_montaza",
    name: "Skrūves 4.5x45, 6gb x leņķu skaits",
    unit: "gb",
    param: 6,
    qty: (c) => c.this.param*c.line('jumta_kopnu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('kokskruve_t_4_5x45'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.skruves_4_5x45_6gb_x_lenku_skaits', 'jumta_kopnu_montaza.skruves_4_5x45_6gb_x_lenku_skaits', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokskruve_t_4_5x45"},
    blank: ["hours"],
    tools: ["skrūvmašīna un uzgaļi"],
  }),
  line({
    id: "jumta_kopnu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits",
    row: 46,
    block: "jumta_kopnu_montaza",
    name: "Enkurnaglas 70mm, 4gb x leņķu skaits\n",
    unit: "gb",
    param: 4,
    qty: (c) => c.this.param*c.line('jumta_kopnu_montaza.lenki_90x90_nostiprinasanai_uz_murlatas').qty,
    reserve: 1.1,
    unitPrice: (c) => c.price('enkurnaglas_70mm'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits', 'jumta_kopnu_montaza.enkurnaglas_70mm_4gb_x_lenku_skaits', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "enkurnaglas_70mm"},
    blank: ["hours"],
    tools: ["āmurs"],
  }),
  line({
    id: "jumta_kopnu_montaza.diognales",
    row: 47,
    block: "jumta_kopnu_montaza",
    name: "Diognāles",
    unit: "m3",
    note: "Atkarībā no projekta",
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.diognales', 'jumta_kopnu_montaza.diognales', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    blank: ["hours"],
  }),
  line({
    id: "jumta_kopnu_montaza.skerssijas",
    row: 48,
    block: "jumta_kopnu_montaza",
    name: "Škērssijas",
    unit: "m3",
    note: "Atkarībā no projekta",
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.skerssijas', 'jumta_kopnu_montaza.skerssijas', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    blank: ["hours"],
  }),
  line({
    id: "jumta_kopnu_montaza.stiprinajumi",
    row: 49,
    block: "jumta_kopnu_montaza",
    name: "Stiprinājumi",
    blockTotal: (c) => total(c.span('jumta_kopnu_montaza.stiprinajumi', 'jumta_kopnu_montaza.stiprinajumi', 'blockMaterials', 'blockLabor')),
    blank: ["qtyRes", "materials", "hours", "labor", "laborMarked", "total"],
  }),

  // ---- Protēzes gb ----
  line({
    id: "protezes.proteze_garums_1_5m_videji",
    row: 50,
    block: "protezes",
    name: "Protēze, garums 1.5m (vidēji)",
    unit: "m3",
    laborUnit: "gb",
    qty: (c) => c.inp.rafter_splices_count,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0)*0.05*0.15,
    unitPrice: (c) => c.price('kokmateriali_impregneti'),
    hoursPerUnit: (c) => c.norm('protezes.proteze_garums_1_5m_videji_zagesana_ieza'),
    blockMaterials: (c) => total(c.span('protezes.proteze_garums_1_5m_videji', 'protezes.koka_urbis_d14_1gb_30gb', 'materials')),
    blockLabor: (c) => total(c.span('protezes.proteze_garums_1_5m_videji', 'protezes.koka_urbis_d14_1gb_30gb', 'labor')),
    blockHours: (c) => total(c.span('protezes.proteze_garums_1_5m_videji', 'protezes.koka_urbis_d14_1gb_30gb', 'hours')),
    blockTotal: (c) => total(c.span('protezes.proteze_garums_1_5m_videji', 'protezes.proteze_garums_1_5m_videji', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "kokmateriali_impregneti"},
    tools: ["cirkulārais zāģis", "zobenzāģis", "trīstūris"],
  }),
  line({
    id: "protezes.vitnstieni_m12_30cm_komplekts_ar_uzgriez",
    row: 51,
    block: "protezes",
    name: "Vītnstieņi M12 30cm komplekts ar uzgriežņiem  3gb/ gb",
    unit: "gb",
    laborUnit: "gb",
    param: 3,
    qty: (c) => c.this.param*c.line('protezes.proteze_garums_1_5m_videji').qty,
    reserve: 1.05,
    qtyRes: (c) => ceilUp(c.this.qty*c.this.reserve, 0),
    unitPrice: (c) => c.price('vitnstieni_m12_30cm_komplekts_ar_uzgriezniem'),
    hoursPerUnit: (c) => c.norm('protezes.vitnstieni_m12_30cm_komplekts_ar_uzgriez'),
    blockTotal: (c) => total(c.span('protezes.vitnstieni_m12_30cm_komplekts_ar_uzgriez', 'protezes.vitnstieni_m12_30cm_komplekts_ar_uzgriez', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "vitnstieni_m12_30cm_komplekts_ar_uzgriezniem"},
    tools: ["fleksis", "flekša ripas", "seškantes atslēga M12"],
  }),
  line({
    id: "protezes.koka_urbis_d14_1gb_30gb",
    row: 52,
    block: "protezes",
    name: "Koka urbis D14, 1gb/30gb",
    unit: "gb",
    param: 30,
    qty: (c) => ceilUp(c.line('protezes.vitnstieni_m12_30cm_komplekts_ar_uzgriez').qty/c.this.param, 0),
    reserve: 1,
    unitPrice: (c) => c.price('koka_urbis_d14_1gb_50gb'),
    blockTotal: (c) => total(c.span('protezes.koka_urbis_d14_1gb_30gb', 'protezes.koka_urbis_d14_1gb_30gb', 'blockMaterials', 'blockLabor')),
    priceRef: {"type": "mat", "id": "koka_urbis_d14_1gb_50gb"},
    blank: ["hours"],
    tools: ["urbjmašina"],
  }),
];
